### ISSUE TITLE
Communication platform for Kiwi TCMS users

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#1003]
If there is interest from other users of Kiwi TCMS (and the development team gives their permission) I would like to see some kind of instant messaging platform where we (=users of Kiwi TCMS) would have the chance to talk to each other, share usage tips'n'tricks etc. I can take care of all the administration associated with creating and maintaining such communication channel.

Current ideas (but not limited to) are:
- Slack channel
- Discord server
- IRC server
- Telegram channel

Please up-vote the issue if you are interested (or down-vote if you do not agree with it)  in this and comment with your preferred communications platform - either from the list above or maybe something you think it would be more suitable.

**Comment by okainov** [comment]
What about forum? Or am I too oldschool?

**Comment by atodorov** [comment]
FTR we've always had #kiwitcms on Freenode and it was andvertised on the website for some time. Noone has ever used this communication channel so I believe it is totally obsolete.

**Comment by atodorov** [comment]
After asking around it turns out lots of big OSS projects now use Discourse so here it is:
https://kiwitcms.discourse.group/

It needs to be listed on the website as well but let's close this issue for now.
