### ISSUE TITLE
Improvements for TestCase search

### ISSUE THREAD

**Issue by Tomasito-cca** [kiwitcms/Kiwi#1014]
**Current implementation:**

When users clicks to Search / Search TestCase - Test cases are unnecessarily loaded and it takes a long time to enter search criteria... It would be good to change that.

**Proposed implementation of search optimization:**

Don't search automatically. Search after pressing the search button.

**Comment by atodorov** [comment]
Page behavior is not going to change but maybe there can be some optimization to show results faster. Keeping this issue open to investigate what can be sped up. 

Also when you say something is slow post some times and your server parameters. On public.tenant it takes less than 2 seconds for the initial RPC call to fetch all data which is not that bad considering we load nearly 2000 entries ATM.
