### ISSUE TITLE
RFC: Remove model Bug in favor of LinkReference

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1029]
ATM we're thinking to refactor "bug display" functionality by making the following changes which will enable several issues to be resolved.
![bug_linkreference](https://user-images.githubusercontent.com/1002300/62125822-e10d4700-b2d6-11e9-9b51-879f3ceb9215.png)

The idea is to replace `Bug` model with `LinkReference`. Directly makes #320 obsolete and also somewhat negates the necessity to have per-bug tracker support/LinkOnly bug tracker. So when you have an existing bug report (or have just reported a new one) you will only have to paste its URL into Kiwi TCMS UI. Very similar (even a bit simpler) to what we currently have.

List of changes:
1) add new field `is_defect` to `LinkReference` which will be primarily used in queries so we can show the reported defects in various pages in the UI
2) provide data migration to convert existing `Bug` records into `LinkReference` records
3) Update the UI in TestExecution widget as shown on the image above
4) Update TestRun report page section showing defects for the current TR (use new query against LR)
5) Update TestCase page section showing bugs (use new query against LR)
6) Remove API around `Bug` model.
7) Update/add new API for adding LinkReferences where necessary. Also show from which TR this bug is.
8) Start using a JavaScript library to show bug details (#117). This will be based on the OpenGraph protocol. If no OG tags are provided fallback to using `<title>` HTML tag. Some bug trackers do support OpenGraph, others most notably Bugzilla do not!
9) The script in previous step will be designed with the possibility to expand/overwrite so you can add your own customizations if desired.

Changes will be in the `remove_bug_use_linkreference` branch which will stay open for around a month after this issue is closed to give opportunity for beta testing of this change.

I will open another RFC for the Report/Comment functionalities.

CC @okainov, @Prome88 since you've commented/reported on other related issues as well

**Comment by okainov** [comment]
Doesn't look like a good idea at all IMO. It is again defeaturing the tool. I understand you want to throw away all legacy stuff, but this concept was quite useful and important.

>add new field is_defect to LinkReference which will be primarily used in queries so we can show the reported defects in various pages in the UI

Why? All bugs are defects.

>Start using a JavaScript library to show bug details
Bad idea, bug details should be cached in Kiwi, because request to issue trackers takes some time. Especially Jira is quite slow.

> you will only have to paste its URL
Bad idea, I do not want to copy-paste links, I want to use bugs IDs

**Comment by atodorov** [comment]
> It is again defeaturing the tool.

This is definitely not the case. The feature is "linking to existing bugs" which will still be possible. You may not agree on the internal workings but the same feature will continue to be available using very similar UI and workflow.

Now with that out of the way a few question:

> bug details should be cached in Kiwi, because request to issue trackers takes some time. 

- which bug details ? ATM we can definitely do name/title. What other fields ? Mind you these must be universally applicable between other bug tracking tools and JIRA because we don't want to special case support for bug trackers.
- How slow is slow enough that it makes sense to use internal cache? Why not simply work on optimizing network or JIRA speed ? We need some numbers, saying "it is slow" is not actionable information
- Some form of caching can probably be done on the browser side as well, needs investigation
- How do you imagine "Refresh cache" to work ? What do we do when users don't click "Refresh cache" but complain that Kiwi TCMS shows them different information compared to their bug tracker ?

**Comment by atodorov** [comment]
@okainov another question: 

How would you implement the feature "Linking to existing bug reports" from 8 different bug tracking systems on the backend ? Looking for implementation ideas. 

We definitely want to get away from special casing each of these bug trackers and make support more unified (think BT features/protocols supported) to make it possible to work with any kind of bug tracker system.

**Comment by okainov** [comment]
>which bug details ? ATM we can definitely do name/title. What other fields ? 

State and Exposure as the *very* least. Submit date and Submitter as other examples. General abstract interface should know all of those and if some if issue trackers does not want to implement some methods - up to them, no problems.

>How slow is slow enough that it makes sense to use internal cache? 

Establishing connection ~5sec, query data per bug ~1 sec => first load of the page with 20 bugs is 25 sec. Slow enough for me.

If there are two issue trackers in use - multiply by two.

>Why not simply work on optimizing network or JIRA speed ?

Jira is maintained by corporate IT. Plus authorization. No chance. Everything is already in internal network. In case of big companies physical location can be the other side of the planet (US-EU).

>How do you imagine "Refresh cache" to work ? What do we do when users don't click "Refresh cache" but complain that Kiwi TCMS shows them different information compared to their bug tracker ?

In our Kiwi we just set up bugs synchronization with cron every hour. Full sync currently (maybe just around couple of hundreds bugs linked in Kiwi) takes ~5-10 minutes. Timeout can be configurable.



>How would you implement the feature "Linking to existing bug reports" from 8 different bug tracking systems on the backend ? Looking for implementation ideas.

What do you mean? Same as you have now, what's the problem?

`class AbstractBugTracker:

  def __init__(self, id):
    self.id = id

  def get_title(self):
    return self.id

  def get_exposure(self):
    return Exposure.NA

  def get_whatever(self):
    return 'whatever default dummy value

class Jira(AbstractBugTracker):
  def get_title(self):
    if self.title:
      return self.title
    else:
      jira = PyJira.establish_connection(credentials)
      self.title = jira.get_issue_title(self.id)
       return self.title
`

Somehow, just pseudocode. Abstract interface and its implementation :)
