### ISSUE TITLE
Test Plan - Case - Clone - No test cases shown on clone page

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#1054]
### Description of problem
In test plan which has bigger amount of test cases and checkbox Also select all test cases that are not yet shown below is selected not test cases are shown on clone test cases page.

### Version or commit hash (if applicable)
6.11

### Steps to Reproduce

1. Open https://public.tenant.kiwitcms.org/plan/1219/performance-baseline-tp-at-2018-10-26-14-39-56#testcases
2. Check Also select all cases that are not yet shown below.
3. Click Case
4. Click Clone
5. Go back one page
6. Un-check Also select all cases that are not yet shown below.
7. Click Case
8. Click Clone

### Actual results
Blank page shown.
![image](https://user-images.githubusercontent.com/25688732/62682931-99b14580-b9bd-11e9-8d45-6c5de36e67cd.png)

### Expected results
All selected test cases shown.

**Comment by atodorov** [comment]
As a workaround expand all test cases before cloning.
