### ISSUE TITLE
testcases/migrations/0007_convert_is_automated_to_boolean.py failing on postgresql

### ISSUE THREAD

**Issue by clee** [kiwitcms/Kiwi#1059]
### Description of problem

I use Kiwi with PostgreSQL, and I'm trying to upgrade an older installation to the newest code. I ran `/Kiwi/manage.py migrate` after successfully building a new docker image locally, and it errored out.

### Version or commit hash (if applicable)
~~`1921d5f5fe8bd7cc33484480f539879b1e252883`~~
`7764bf10fa403111473bba4b824e78ff98d3be3b`

### Steps to Reproduce

1. Start from old working Kiwi installation using PostgreSQL database backend
2. Build latest code from github locally
3. Run `manage.py migrate`

### Actual results
```
Operations to perform:
  Apply all migrations: admin, attachments, auth, contenttypes, core, django_comments, kiwi_auth, linkreference, management, sessions, sites, testcases, testplans, testruns
Running migrations:
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying management.0004_remove_sortkey_description... OK
  Applying management.0005_order_by_name... OK
  Applying testcases.0005_remove_unused_fields... OK
  Applying testcases.0006_merge_text_field_into_testcase_model... OK
  Applying testcases.0007_convert_is_automated_to_boolean...Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "testcases_historicaltestcase" because it has pending trigger events
```

### Expected results
Successful migration to the latest database layout.

### Additional info (Python traceback, logs, etc.)
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 178, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 487, in remove_field
    self.execute(sql)
  File "/venv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: cannot ALTER TABLE "testcases_historicaltestcase" because it has pending trigger events
```

**Comment by atodorov** [comment]
According to this answer here:
https://stackoverflow.com/questions/12838111/django-db-migrations-cannot-alter-table-because-it-has-pending-trigger-events

> Every migration is inside a transaction. In PostgreSQL you must not update the table and then alter the table schema in one transaction.

which is exactly what we were doing. 

FTR tests have not shown this error. In production we also use Postgres and haven't seen this failure so I'm not sure why it happens for you.  Can you post some more info: 

1) git tells me `1921d5f5fe8bd7cc33484480f539879b1e252883` is a bad object, I don't find it locally on my computer. I'm wondering if this isn't a custom commit and more precisely before/after which released version that is.

2) `./manage.py showmigrations` before you try to upgrade. I want to see which migrations have been applied already and if they also contain data + schema migration in the same file.

**Comment by clee** [comment]
> git tells me 1921d5f5fe8bd7cc33484480f539879b1e252883 is a bad object, I don't find it locally on my computer. I'm wondering if this isn't a custom commit and more precisely before/after which released version that is.

Ah, yes! My bad, that's my rebased commit customizing the Dockerfile for postgresql support. It was rebased on top of `7764bf10fa403111473bba4b824e78ff98d3be3b`, sorry.

I have a local postgresql dump I took of the database before attempting the upgrade; I'll re-do it and post the update here.

**Comment by clee** [comment]
Here's what `/Kiwi/manage.py showmigrations` shows me before attempting the upgrade:

```
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
attachments
 [X] 0001_initial
 [X] 0002_auto_20180104_1247
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [ ] 0010_alter_group_name_max_length
 [ ] 0011_update_proxy_permissions
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
core
 [X] 0001_squashed
django_comments
 [X] 0001_initial
 [X] 0002_update_user_email_field_length
 [X] 0003_add_submit_date_index
kiwi_auth
 [X] 0001_initial
linkreference
 [X] 0001_squashed
management
 [X] 0003_squashed
 [ ] 0004_remove_sortkey_description
 [ ] 0005_order_by_name
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
testcases
 [X] 0001_initial
 [X] 0004_squashed
 [ ] 0005_remove_unused_fields
 [ ] 0006_merge_text_field_into_testcase_model
 [ ] 0007_convert_is_automated_to_boolean
 [ ] 0008_notifications_default_true
 [ ] 0009_populate_missing_text_history
testplans
 [X] 0005_squashed
 [ ] 0006_remove_testplan_owner
 [ ] 0007_notifications_default_true
testruns
 [X] 0004_squashed
 [ ] 0005_remove_unused_fields
 [ ] 0006_rename_test_case_run_to_test_execution
```

**Comment by atodorov** [comment]
> Ah, yes! My bad, that's my rebased commit customizing the Dockerfile for postgresql support. It was rebased on top of 7764bf10fa403111473bba4b824e78ff98d3be3b, sorry.

FTR you can change the DB layer and settings without the need to modify files in the main repository. You can add your Dockerfile/docker-compose.yml/local_settings.py into another repository and work from there, but this is not the issue here.

The oldest unapplied migration is  `0006_remove_testplan_owner` which is from 06 Oct 2018, which tells me you are using version 6.0 (released 04 Oct 2018) or earlier. Direct upgrade to the latest version is not supported, see CHANGELOG and blog post for instructions.

Unless you are trying to upgrade from version 6.1.1 as documented this is not going to work.

Give us an indication which is the version you are trying to upgrade from. If it is older than 6.1.1 upgrade in steps as shown on the blog. There's nothing we can do about it b/c some of the migration files have been removed between versions.

**Comment by clee** [comment]
> Direct upgrade to the latest version is not supported, see CHANGELOG and blog post for instructions.

Yeah, I missed that part. I was able to work around it and fix my upgrade anyway without following the official instructions.

I'll close this out since direct upgrades from such old versions are unsupported. Thanks for helping me dig into it!
