### ISSUE TITLE
Preview for Localisation purposes

### ISSUE THREAD

**Issue by borianamavramova** [kiwitcms/Kiwi#1098]
Please introduce possibility to check somehow the translated strings so that the localisation becomes perfect.

**Comment by Prome88** [comment]
A partial solution is already available in Crowdin. Each translation string can have a picture and description set in the field Context from which translator can more easily understand where the string is shown and in what context. But many of the strings are currently without context in Crowdin. You can request the context via:

> If the source string does not have any context and it isn’t clear how to translate it, click Request and project manager will be notified that additional explanations are required.

This unfortunately does not solve the issue of checking the display of translated string - if it's long / short enough....
