### ISSUE TITLE
Use httpd Docker image

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#1100]
Is there any reason you use pure `centos` image instead of using official Apache's `httpd` image? https://hub.docker.com/_/httpd

Should be quite standard and much better than handling everything (python and Apache) by yourself

**Comment by atodorov** [comment]
The official docker images that we build are based on CentOS 8, also our entire build and hosting infrastructure is Red Hat based and privately built downstream images are also Red Hat based. We're not going to use the upstream image from Apache.

Feel free to open pull request which make it possible to build on top of other base images but we can't maintain them.
