### ISSUE TITLE
new linter: [l10n] reduce the number of similar strings

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1126]
There are some very similar (sometimes even the same) strings. They differ in capitalization or spelling.  In general we'd like to minimize the number of translatable strings to make it easier for language translators.

Kiwi TCMS needs a custom kiwi_lint/ checker which will discover all similar strings (that are marked for translation) and warn about them so we can gradually remove duplicates.

See the `textdistance` package mentioned in the comment below. That sounds like a good candidate to plug into our customized pylint infrastructure.

**Definition of Done**:
- new checker class under `kiwi_lint/` which implements the necessary pylint machinery
- Checker uses the levenstein distance algorithm (for starters), we may decide to change it later.
- NOTE: initially the checker probably wants to pay attention only to strings marked for translation (as opposed to any kind of string constant), see #733 
- NOTE2: at some point before this checker is merged we need to teach it how to parse templates and extract all strings marked for translation before comparing them
- Note3: this checker will likely need to consider "similarity percentage". Let's say 80% or above would be considered duplicate strings. The actual value must be a class attribute so we can play around with it, later we may turn it into a linter configuration.
- All code review passed & PR merged

Here's me explaining how to write pylint plugins:
- https://www.youtube.com/watch?v=3CkSKUNMLJc
- https://www.youtube.com/watch?v=D1wLFyazTRM

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Comment by atodorov** [comment]
Several tools & algorithms which can help with this:

> frequently-used algorithms for string edit distance:
> Levenshtein & Damerau Levenshtein distance
> Jaro & Jaro-Winkler distance
> N-Gram distance

> The scipy package has several implementations of "distances". all of them are useful in one way to another to make these comparisons. 
> Another package (related only for this topic) is https://pypi.org/project/textdistance/

> There are many such algorithms, starting with the venerable Soundex 
> algorithm, the well-known Levenshtein distance, and many more.

> You're looking for https://en.m.wikipedia.org/wiki/Levenshtein_distance , there's a python module that implements this already (actually an extension, for speed)


We need to figure out which one is best suited for us and doesn't produce lots of false results.

**Comment by Prome88** [comment]
What about something more simple for start:
https://github.com/civicrm/l10n/blob/master/bin/find-similar-strings.php

**Comment by souravsingh** [comment]
@atodorov I am willing to take a stab at this issue.

**Comment by brymut** [comment]
Hi @souravsingh , are you still going to try this one out, as I would like to have a go at it.

**Comment by souravsingh** [comment]
I am working on this issue

**Comment by brymut** [comment]
Okay, no problem.

**Comment by atodorov** [comment]
> I am working on this issue

@souravsingh  I don't see a PR open for it. If you are working on this issue then open a PR because it has been more than 1 month already.

@brymut feel free to take a stab at this.

**Comment by souravsingh** [comment]
Sorry for not opening the PR @atodorov, I was hesitant to put a PR without checking if the distance algorithm worked nicely. I can put in a WIP Pull request if needed.

**Comment by 17sushmita** [comment]
@atodorov May I work on this issue?
