### ISSUE TITLE
Static file not loading in a subdirectory

### ISSUE THREAD

**Issue by vesamet** [kiwitcms/Kiwi#1129]
### Description of problem
I am unable to run kiwi via docker in a subdirectory. ex: www.mysiteweb.com/kiwi with a reverse proxy (nginx)
Here is my current configuration:

```
#kiwi // port 8005                                                                                                                                                                          location /kiwi {
proxy_pass  http://localhost:8005;
proxy_set_header    Host                $http_host;
proxy_set_header    X-Real-IP           $remote_addr;
proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Proto $scheme;
}
```

### Actual results
I get what i think is a redirection loop:
The firefox error is: "the page isn’t redirecting properly"

### Expected results
Run kiwi in a subdirectory: www.mysiteweb.com/kiwi 

### Additional info
I use the default docker-compose.yml config, but use my own database. (i've been able to perform the shema migration successfully)

**Comment by vesamet** [comment]
Found my issue

**Comment by vesamet** [comment]
Updated with another problem in regard to static files

**Comment by atodorov** [comment]
This is a support question for StackOverflow and not a bug.

**Comment by vesamet** [comment]
Oh sorry.
https://stackoverflow.com/questions/57963804/kiwi-tcms-static-file-not-loading-in-a-subdirectory
