### ISSUE TITLE
Internal Bug Tracker: Edit Own Comment in a Bug

### ISSUE THREAD

**Issue by csonuryilmaz** [kiwitcms/Kiwi#1151]
### Description of problem
When we use "Report Bug" button from **Test Execution** using internal KiwiTCMS bug tracker, Kiwi opens  a new **bug** with default explanation that came from **TE**. 

This process does not allow us to modify **bug** description.

### Version or commit hash (if applicable)
7.0

### Steps to Reproduce

1. Go to any test exection from an eligible test run.
2. Click on "Report Bug" button.
3. Select KiwiTCMS internal bug tracker from "Issue Tracker" dropdown list.
4. Click on "Report" button.

### Actual results
New created bug contains auto-generated description from test execution which I didn't have a chance to modify.

### Expected results
Bug description is added as an user comment. If a user can modify his/her own comments on a bug, we can have an opportunity to modify bug description. 

For example, I want to remove components part from description and I want to add some more information into actual results in order to explain what really happened.
![example](https://user-images.githubusercontent.com/7355362/65832149-f992e100-e2c8-11e9-9b6a-d64fc8f2e250.png)

**Comment by atodorov** [comment]
Editing comments is not a feature we will support unless more people upvote this issue. This kind of defeats the purpose of having traceable history over who said what. (Bugzilla works like that too, maybe others).

The information that gets auto-generated can be configured. We'll do a blog post about this with examples.

Anything else you can just add as a new comment so the priority here doesn't appear very high.

**Comment by csonuryilmaz** [comment]
> .. The information that gets auto-generated can be configured. We'll do a blog post about this with examples. ..

:+1: I'll try to follow blog/documentation updates. It will be useful for us to be able to modify auto generated text.

> .. Anything else you can just add as a new comment ..

You're right, from a different perspective I can add a new comment for additional information.

**Comment by atodorov** [comment]
For the display of component information see 
https://github.com/kiwitcms/Kiwi/issues/1157

once we have the blog post/documentation for the rest I will close this issue.

**Comment by atodorov** [comment]
How to override the information automatically shown for bugs is documented at:
https://kiwitcms.org/blog/atodorov/2019/11/11/how-to-override-bug-details-in-kiwi-tcms/

We'll do a similar blog post showing how to override the information which is used for automatically reporting bugs.

**Comment by atodorov** [comment]
> We'll do a similar blog post showing how to override the information which is used for automatically reporting bugs.

https://kiwitcms.org/blog/atodorov/2020/07/11/customize-the-information-used-for-1-click-bug-reports/
