### ISSUE TITLE
Internal Bug Tracker: Reopen a Bug

### ISSUE THREAD

**Issue by csonuryilmaz** [kiwitcms/Kiwi#1152]
### Description of problem
When we mistakenly close bug, we don't have a way to reopen it.

### Version or commit hash (if applicable)
7.0

### Steps to Reproduce

1. Open a bug with either from "Testing > New Bug" menu or "Report Bug" button from a test execution.
2. Click on red "Close" button located at bottom right-hand-side.

### Actual results
Now the bug is closed. But we don't have any opportunity to reopen it, especially for mistaken actions.

### Expected results
For a closed bug, there may be a "Reopen" (may be different color like orange) button on the page. When user clicks on, the bug becomes "Open" again with a suitable note/comment about the state change. 

Also this action can be placed in "Edit" bug page.

**Comment by cmbahadir** [comment]
Hey,

First i wanted to be sure if this issue is still active. 
If its still a desired feature (IMO it is :)) i can open a PR for this.
