### ISSUE TITLE
Is it possible to clone multiple test cases to some product at once?

### ISSUE THREAD

**Issue by babbit0809** [kiwitcms/Kiwi#1182]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
It's troublesome to clone a test case at once.

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
This is a support question which should be asked on StackOverflow as per the instructions above. Closing.
