### ISSUE TITLE
Update Issue template to be new style

### ISSUE THREAD

**Issue by eddiejaoude** [kiwitcms/Kiwi#1183]
Issue template is the old style, update to be the new style

**Comment by atodorov** [comment]
Proposed change in https://github.com/kiwitcms/Kiwi/pull/1184.

As commented in the PR we don't differentiate between issues so this change is not needed.  If users who report issues for this project more actively find the feature useful please comment with the type of issues that you propose to have (this affects GitHub UI) and the information required for every type (will affect the template). Until then closing.
