### ISSUE TITLE
Enable black & isort in --check && --diff mode first

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1193]
In CI we can do something like:

```
black --diff tcms
black --check tcms

isort -rc --diff tcms/
isort -rc tcms/
```

Initially will allow it to fail but we'll clean up the mess over time and make this mandatory.

**Comment by rajibmitra** [comment]
I can take this one. @atodorov

**Comment by atodorov** [comment]
@rajibmitra waiting for pull request then :-)
