### ISSUE TITLE
node_modules folder for patternfly is not in place in static folder

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#120]
### Description of problem
I was installing the tool on our new server and found out that some statics are not in place, and it's leading to non-working JS menu, for example.
Example of missing file: <website>/static/patternfly/node_modules/jquery/dist/jquery.min.js

### Component (web, API, etc)
web, docker deployment

### Version or commit hash (if applicable)
latest

### How often reproducible
saw it once, but probably on every clean installation

### Steps to Fix

1. Go into docker container `docker exec -it kiwi_web /bin/bash`
2. Go to /Kiwi directory
3. run `npm install patternfly`
4. run `manage.py collectstatic --noinput`
5. New 2900+ files should be copied.

### Actual result
In static folder /usr/share.... in patternfly folder "node modules" is missing. It had only "dist" folder.

### Additional info
I double-checked - npm install patternfly is present in docker compose file, and there were no visible errors when I was running `make docker image`, but

**Comment by GodfatherThe** [comment]
Ok, seems my solution was wrong, it didn't work all the time (but it worked sometimes!), more corrent is to fix jquery and bootstrap locations in tcms/templates/patternfly.html from `patternfly/node_modules/jquery/dist/jquery.min.js` to `jquery/dist/jquery.min.js`

**Comment by atodorov** [comment]
Sorry for the late reply. Your issue sounds like a change caused by patternfly itself. Locally I have
```
$ npm list
/home/senko/Kiwi
└─┬ patternfly@3.27.3
  ├── bootstrap@3.3.7
  ├── bootstrap-datepicker@1.6.4
  ├── bootstrap-select@1.12.4
  ├── bootstrap-switch@3.3.4
  ├── bootstrap-touchspin@3.1.1
  ├── c3@0.4.17
  ├── d3@3.5.17
  ├── datatables.net@1.10.15
  ├── datatables.net-colreorder@1.3.3
  ├─┬ datatables.net-colreorder-bs@1.3.3
  │ └── datatables.net-bs@1.10.15
  ├── datatables.net-select@1.2.2
  ├── drmonty-datatables-colvis@1.1.2
  ├── eonasdan-bootstrap-datetimepicker@4.17.47
  ├── font-awesome@4.7.0
  ├── google-code-prettify@1.0.5
  ├── jquery@3.2.1
  ├── jquery-match-height@0.7.2
  ├── moment@2.14.1
  ├── moment-timezone@0.4.1
  ├── patternfly-bootstrap-combobox@1.1.7
  └── patternfly-bootstrap-treeview@2.1.5
```

What versions do you have ?

**Comment by GodfatherThe** [comment]
From Docker container:
```
[root@4f64443771b8 Kiwi]# npm list
/Kiwi
└─┬ patternfly@3.30.0
  ├── bootstrap@3.3.7
  ├── bootstrap-datepicker@1.6.4
  ├── bootstrap-select@1.12.4
  ├── bootstrap-switch@3.3.4
  ├── bootstrap-touchspin@3.1.1
  ├── c3@0.4.18
  ├── d3@3.5.17
  ├── datatables.net@1.10.16
  ├── datatables.net-colreorder@1.3.3
  ├─┬ datatables.net-colreorder-bs@1.3.3
  │ └── datatables.net-bs@1.10.16
  ├── datatables.net-select@1.2.3
  ├── drmonty-datatables-colvis@1.1.2
  ├── eonasdan-bootstrap-datetimepicker@4.17.47
  ├── font-awesome@4.7.0
  ├── google-code-prettify@1.0.5
  ├── jquery@3.2.1
  ├── jquery-match-height@0.7.2
  ├── moment@2.14.1
  ├── moment-timezone@0.4.1
  ├── patternfly-bootstrap-combobox@1.1.7
  └── patternfly-bootstrap-treeview@2.1.5

```
