### ISSUE TITLE
Clone Test Run - Does not clone "Bugs and hyperlinks"

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#1207]
### Description of problem
Clone Test Run

### Version or commit hash (if applicable)
V7.1 (Docker)

### Steps to Reproduce

1. Add "Bugs and hyperlinks" to test case
2. Clone test run
3. Verify "Bugs and hyperlinks" from #1 show

### Actual results
"Bugs and hyperlinks" from #1 doesn't show

### Expected results
"Bugs and hyperlinks" from #1 show

### Additional info (Python traceback, logs, etc.)
_After Clone_:
![image](https://user-images.githubusercontent.com/9214815/68867110-fbd8bf80-06fd-11ea-90ca-9dbc76d465ea.png)

_Before Clone_:

**Comment by atodorov** [comment]
When you clone a TestRun it creates new TestExecution(s) for every TestCase that has been selected. The meaning is "these items need to be tested again". Most often than not the build will be modified as well.  Cloning TR is like a shortcut for quickly creating a new container with the same instructions to be tested. 

"Bugs & hyperlinks" in this context is something that is valid only for the current test execution so this is a WONTFIX.

There is some value in seeing bugs from previous test executions or even TE numbers which previously failed (e.g. something is still failing) and this is in our backlog after this page has been redesigned (currently WIP). Status matrix telemetry will also show similar functionality (still in TODO).
