### ISSUE TITLE
Feature request: Add Bugs In "New Test Case" Stage

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#1208]
There is no option connecting old open issues when adding "New Test Case" - There are bugs connected with all tests runs.
This feature is for users migrating from other TCMS into Kiwi.

**Comment by atodorov** [comment]
Bugs are related to test executions, not test cases so the notion of adding bugs to newly created test case does not apply in Kiwi TCMS.  If you are migrating old data then create a test run (can be only 1 for everything before the import) and attach bugs to a particular TE. It will be listed when you open the test case and it will also be shown under the Executions tree view indicating that was something from before the import.
