### ISSUE TITLE
Percent of finished executions not rounded in TestRun View

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#1230]
### Description of problem
the percent of finished test execution looks weird in some cases, e.g.
<img width="304" alt="Screen Shot 2019-11-27 at 18 10 42" src="https://user-images.githubusercontent.com/18421997/69740046-639cfa80-1141-11ea-9804-abf7b1513703.png">

### Steps to Reproduce

1. Create a Test Run with 14 Test Cases
2. Set 6 of the to IDLE (or any non-finished) and 8 to PASSED (or any finished status)

### Actual results
percentage is 56.99999999

### Expected results
percentage is rounded to the second digit, everything after that does not matter IMO
in this case this value is 57%

**Comment by asankov** [comment]
Update: when I refreshed the page it showed it as `57%`. if we are calculating that on the JS side, it's possible for the results to vary from time to time, because of the fuzzy way JS does math. still needs to be checked

**Comment by okainov** [comment]
+1б I've seen this one since forever

**Comment by atodorov** [comment]
> I've seen this one since forever

How about a pull request then ?

**Comment by RMadjev** [comment]
When the value is returned from the back end it is displayed with "{{ status_stats.CompletedPercentage|floatformat:0 }}", from the django docs floatformat:0  "round the float to the nearest integer". If we just use Math.round in the js it will do the trick.
