### ISSUE TITLE
Can't create test run with kiwi version 7.2

### ISSUE THREAD

**Issue by lxwcu** [kiwitcms/Kiwi#1259]
### Description of problem

After I seleceted test cases and tried to create test run, my explorer dispayed error 500

### Version or commit hash (if applicable)
Version 7.2

### Steps to Reproduce

1. Select 1 test case at test plan
2. Create test run  

### Actual results
![image](https://user-images.githubusercontent.com/43214555/70500750-414ea800-1b57-11ea-8d00-a10a95e32961.png)

**Comment by caleb15** [comment]
Same error with `kiwitcms/kiwi:latest` and `centos/mariadb` images.

**Comment by atodorov** [comment]
Either reproduce on public.tenant or post a Python traceback. Otherwise there's not thing we can do about it. 

FTR I tried creating a TR on public.tenant with only 1 TC and it worked fine: 
https://public.tenant.kiwitcms.org/runs/1547/

**Comment by lxwcu** [comment]
Thanks a lot. How can I get python traceback? Is there any logfile record this information?

**Comment by Almenon** [comment]
@lxwcu It's in the documentation - you have to set DEBUG to True.  Unfortunately I'm not sure exactly how to go about that off the top of my head. I tried adding it to the docker-compose file but that didn't work

**Comment by caleb15** [comment]
@lxwcu It's in the documentation - you have to set DEBUG to True. Unfortunately I'm not sure exactly how to go about that off the top of my head. I tried adding it to the docker-compose file but that didn't work

**Comment by atodorov** [comment]
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#troubleshooting
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#customization

**Comment by caleb15** [comment]
I tried setting DEBUG to true inside `tcms/settings/product.py` (other settings files already have it set to true) but that didn't work either.

> configure the DEBUG setting to True

@atodorov where exactly do I configure this, if you don't mind me asking?

**Comment by caleb15** [comment]
Uggg just realized I forgot the -it flag to `docker exec kiwi_web bash` so I wasn't inside the docker container. Once I specified it and went into the docker container I added `os.environ['DEBUG'] = True` to manage.py and restarted the container but that didn't help either :(

**Comment by atodorov** [comment]
@caleb15 - see the Customization section linked above. It explains how to change settings for the running container.

**Comment by atodorov** [comment]
No traceback or steps to reproduce.
