### ISSUE TITLE
How to import test cases from excel documents

### ISSUE THREAD

**Issue by lxwcu** [kiwitcms/Kiwi#1260]
I want to know how could I import test cases from excel documents, thanks.

**Comment by Prome88** [comment]
- https://stackoverflow.com/questions/58425742/can-we-write-test-cases-in-excel-and-upload-into-kiwi-tcms

- https://stackoverflow.com/questions/55798634/how-to-import-the-existing-test-cases-from-excel-file-to-kiwi-tool

**Comment by atodorov** [comment]
@lxwcu use StackOverflow for support questions as instructed on our website and the text template which appears when you open an issue.
