### ISSUE TITLE
Test run - Cannot change test case status on TC view without leaving a comment

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#1261]
### Version or commit hash (if applicable)
7.2 @ public tenant

### Steps to Reproduce

1. Create test run
2. Expand test case
3. Click on one of status buttons

### Actual results
A)
![image](https://user-images.githubusercontent.com/25688732/70508081-f3717a00-1b2d-11ea-92e2-4118d4081bb5.png)

B)  if users starts clicking on statuses the test run bar goes berserk untill the page is reloaded
![image](https://user-images.githubusercontent.com/25688732/70508222-4b0fe580-1b2e-11ea-903a-1c5ed907b3f2.png)

### Expected results
Comment should not be a mandatory field.

### Additional info (Python traceback, logs, etc.)
Changing the status via drop-down works but 99% of our users change the status via expanding the TC view.

**Comment by asankov** [comment]
this will be resolved when #1258 is merged
