### ISSUE TITLE
Passing arguments to httpd via apachectl is not longer supported

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#1274]
Subj.

Please update `httpd-foreground` to pass the options in a proper way

**Comment by okainov** [comment]
@atodorov seems like you've closed the wrong issue. In `master` `httpd-foregroud` still has `exec /usr/sbin/apachectl ${APACHE_PARAMETERS}` line which is exactly the subject of this issue.

**Comment by atodorov** [comment]
The referenced commit adds a test which exercises the functionality of specifying the 1 additional parameter which we support. If you mean something else then it wasn't clear from the original bug report.  Specify with more details.

**Comment by okainov** [comment]
Passing arguments to httpd via apachectl is not longer supported. How can it be more concrete?

```
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.
```

One should not pass arguments in the way they're passed now.
