### ISSUE TITLE
test plan search page ;cannot select "version" 

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1276]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
test plan search page ;cannot select "version" 

### Version or commit hash (if applicable)
7.2

### Steps to Reproduce

1.Search Test Plans/Select Product
2.Select Version

### Actual results
"Version" displays -----;cannot select "version" 

### Expected results
Version can be selected.

**Comment by atodorov** [comment]
`_select_tag.options` is undefined in utils.js, line 10
