### ISSUE TITLE
Add ESLint for better JS code

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#1281]
### Description of problem
Currently, we have no definition of good JS code and no guidelines on how to write one. 

Also, there is a lot of legacy JS which is in a really bad shape. 

Adding something like ESLint will allow us to:
1. have a tool that enforces writing good JS code
2. it will point out all the bad legacy code, which eventually must be refactored
3. define guidelines for writing JS and enforce them

good instructions on how this can be setup-ed can be found here:
https://eslint.org/docs/user-guide/getting-started

it is highly customizable, allows to exclude rules, and to write custom ones.

this should be part of the travis build and initially, it should be set to 'allow failure', because there will be many errors.

local run with default settings:
```
✖ 1506 problems (1506 errors, 0 warnings)
  34 errors and 0 warnings potentially fixable with the `--fix` option.`
```
mostly unused vars and false-positives `XXX is not defined` (false-positive because XXX is imported in the HTML)

maybe this should be fixed after #1262 , since this would solve the `import/export` problem and remove all the false positives for `XXX is not defined` (which come from HTML imports)

**Comment by Prome88** [comment]
What about integrating with SonarCloud?
Their JS linter gives this output: https://sonarcloud.io/project/issues?id=Prome88_Kiwi&languages=js&resolved=false
