### ISSUE TITLE
internationalization support

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#129]
@atodorov 

### Description of problem
 re-enable internationalization support and create 
documentation about adding translations

### Additional info
as discussed with Alexander Todorov on Nov, 15th

**Comment by atodorov** [comment]
@xbln I have created a translation project on Crowdin at:
https://crowdin.com/project/kiwitcms

ATM I'm waiting for their reply on whether or not they will grant free use for the project or we'll have to pay some monthly fees.

This is all quite new to me but the web interface should be easy to use. The nice thing is that Crowdin is able to automatically send pull requests back to GitHub when translations are ready!

Note: making use of the translations in the running app is still disabled but we'll fix it sometime soon.
Note2: I don't have a Translation HOWTO document but will create one if you don't beat me to it.

If you'd like you can give it a try and tell me what you think.

**Comment by atodorov** [comment]
QA note: we need a test similar to the docs test which will update the po files to make sure any current change (e.g. PR) is not modifying strings without regenerating the po files.

**Comment by xbln** [comment]
German translation has been completed, review is pending.

**Comment by atodorov** [comment]
@xbln thanks for the translations, I've gone ahead and approved all of them since I don't speak German. 

However I think the settings in Crowdin are wrong somehow. For German only files under de/LC_MESSAGES need to be translated and I get the same translations also for Chinese. Also after approval I don't see the automated pull request that Crowdin used to open against the project. 

I'm in the middle of some big refactoring around the XML-RPC API of the project but the transaltion stuff is on my todo list right afterwards.

**Comment by xbln** [comment]
Hi Alex,

thanks for the information. If you need help in translating / making any
buttons or other graphical stuff, pls give me a note.

Viele Grüße

Martin Esche
martin.esche@gmx.de
Mobil 0171 4103644

2017-12-27 22:15 GMT+01:00 Alexander Todorov <notifications@github.com>:

**Comment by xbln** [comment]
As there is some need for more translations (e. g. within HTML-templates) pls check if Babel could make life easier.

**Comment by atodorov** [comment]
@xbln basic translations should be working now. If they aren't please open a new issue for the problems you see.

Note: if there are strings within templates which are not marked as translatable they need to be enclosed inside the `{% trans %}` template tag. For more info refer to the Contribute section in the documentation.
