### ISSUE TITLE
filter function:Assignee @test run doesn't work

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1299]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
filter function:Assignee @test run doesn't work

### Version or commit hash (if applicable)
7.2

### Steps to Reproduce

1.Test Run/show filter options
2.Assignee/input Assignee key word

### Actual results

NO ANY Results
### Expected results

Search assignee should be Work
(Status,priority or tag is workable

**Comment by Prome88** [comment]
It works if you input user's email, but it does not work with username.

**Comment by atodorov** [comment]
Duplicate of https://github.com/kiwitcms/Kiwi/issues/332
