### ISSUE TITLE
Incorrect code formatting (tags pre)

### ISSUE THREAD

**Issue by AlexeiVokuev** [kiwitcms/Kiwi#1300]
### Version 
Kiwi TCMS 7.2.1 (23 Dec 2019)

### Steps to Reproduce

1. Add description to TestPlan or TestCase with multiline code, for ex
https://public.tenant.kiwitcms.org/case/7327/
2. Click "Save"

### Actual results
Unreadable formatting
tags "pre" displays as text

`(&lt;pre&gt; and &lt;/pre&gt;)`

### Expected results
tags "pre" correctly interpreted

**Comment by AlexeiVokuev** [comment]
![2020-01-09_1915](https://user-images.githubusercontent.com/24574039/72139914-8c4f1b80-33a0-11ea-8058-dec3c3da3a17.png)

**Comment by atodorov** [comment]
FTR the offending text is including the opening/closing 3 backticks (copy-paste this raw comment): 

```
   @Test
   @Feature("test")
   fun test(){
      /** When **/
      val test = justTest()
	  /** Then **/
	  TestCase.assertEquals("test != 1", 1, test)
   }
```

**Comment by AlexeiVokuev** [comment]
Yes, that's exactly what I did
The preview is displayed perfectly
The markup is broken that is in view mode after saving
![2020-03-01_2157](https://user-images.githubusercontent.com/24574039/75631931-25afe680-5c08-11ea-9071-5c1d6e14f90e.png)
![2020-03-01_2157_001](https://user-images.githubusercontent.com/24574039/75631932-26487d00-5c08-11ea-9245-37983f973d20.png)
