### ISSUE TITLE
Special edit for default groups

### ISSUE THREAD

**Issue by csonuryilmaz** [kiwitcms/Kiwi#1313]
### Description of problem

In Kiwi group names are editable. We've changed group name of "Tester" to "Test & QA" after installation which maps better for our team. 

While upgrading from v7.0 to v7.3 **bugs.0002_add_permissions** migration returns with *"_fake__.DoesNotExist: Group matching query does not exist."* *error* if Kiwi TCMS does not have any "Tester" group.

### Version or commit hash (if applicable)
7.3

### Steps to Reproduce

1. Run brand new docker image v7.0
2. Rename or remove "Tester" group.
3. Docker pull Kiwi latest image.
4. Run Kiwi latest image. (`docker-compose up -d`)
5. `docker exec -it kiwi_web /Kiwi/manage.py migrate` 

### Actual results

```bash
[root@sentry Kiwi]# docker exec -it kiwi_web /Kiwi/manage.py migrate
Operations to perform:
  Apply all migrations: admin, attachments, auth, bugs, contenttypes, core, django_comments, kiwi_auth, linkreference, management, sessions, sites, testcases, testplans, testruns
Running migrations:
  Applying bugs.0002_add_permissions...Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/venv/lib/python3.6/site-packages/tcms/bugs/migrations/0002_add_permissions.py", line 13, in forwards_add_perms
    tester = Group.objects.get(name='Tester')
  File "/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Group matching query does not exist.
```
### Expected results

```bash
[root@sentry Kiwi]# docker exec -it kiwi_web /Kiwi/manage.py migrate
Operations to perform:
  Apply all migrations: admin, attachments, auth, bugs, contenttypes, core, django_comments, kiwi_auth, linkreference, management, sessions, sites, testcases, testplans, testruns
Running migrations:
  Applying bugs.0002_add_permissions... OK
  Applying management.0006_remove_autofield_max_length... OK
  Applying testcases.0012_remove_autofield_max_length... OK
  Applying testruns.0007_test_execution_statuses... OK
```
I think **bugs.0002_add_permissions** migration should be optional or its implementation should consider the probability of not being "Tester" group. 

As a quick workaround, I added "Tester" group (without any permission, only for its name) and after migration I removed the group.

**Comment by atodorov** [comment]
> We've changed group name of "Tester" to "Test & QA" after 

`Tester` and `Admin` are special groups, do not change their names. 

As a workaround rename the group back to Tester and upgrade.

**Comment by atodorov** [comment]
> I think bugs.0002_add_permissions migration should be optional

Django takes migrations from the list of INSTALLED_APPS. If you don't want to use this app remove it from the list. There is no other way to ignore migrations.

> or its implementation should consider the probability of not being "Tester" group.

Whatever you've named your default user group it needs to have permissions for newly added objects in the system. This is true any time permission labels need to be refreshed. There is no  good way to figure out how granular you want the permissions to be. The only option I see is to make editing the above 2 special groups hard or impossible and if you want to configure your own groups then leave it to you to refresh permissions manually. 

For example it is entirely possible to have somebody being able to add products or test cases and nothing else, although it doesn't make much practical sense.

**Comment by csonuryilmaz** [comment]
> .. `Tester` and `Admin` are special groups, do not change their names.

👍 I won't touch default groups. For special purposes, I'll go on with brand new custom groups.
> .. Whatever you've named your default user group it needs to have permissions for newly added objects in the system.

I agree with that.

> .. The only option I see is to make editing the above 2 special groups hard or impossible ..

Yes. If imigrations and healthy version upgrades are dependent to special groups, Kiwi may warn user with message about the situation or may disallow editing special groups.

Thanks a lot for clarification.

**Comment by atodorov** [comment]
Reopening b/c the UI can do better in terms of indicating who can edit these groups and/or if you can edit them at all. We can disable editing of their names but allow editing of permissions.
