### ISSUE TITLE
Progress bar on test runs showing 0%

### ISSUE THREAD

**Issue by dkotschessa** [kiwitcms/Kiwi#1326]
### Description of problem

When running test cases as part of a test run, the progress bar does not update and stays at 0%

### Version or commit hash (if applicable)

Version 7.3

### Steps to Reproduce

1. Create a test run from existing test cases/test plan
2. Run all or part of test plan by using play/pass/block/failed
3. Check progress report at top

### Actual results

![image](https://user-images.githubusercontent.com/7572608/73186994-ac940f80-40ee-11ea-941e-7464f7b91902.png)

### Expected results

Expect to see progress bar with pass/fail/etc. 

### Additional info (Python traceback, logs, etc.)

Let me know what logs might be useful and easiest to get - I do not have access to the server where it is deployed, but I can ask.

This issue was brought up on stackoverflow and Twitter and acknowledged a possible defect.
https://twitter.com/dkotschessa/status/1220797684551995392

**Comment by dkotschessa** [comment]
Thank you for looking into this!

**Comment by asankov** [comment]
@dkotschessa Thank you for reporting this! After #1331 is merged this should all be working as expected in both english and other languages.
