### ISSUE TITLE
Add hyperlink fails silently when Name exceeds 64 characters

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1327]
### Description of problem
When attempting to attach a hyperlink to a test execution, if the name field has more than 64 characters, the link is not created and no error is given.

### Version or commit hash (if applicable)
7.3

### Steps to Reproduce

1. Open a Test Execution
2. Click on the Add link next to the label "Bugs and hyperlinks".
3. In the URL field, enter a valid URL.
4. In the Name field, enter a string that is longer than 64 characters, for example: "This description is 65 characters long. It won't work correctly!!"
5. Click on the OK button.

### Actual results
The dialog closes. No new link is shown on the Test Execution page. No new link is shown in the linkreference_linkreference table.

### Expected results
New link is shown on the Test Execution page and in the linkreference_linkreference table.
Long name string is truncated to 64 characters.
User is warned when name field is truncated.

Alternative expected results:
Error is displayed, warning user about 64-character limit for the Name field.

### Additional info (Python traceback, logs, etc.)
The linkreference_linkreference.name field has a limit of 64 characters:

MariaDB [kiwi]> desc linkreference_linkreference;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| id           | int(11)      | NO   | PRI | NULL    | auto_increment |
| execution_id | int(11)      | NO   | MUL | NULL    |                |
| name         | varchar(64)  | NO   |     | NULL    |                |
| url          | varchar(200) | NO   | MUL | NULL    |                |
| created_on   | datetime(6)  | NO   | MUL | NULL    |                |
| is_defect    | tinyint(1)   | NO   | MUL | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+

However, inserting a record with a longer name field succeeds, with the name field truncated to 64 characters.

I haven't experimented with longer URLs.

**Comment by atodorov** [comment]
workaround: do not add names for link or truncate them.

**Comment by atodorov** [comment]
WIP in https://github.com/kiwitcms/Kiwi/issues/1327

**Comment by atodorov** [comment]
Fixed on FE and BE already. Closing.
