### ISSUE TITLE
Report bug to Jira fails when test case is too long

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1333]
### Description of problem
When a TC has a large amount of text, reporting a bug to Jira fails with status 400.

### Version or commit hash (if applicable)
7.3

### Steps to Reproduce

1. Create a TR of a TC whose text content is about 3.5k in size (3459 bytes, in my case)
2. Execute Report bug -> JIRA -> Report

### Actual results
Status 400 - Bad Request

Jira displays the following error message:

> HTTP Status 400 – Bad Request
> Type Exception Report
> 
> Message Request header is too large
> 
> Description The server cannot or will not process the request due to something that is perceived > to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive > request routing).

### Expected results
JIRA opens Create issue dialog with data from TR

### Additional info (Python traceback, logs, etc.)
* Using Jira Cloud.

* The request itself is 5028 bytes in length.

* Reporting a bug for a TC with a slightly smaller text portion (2478 bytes) succeeds.

Comments on [this Jira ticket](https://jira.atlassian.com/browse/JSWSERVER-20190?error=login_required&error_description=Login+required&state=5987ae8b-5113-4e54-9b30-a15866bd26cc) recommend setting a limit to the header size of requests to work around Jira's limitation. But I don't think that's a ticket against Jira cloud, so it may not be relevant.

**Comment by atodorov** [comment]
This appears to be related to 
https://stackoverflow.com/questions/60049591/kiwi-reporting-to-jira-issue/60053097#60053097

where we have at least 1 bug on the FE layer, not handling the failure well and not informing the user what is going on. 

Then there's the BE interaction between Kiwi TCMS and JIRA which is a separate story.

**Comment by atodorov** [comment]
@ronfeldman do you have any idea what is the maximum request size/text size your Jira instance is configured to receive via an API call ?

Is this something you can configure yourself or is it a hard limitation for all JIRA installations ?

**Comment by ronfeldman** [comment]
@atodorov This took a little digging and is still a guess, but I think they are using Tomcat and from [their docs](https://tomcat.apache.org/tomcat-5.5-doc/config/http.html) it looks like the default max header size is 4k. (maxHttpHeaderSize about halfway down the page).

We are using JIRA Cloud. I'll check with our IT to find out if this is something we can ask them to increase. I'm in favor of being mindful of the length of the text of a TC and putting in the practice of breaking down complex TCs into smaller ones if possible. My main concern with Kiwi in this situation is the error handling. But JIRA is certainly making it clear to the user that their operation has failed, so I don't consider this a high priority Kiwi issue for us.
