### ISSUE TITLE
Feature: Adding Custom Fields for Test Plan and Test Case

### ISSUE THREAD

**Issue by edoswaldgo** [kiwitcms/Kiwi#1368]
Good day,

I would like to request for the feature of adding custom fields to test plans and cases for advanced filtering. May I know if this feature is viable to be added to Kiwi TCMS?

Thank you very much!

**Comment by atodorov** [comment]
Essentially duplicate of #156

**Comment by edoswaldgo** [comment]
Thanks for the clarification, @atodorov !
