### ISSUE TITLE
v8.0 database migration problem with test runs

### ISSUE THREAD

**Issue by QuentinKp** [kiwitcms/Kiwi#1388]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
I just migrated from v7.1 on a server A to v8.0 on a server B (I virtualized our application server).

I use a pgsql container for the db.

For the migration I used the [backup-restore method](https://kiwitcms.org/blog/atodorov/2018/07/30/how-to-backup-docker-volumes-for-kiwi-tcms/).

1. The db volume on server B is brand new and I created the schema using `/Kiwi/manage.py migrate`
2. Then I restored the .json. But I ran into schema problem because of the changes in v8.0 of the changes of the primary key. I just replaced in the json file the old names by the new one and the restoration passed.

3. The application runs fine except that I have now a problem with test runs when I go to the "search for test runs" page:

> DataTables warning: table id=resultsTable - Requested unknown parameter 'run_id' for row 0, column 0. For more information about this error, please see http://datatables.net/tn/4

I am not sure if I made any mistake during the migration or  if there is actually a bug in the migration process.

For info: I tried on my test container in v7.3 to migrate the database in v8.0. Everything went fine but I had the same problem at the end.

### Version or commit hash (if applicable)
8.0

**Comment by atodorov** [comment]
Do not use GitHub Issues for support requests and general questions, use StackOverflow as instructed in the template text of this issue and on https://kiwitcms.org/support/

**Comment by oscar-giggity** [comment]
Isn't this a bug? I'm affected in the same way (apart from me using MariaDB).

**Comment by gizzmojr** [comment]
A 7.3 backup cannot be restored to docker image, b7513e199d8c, so I've been testing. Prune was done on the hosting system, so the previous image is not an option to switch too in my case. A DB backup, without some way of going back to retry the migration, we're in limbo. Anyone have the SHA info by chance, @atodorov? Maybe we can still pull it from dockerhub calling the SHA in the pull.

Like @oscar-giggity , mariaDB is what we use as well and having the exact same symptoms.

**Comment by QuentinKp** [comment]
FYI I created a subject on this problem on stackoverflow [following this link](https://stackoverflow.com/questions/60295040/kiwi-tcms-v8-0-database-migration-problem-with-test-runs).
