### ISSUE TITLE
test case search result each page only display 20 items is not enough

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1396]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
test case search result each page only display 20 items is not enough

### Version or commit hash (if applicable)
7.3

### Steps to Reproduce

1.serach test cases
2.see test case serach result

### Actual results

test case search result each page only display 20 items is not enough

### Expected results
Per page: 100, 150, 200

**Comment by atodorov** [comment]
Duplicate of https://github.com/kiwitcms/Kiwi/issues/1210
