### ISSUE TITLE
report of test case run "Closed at" is None

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1403]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
report of test case run "Closed at" is None

### Version or commit hash (if applicable)
8.0

### Steps to Reproduce

1.run test case
2.click" report"
3.check "closed at"

### Actual results
is None

### Expected results
display correct time

**Comment by atodorov** [comment]
Handled in https://github.com/kiwitcms/Kiwi/pull/1391 via redesign.
