### ISSUE TITLE
"select all cases/select none case" function doesn't work

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1404]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
"select all cases/select none case" function doesn't work

### Version or commit hash (if applicable)
8.0

### Steps to Reproduce

1.Test executions
2.click function "select all cases/select none case" 

### Actual results
 doesn't work

### Expected results
should be OK

**Comment by Prome88** [comment]
- Works on v7.0
- On 8.0.1EE it does not work on Test run page, but it works on Test plan page
