### ISSUE TITLE
cannot  using "test id"search test case

### ISSUE THREAD

**Issue by imhanachang** [kiwitcms/Kiwi#1408]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

cannot search test case via "test id"
### Version or commit hash (if applicable)
8.0

### Steps to Reproduce

1.search/test case 

### Actual results
cannot  using "test id"search test case

### Expected results
 using "test id"search test case
this function is  useful for QA

**Comment by atodorov** [comment]
> cannot search test case via "test id"

If you have the case ID then you can just open it via /case/xyz/. Why do you need to search by unique identifier which you already know and will return only 1 result ?

**Comment by atodorov** [comment]
No more information provided so closing as invalid. If you have the case ID then just open it via /case/xyz/ URL.
