### ISSUE TITLE
404 on the "Users and groups" page

### ISSUE THREAD

**Issue by Artem1702** [kiwitcms/Kiwi#1445]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
404 Page Not Found on the "Users and groups" page

### Steps to Reproduce

1. Click ADMINS section in the menu on homepage
2. Click Users and groups->FAIL

### Actual results
404 Page Not Found on the "Users and groups" page

### Expected results
"Users and groups" page is displayed

**Comment by atodorov** [comment]
On public tenant you are not allowed to access this page due to obvious reasons. Only superusers are allowed to do so.

**Comment by asankov** [comment]
maybe we should hide the menu/button for users who don't have permissions to go there. why see the menu when you can't access it?
