### ISSUE TITLE
py.test reporting plugin

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1511]
Kiwi TCMS needs a customized test runner for py.test based projects. This runner will execute the py.test test suite as normal and then report the results into Kiwi TCMS database via our API.

**Getting started docs**
- https://kiwitcms.readthedocs.io/en/latest/plugins/automation-frameworks.html
- https://kiwitcms.readthedocs.io/en/latest/contribution.html
- http://kiwitcms.org/blog/atodorov/2018/11/05/test-runner-plugin-specification/
- https://docs.pytest.org/en/latest/writing_plugins.html

For inspiration see https://github.com/kiwitcms/tap-plugin and https://github.com/kiwitcms/junit.xml-plugin

**Definition of done**
- We already have a skeleton repository at https://github.com/kiwitcms/pytest-plugin - pull request(s) must be sent towards that repository
- py.test information is read and fed to  an instance of `tcms_api.plugin_helpers.Backend` which encapsulates the communication and behavior logic around the TCMS DB, see referenced plugins above
- README.rst contains information about installation & configuration (see plugin references above)
- repository contains tests which are executed by py.test and will serve as dog fooding
- code review & issues reported from Kiwi TCMS maintainers have been resolved

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Comment by cmbahadir** [comment]
Ooops, wrong linked PR.

**Comment by leoGalani** [comment]
If nobody is doing this, I'll give a try.
