### ISSUE TITLE
IDEA: Use EtherPad as collaborative text editor aka test writing in pairs

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1528]
Writing a TestPlan and/or a TestCase could be a collective effort and there is a use-case for test engineers working in pairs when creating these documents. Could be a more experienced + less experienced tester working together, or a small team hacking up a TP (brainstorming in writing). 

That's definitely something I've done in the past and can be useful. :+1: or :-1: !

Without detailed research it's hard to say how much work this is. The most straight forward method is to provide a pop-out editor like Etherpad which will load the initial text, allow people to modify it and then have a mechanism to push the new text back to the database. Kiwi TCMS and EtherPad could be 2 separate app instances, living in the same docker image which are configured to talk together initially. It is possible that others editors also exist and are easier to integrate.

**Comment by zahari** [comment]
Good idea. There are variants of EtherPad that are available to host
yourself.

**Comment by atodorov** [comment]
Closing due to lack of traction
