### ISSUE TITLE
Add buttons for creating tables in text editor - SimpleMDE

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1531]
The text editor that we use is called SimpleMDE.

Kiwi TCMS needs a way to insert tables in the document for users who are not familiar with the markdown syntax. 

SimpleMDE has the ability to define custom buttons so something like the following will do the trick:

**Definition of Done**:
1. A button to insert a table, say 3x3
2. A button to insert a new row, below the currently selected one
3. A button to delete the current row
4. A button to insert a column, to the right of the currently selected one
5. A button to delete the current column

For more info see the **insertTexts** and **Custom Button** examples at:
https://github.com/sparksuite/simplemde-markdown-editor

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Comment by brymut** [comment]
I think SimpleMDE already comes with a [table button](https://github.com/sparksuite/simplemde-markdown-editor/blob/6abda7ab68cc20f4aca870eb243747951b90ab04/src/js/simplemde.js#L1180), its just not a default option. I'll try it out and see what it does

**Comment by atodorov** [comment]
> As for this, would selected mean that a row would be highlighted or the cursor is in anywhere in the row?

Use cursor position

**Comment by brymut** [comment]
I've had a closer look at the simplemde and the API provided and it looks like it would be complicated to implement the appropriate parsing, validation and insertion of the appropriate Markdown text to add new columns & rows in place without breaking the user's markdown formatting.

**Comment by atodorov** [comment]
Closing this issue b/c implementing the missing table rows/columns functionality should be something that goes inside the text editor itself and we're not getting any user feedback on this issue. 

@brymut since you've implemented the button for adding a table markup feel free to claim the bounty attached to this issue.

**Comment by brymut** [comment]
Thank you @atodorov, submitted new expense at https://opencollective.com/kiwitcms/expenses/29854
