### ISSUE TITLE
Report bug to Jira fails :&amp; instead of in the URL

### ISSUE THREAD

**Issue by Ramslim** [kiwitcms/Kiwi#1533]
When i click on Report bug, the generated URL contain "& amp ;" instead of &.
The Report isn't created in JIRA.
If i manually replace "& amp ;" by & in the URL, everything works fine.

Steps to Reproduce:
Execute Report bug -> JIRA -> Report

**Comment by atodorov** [comment]
Note: this is probably due to the fact that JSON-RPC now unconditionally HTML-escapes all strings. FE should probably unescape before handling the URL.
