### ISSUE TITLE
Projects feature

### ISSUE THREAD

**Issue by ferranpujolcamins** [kiwitcms/Kiwi#154]
What's holding us back to implement Kiwi in our company is that one instance only serves one project. If we have two different teams working in two different projects we need to run two instances of Kiwi. This is not scalable.

I'd love Kiwi to let us create projects, assign users to projects, and let the Kiwi admin features be configurable project-wise.

**Comment by atodorov** [comment]
Hi @ferranpujolcamins,
I'm not sure I am understanding your use case very well. You can create Products inside Kiwi TCMS. Each product has versions and even builds, e.g. version 3.2, build 3.2-beta1, etc.

TestPlans are attached to products and test runs (aka executions) are attached to Test Plans (hence products), versions and builds. Then all of this can be used for filtering and reporting. 

From our demo site you can see that there are many test plans for different products,
[link here](https://demo.kiwitcms.org/plans/?action=search&name__icontains=&author__email__startswith=&owner__username__startswith=&type=&tag__name__in=&case__default_tester__username__startswith=&is_active=on&product=&product_version=&env_group=&create_date__gte=&create_date__lte=).


If this isn't working for you can you tell me how do you imagine you can structure the work within your teams ?

**Comment by ferranpujolcamins** [comment]
Hi Alexander, thanks for answering.

I would like a new kind of entity (which I'll call project from now on)
that has a collection of products inside and can configure Kiwi
independently.

The reason for that is that different teams in the company may have
different testing workflows and might want to work with a different testing
model. Thus I would like each team to configure Kiwi as they like (each
team might want different classifications, priorities or products) without
modifying what the other team sees.

Think of having two isolated instances of Kiwi, one for each team. If you
do this manually you need to setup a new instance of Kiwi each time you
start a new project. If Kiwi supported this, with just a few clicks you
could have a new project with custom settings isolated from the other ones.

Atlassian Jira is somehow like this: you can configure issue types and
workflows on a per project basis.

On 18 Dec 2017 7:30 p.m., "Alexander Todorov" <notifications@github.com>
wrote:

Hi @ferranpujolcamins <https://github.com/ferranpujolcamins>,
I'm not sure I am understanding your use case very well. You can create
Products inside Kiwi TCMS. Each product has versions and even builds, e.g.
version 3.2, build 3.2-beta1, etc.

TestPlans are attached to products and test runs (aka executions) are
attached to Test Plans (hence products), versions and builds. Then all of
this can be used for filtering and reporting.

From our demo site you can see that there are many test plans for different
products,
link here
<https://demo.kiwitcms.org/plans/?action=search&name__icontains=&author__email__startswith=&owner__username__startswith=&type=&tag__name__in=&case__default_tester__username__startswith=&is_active=on&product=&product_version=&env_group=&create_date__gte=&create_date__lte=>
.

If this isn't working for you can you tell me how do you imagine you can
structure the work within your teams ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kiwitcms/Kiwi/issues/154#issuecomment-352517185>, or mute
the thread

**Comment by atodorov** [comment]
OK, I think I understand the basic concept now.

> each team might want different classifications, priorities or products

What models are we talking about? Can you give me a list of all the things that you'd like to be able to configure per project ?

We can definitely make classifications, priorities, etc to have a foreign key relationship with the Product (or a product called "Project X", I need to explore this a bit) and that would probably more easier than having to make everything configurable per team basis. 

OTOH Kiwi ships inside a Docker container together with its DB layer so spawning several instances should be relatively easy as a workaround for the moment.

**Comment by ferranpujolcamins** [comment]
I can think of Test case run status, Test plan types, Test case status, Test case categories, Priorities and Classifications.

I'm not sure if attaching this to product is the best way to go. Maybe a project has several products.
And in the future you will probably want to set permissions to user only for specific projects.

But, for sure this is a long-term vision. But from my point of view the first baby-step is to add "projects" that can contain products. User permissions and per-project configuration can come later.

What do you think?

**Comment by atodorov** [comment]
For the record, I think a multi-tenant architecture will resolve this issue.

For complete isolation you can use the existing docker images, which is described in:
http://books.agiliq.com/projects/django-multi-tenant/en/latest/isolated-dockers.html

For partial isolation (i.e. at the application level) with some shared objects (like user accounts) you can take a look at:
https://django-tenant-schemas.readthedocs.io/en/latest/ or https://github.com/tomturner/django-tenants/

I have experimented with both (mostly with django-tenant-schemas) and they seem to work. However both also have issues and appear to not be maintained very actively. As of last time I checked they didn't support the latest version of Django that Kiwi TCMS is using.

That said I am not going to integrate these apps with Kiwi TCMS and declare official support for them. We're going to continue experimenting with tenant schemas and may even release a package that makes the integration with Kiwi TCMS easier but that would be mostly for our own use.

Official statement is to use Docker because it gives you full isolation and is less prone to issues compared to the exiting alternatives. Closing this issue.
