### ISSUE TITLE
Rename / disable Environment Properties fails

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#167]
### Description of problem
Click on "rename" on last item in list loads "New property name"-box with "null", changes will not be accepted ("ID is required"). Disabling fails.
Workaround: Page refresh

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
3.49ee

### How often reproducible
allways

![image](https://user-images.githubusercontent.com/27554937/34491864-767903f8-efe5-11e7-9a35-9841a633868f.png)

**Comment by atodorov** [comment]
Do you have any values assigned to this property before Trying to rename to 'null' ?

I was able to successfully rename another property on the demo site. Then I added a new property with name 'Notebook Display 1366*744', without any values and then tried to rename it. Only then I got the error which makes me think the '*' in the name could be to blame.

If you can get an exact reproducer that would be very helpful
