### ISSUE TITLE
Add option to show only IDs in Status Matrix

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1682]
**Problem**
It is difficult to get a sense of the overall state of testing when one cannot view the latest Test Execution for all Test Cases at the same time.

**Solution**
Allow the user to display only the ID of the Test Cases and Test Runs, similar to how the current version displays only the ID of each Test Execution. This will make the columns more narrow and more will fit on the screen at once.

Vertical scrolling will probably always be necessary when the number of Test Cases exceeds a certain amount, but it is not hard to maintain the overall view when scrolling vertically.

**Alternative Solutions**
Alternatives which would achieve similar results:

- Option to sort Test Executions in reverse chronological order, so the most recent items are listed first.
- Freeze the TC column.
- Freeze the TR row.

I'd really like to see all of these implemented as options (ID only, sort, column and row freeze). I understand that the column/row freeze may require frames, which don't generally make people happy (myself included). But that might be acceptable if the view is more effective.

**Comment by atodorov** [comment]
> Allow the user to display only the ID of the Test Cases and Test Runs, similar to how the current version displays only the ID of each Test Execution. This will make the columns more narrow and more will fit on the screen at once.

For the TR portion please see:
https://public.tenant.kiwitcms.org/telemetry/testing/status-matrix/

The TR column headers have been updated in v8.3. 

Not sure if you would still need anything done for the TC rows.

> Vertical scrolling will probably always be necessary when the number of Test Cases exceeds a certain amount, but it is not hard to maintain the overall view when scrolling vertically.

That's been on our backlog for some time but there are nuances here. ATM there is a vertical scroll bar on the right of the page, but the horizontal scroll is at the bottom, hardly visible.

Current design idea is to force the table to render within the remaining width/height of the page (so everything fits on the screen) and that would in turn force the scroll bars to appear right/bottom of the page and be more easily accessible.

**Comment by atodorov** [comment]
> It is difficult to get a sense of the overall state of testing

Doesn't Execution trends work better for you ? What exactly do you call an "overall state" ?

Regardless of how UI and scrollbars are updated on the Status Matrix page there isn't enough real estate to fit everything on the screen if you do not filter down the information which should be displayed.

**Comment by ronfeldman** [comment]
Yes, thanks Execution trends is very useful for getting the view of the overall state.

**Comment by ronfeldman** [comment]
The updated TR view is a helpful improvement of the usability of the Status matrix, yes.

In working with the Status matrix to decide what work needs to be picked up for re-testing, I still think that displaying the columns in reverse chronological order (ie show the most recent TR would be more efficient. So I'd re-phrase my original request as

**Problem** As a tester, I want to use the Status matrix to find the Test Cases which need to be re-tested, but I have to scroll to the right to find them and they are not lined up for easy discovery"

**Solution** to be "List TRs in reverse chronological order".
