### ISSUE TITLE
centos/mariadb-103-centos7 doesn't support MYSQL_CHARSET & MYSQL_COLLATION

### ISSUE THREAD

**Issue by zhuangyy** [kiwitcms/Kiwi#1700]
input Chinese in any testcase/testplan fields will cause 500 error while English input works fine. but this issue can not be reproduced at https://public.tenant.kiwitcms.org. so I guess it must be related to some wired configuration.

the kiwi tcms instance I am running is installed by docker, I changed nothing besides followed some initialization operations listed on https://kiwitcms.readthedocs.io/.
 
but seaching "kiwi tcms trouble shooting" by google results nothing useful, I can not even get the information about where those error logs (if they do exist) are located. 

any hints will be appreciated. thanks very much.

**Comment by zhuangyy** [comment]
it turns out that the default charset of database kiwi and all its tables is latin1, is there a bug in db init code?

**Comment by atodorov** [comment]
> it turns out that the default charset of database kiwi and all its tables is latin1, is there a bug in db init code?

Nope, this is how MariaDB works by default.

We don't explicitly mention this in the docs but we do say to copy our own `docker-compose.yml`:
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#start-docker-compose

which is configured to use `utf8mb4_unicode_ci` to support non-latin script & emojis.

**Comment by zhuangyy** [comment]
that docker-compose.yml (contains MYSQL_CHARSET: utf8mb4 kinda stuff) is exactly what I used.

**Comment by atodorov** [comment]
Reopening issue. It looks like the problem is with the underlying MariaDB container. Version 5.5 which we used before supported the `MYSQL_CHARSET` and `MYSQL_COLLATION` variables while the newest 10.x versions don't support these so your settings don't come into effect.

I will investigate this upstream and link back to this issue.

**Comment by atodorov** [comment]
Here's the upstream reference, hopefully they accept this patch:
https://github.com/sclorg/mariadb-container/pull/125
