### ISSUE TITLE
Test Case IDs are listed as "undefined" on Test Case health page

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1711]
### Steps to Reproduce

1. Go to Telemetry -> Test Case Health

### Actual results
Display and links to Test Case ID have the value "TC-undefined" instead of the actual TC ID
Example link:
https://<internal host>/case/undefined

### Expected results
The correct TC ID, for example:
https://qaportal01.irvl.mymbnet.com/case/177/

Screenshot attached.
![tc-undefined](https://user-images.githubusercontent.com/6746868/83172042-d9bbf300-a0cb-11ea-946f-924eb1b01f5f.jpg)

**Comment by atodorov** [comment]
Fixed in v8.1, see 8.1 changelog, section Bug fixes at the bottom
https://kiwitcms.readthedocs.io/en/latest/changelog.html#kiwi-tcms-8-1-04-mar-2020

```
Fix a TC-undefined displayed in TestCase health telemetry
```
