### ISSUE TITLE
wrong link on https://kiwitcms.org/ - Kiwi TCMS plugins

### ISSUE THREAD

**Issue by jhutar** [kiwitcms/Kiwi#1726]
Hello. This is most probably a wrong place where to report a bug about kiwitcms.org website, but first I could find :-)

> Test runner plugins
> Use Kiwi TCMS plugins for TAP, JUnit...

Link there leads to https://kiwitcms.readthedocs.io/en/latest/plugins.html which gives 404 for me.

**Comment by atodorov** [comment]
https://github.com/kiwitcms/kiwitcms.github.io/ is for bugs against the website. Already fixed.
