### ISSUE TITLE
Add test case: Estimated time is mandatory but accepts no inputs

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#174]
### Description of problem
Add test case fails because Estimated time field requires input in the form DDHHMM but accepts digits only; digits are refused.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
3.49-ee (untouched Mr. Senko docker image on digitalocean ubuntu 17.09)

### How often reproducible
permanent

![bugx1](https://user-images.githubusercontent.com/27554937/34915687-d2a1176c-f92a-11e7-8181-816f03aee220.png)

**Comment by atodorov** [comment]
Thanks for the bug report. Please use the form at /cases/new/ instead of the admin interface.

Note: I will fix this by redirecting the Add button from admin to the same URL. Users should be entering objects via the Admin interface unless strictly required.
