### ISSUE TITLE
Create Test Case: Error 500 when saving (Link on Crash report attached)

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#175]
### Description of problem
Error 500 when hitting the save button on Create Test Case Form

### Component (web, API, etc)
New Kiwi (Docker) installation 

### Version or commit hash (if applicable)
3.49-ee (untouched Mr. Senko docker image on digitalocean ubuntu 17.09)

### How often reproducible
permanent

### Steps to Reproduce

1. Admin -> Test Case Status: Change some of them (I also used German äöü)
2. Make Test plan and open it
3. Case -> Write new case: open Test case form
4. Fill Summary field
5. Hit save button

I setup a complete new Installation and **did not** change Test Case Status: Everything was fine!

### Actual results
Error 500

Request Method: | POST
-- | --
https://207.154.198.232/cases/new/?from_plan=1
2.0.1
IntegrityError
(1048, "Column 'case_status_id' cannot be null")
/venv/lib64/python3.5/site-packages/django/db/backends/mysql/base.py in execute, line 76
/venv/bin/python3
3.5.1
['/venv/lib64/python3.5/site-packages',  '/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages',  '/venv/lib64/python35.zip',  '/venv/lib64/python3.5',  '/venv/lib64/python3.5/plat-linux',  '/venv/lib64/python3.5/lib-dynload',  '/opt/rh/rh-python35/root/usr/lib64/python3.5',  '/opt/rh/rh-python35/root/usr/lib/python3.5',  '/venv/lib/python3.5/site-packages',  '/venv/lib64/python3.5/site-packages/tcms/core/lib',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf',  '/venv/lib64/python3.5/site-packages/odf']
Sun, 14 Jan 2018 18:58:41 +0000

[Crash Report](https://drive.google.com/open?id=1xPRBNt6Plkv7PsV6kTE7WXP0ZpQfGq36)

**Comment by atodorov** [comment]
Thanks for this bug report. For now please don't change TestCaseStatus names. I know they are accessible via the admin interface but there are a lot of places where Kiwi does SQL queries based on names. 

Also I think adding new statuses with the names in German will not work as you expect because Kiwi has no special knowledge of these statuses. I need to think about how to fix this before doing anything about it.

**Comment by xbln** [comment]
I suggest to create an additional "display" column where translated names could be placed.

**Comment by xbln** [comment]
Is it the same with test_case_run_status ?
What about test_plan_types ? Are they editable?

**Comment by atodorov** [comment]
Yes, TestPlanTypes should be editable!. I'm closing this issue, RFE in #182. I will examine a small django app that seems to be doing what we need and integrate it with Kiwi if all looks good.
