### ISSUE TITLE
All bulk changes result in endless "loading" loops 

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#177]
### Description of problem
When applying a test-plan bulk change (e. g. status, default tester, category, ...) the system stays in a "loading" loop.  

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
3.49-ee demo site

### How often reproducible
permanent

### Steps to Reproduce

1. Make a test plan with some test cases
2. Apply a bulk change (e. g. bulk change status)

### Actual results
loop (but changes were made in the background), no return

### Expected results
changes to any of the test cases

![bugz1](https://user-images.githubusercontent.com/27554937/34965182-79bc18c6-fa52-11e7-82e5-b4b21e0e7a1f.png)

**Comment by atodorov** [comment]
I get an update failed pop-up, not the loading image. Please don't remove or edit this test plan and its test cases before I can figure out what's wrong with it.

**Comment by xbln** [comment]
I get the same result (loading...) with any testplan on my own kiwi installation.

**Comment by atodorov** [comment]
@xbln can you find a traceback for this problem on your installation? 

Check if the DEFAULT_PAGE_SIZE setting is an integer number, not a string. 

I am able to reproduce is some odd cases and the problem is that page size coming from the filter options is a string, which breaks Kiwi.

**Comment by xbln** [comment]
Glad to hear you fixed it! I checked that error on the demo site again and I could produce the error with any set of test cases.
