### ISSUE TITLE
new linter: warn about missing backwards migrations in RunPython + patches

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1774]
`migrations.RunPython()` is used to manipulate the DB in an arbitrary way. Usually adding initial data and sometimes renaming fields, etc.

In several places we have a Python migration which doesn't have its backwards/reverse counterpart. This means these migrations cannot be rolled back.

A new linter is needed which will be executed against the migration files (pylint-django excludes migrations by default) and warn about this situation.

**Definition of Done**:
- new checker class under https://github.com/PyCQA/pylint-django
- If the linter sees a RunPython migration without its reverse part then warn
^^^ this will be developed in the pylint-django repository, also see https://github.com/PyCQA/pylint-django/blob/master/pylint_django/checkers/db_performance.py for hints. Assign `@atodorov` for code review.

- Then after a new pylint-django version has been released the new checker should be enabled against Kiwi TCMS migrations and all warnings from it should be fixed
- All code review passed & PR merged

Here's me explaining how to write pylint plugins:
- https://www.youtube.com/watch?v=3CkSKUNMLJc
- https://www.youtube.com/watch?v=D1wLFyazTRM
- checkout `node_is_subclass` from pylint-django (which we use anyway) https://github.com/PyCQA/pylint-django/blob/master/pylint_django/utils.py - may help.

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Note:** this is a 70 EUR bounty issue.

**Comment by atodorov** [comment]
@brymut want to take care of this in parallel with #1752 ?

**Comment by atodorov** [comment]
@brymut pylint-django v2.1.0 contains your new checker so you can deal with the rest of this issue.

**Comment by atodorov** [comment]
@brymut for the remaining errors about missing backwards migrations follow these guidelines:

1) If it is a newly added field where we have data migration to supply default values the reverse operation will be to remove the entire field. So we don't need a reverse function to remove the values first, it can be an empty function to satisfy the linter.

2) If we are removing fields (possibly using data migration to transform the values to other fields before removal) the reverse operation is to add the removed fields. However it may not be possible to restore the values. This for example happens for BugSystem model then the reg_ex field is removed.  I suggest storing the values in a file under /tmp. Try `object.serialize()` to see if it will work.

3) Both 1) and 2) should help satisfy the tests in #1797 - you can rebase on top of that branch to see if your changes are helping the tests progress further.

**Comment by brymut** [comment]
@atodorov submitted new expense on https://opencollective.com/kiwitcms/expenses/23852
