### ISSUE TITLE
Status Matrix content gets out of sync

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1801]
### Description of problem
Filtered Status Matrix content is loaded, the content is replaced by an unfiltered list of all Status Matrix content.

### Version or commit hash (if applicable)
8.3
Also tested with Demo site (8.5-Enterprise)

### Steps to Reproduce

1. Open Status Matrix
2. Select a Product (on Demo site, select Kiwi TCMS)

### Actual results
1. Expected (filtered) content is displayed
2. After a few seconds, this content is replaced with Status Matrix data for all Products.

### Expected results
Only filtered content is displayed (on Demo site, this was 3 Test Cases and 4 Test Runs)

### Additional info (Python traceback, logs, etc.)
It seems that this sequence of events is taking place:

1. Initial, unfiltered query (query 1) is automatically executed when page is opened
2. New query (query 2) is executed when filters are selected
3. Query 2 results are returned and displayed
4. Query 1 results are returned and displayed, replacing Query 2 results

**Comment by atodorov** [comment]
```
Query 2 results are returned and displayed
Query 1 results are returned and displayed, replacing Query 2 results
```

Thanks for the analysis. This is spot on.
