### ISSUE TITLE
Test Cases cannot be rearranged from within a Test Run

### ISSUE THREAD

**Issue by mlongmiresqa** [kiwitcms/Kiwi#1805]
### Description of problem

Test cases cannot be rearranged from within a Test Run. The documentation [here](https://kiwitcms.readthedocs.io/en/latest/guide/testcase.html#changing-the-order-of-test-cases-in-a-test-plan-or-test-run) claims that Test Cases can be rearranged from within both Test Plans and Test Runs: "Kiwi TCMS allows the user to change the order of Test Cases within a Test Plan or a **Test Run**."

### Version or commit hash (if applicable)

Tested on v8.5, v8.5-enterprise (the public instance).

### Steps to Reproduce

1. Sign into https://public.tenant.kiwitcms.org
2. Navigate to 'Search' > 'Search Test Run'.
3. Select a test run from the list
4. Observe there is no option to rearrange the test cases.

### Actual results

There is no method to rearrange test cases from within a test run which contradicts the latest KiwiTCMS documentation. 

### Expected results

A method to rearrange test cases from within a test run exists. This functionality already exists from within test plans

### Additional info (Python traceback, logs, etc.)

N/A

**Comment by atodorov** [comment]
The documentation is out of sync as it is right now. 

The capability to reorder executions inside TestRun was removed in version 5.0! You can still reorder the test cases inside the TestPlan page and when a new TR is created it will follow the same ordering.

Do you suggest to reimplement this functionality (in the upcoming new UI of this page) or are you fine with arranging the test cases only on the TestPlan page ?

**Comment by mlongmiresqa** [comment]
I think the current behavior is fine. It's arguably the more 'correct' way to handle it anyway. Thanks

**Comment by atodorov** [comment]
Reopening so we can update the documentation. @Prome88 do you want to have a go at it ?
