### ISSUE TITLE
Comments are always missing in custom report (custom_details_case_runs.html)

### ISSUE THREAD

**Issue by Ariusxiang** [kiwitcms/Kiwi#181]
### Description of problem
Since there're bugs list (blocked/failed case-run list) showing in custom report.
It would be better to display the latest comment as well.

From the file "tcms/templates/report/custom_details_case_runs.html", it should be able to display the comments if available.
However, it did not work at all.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
3.49-ee

### How often reproducible
Always

### Steps to Reproduce
1. Added comment on case run id 76 on the demo site
https://demo.kiwitcms.org/run/39/#caserun_76
2. Going to the custom report 
(https://demo.kiwitcms.org/report/custom/details/?product=5&pk__in=10)

### Actual results
There's only bug list without comments showing together.

### Expected results
Comments should be displayed together with bugs list.

**Comment by Ariusxiang** [comment]
Here's my way to show comments in custom_detail report 
Modify tcms/report/data.py as below
Line 472 from
`return dict((case_run_id, list(comments)) for case_run_id, comments in
                    groupby(rows, key=lambda row: row['case_run_id']))
`
to
`return dict([(int(key), list(groups)) for key, groups in
                    groupby(rows, lambda row: row['case_run_id'])])
`

**Comment by atodorov** [comment]
Legacy reports have been removed as part of #657 and we are working on the new Telemetry system so this becomes invalid.

Additionally the new Test Case page is able to show the comments on particular executions under the Executions card:
https://demo.kiwitcms.org/case/3332/?from_plan=1462

Upcoming feature: TestRun status matrix telemetry will be able to display comments, see:
http://kiwitcms.org/blog/kiwi-tcms-team/2019/03/03/legacy-reports-become-telemetry/
