### ISSUE TITLE
Test Execution close_date stuck at None

### ISSUE THREAD

**Issue by JNPrymek** [kiwitcms/Kiwi#1820]
### Description of problem
Test Execution's `close_date` is not saved when running test.

### Version or commit hash (if applicable)
Kiwi TCMS version 8.5

### Steps to Reproduce

1. Create a Test Run with one or more Test Execution objects.
2. Set the status of a Test Execution to any value besides the default.
3. Check the `Run Date` property (`run_date` if using API) via the web app GUI or the xml-rpc API.

### Actual results
Test Execution's `close_date` is `None`.

### Expected results
Test Execution's `close_date` is set to the date-time that the status was last changed.

### Additional info (Python traceback, logs, etc.)
This issue was first discovered after updating a Kiwi server from version 7.5 (released 29 Oct 2019) to version 8.5 (released 10 Jul 2020).  I do not have test servers with intermediate versions, so I'm not sure which version first introduced the bug.
Reproduced this issue on `https://public.tenant.kiwitcms.org/` as well as a private test server.
Attempting to set the `close_date` of a Test Execution via the xml-rpc API's `TestExecution.update` method also does not allow the `close_date` to be set.
Changing the status of a test execution that already had a `close_date` resets the value to `None`

**Comment by atodorov** [comment]
Note: UI to enable setting the start_date & stop_date for TestExecutions should be enabled after the work on branch `refactor_testrun_ui` has been merged and the related issues resolved!
