### ISSUE TITLE
Auth.login method always returns error using /json-rpc/ endpoint

### ISSUE THREAD

**Issue by StonePack** [kiwitcms/Kiwi#1847]
### Description of problem
The Auth.login method returns an error saying the username or password are incorrect when using the JSON RPC endpoint to interact with a server. I triple checked my credentials and had others with access to my server instance try and all got the same error.

### Steps to Reproduce
1. Send a request to the /json-rpc/ endpont using the Auth.login method
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"id":"jsonrpc","jsonrpc":"2.0","method":"Auth.login","params":[{"username":"USERNAME"},{"password":"PASSSWORD"}]}' \
  https://kiwi.server/json-rpc/
```

### Actual results
Error is returned saying the username or password are incorrect

### Expected results
Response returns with a sessionid

**Comment by atodorov** [comment]
The login method accepts a list of 2 positional arguments, not dictionaries.
