### ISSUE TITLE
Remove javascript:void links

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#189]
As stated in:
https://stackoverflow.com/questions/1291942/what-does-javascriptvoid0-mean/1293130#1293130

this is now a very old approach and not really necessary. It needs to go.

Notes:

1) There are 45 such links at present
2) Replace with # or #id_of_element (where applicable)
3) In case there's onClick event for this element (almost always is) it needs to return `false` as stated in the SO answer.

Send PRs for this in small groups and work on 1 template at a time.

**Comment by atodorov** [comment]
Down to 15 ATM. Migration to Patternfly helps resolve these issues. Also related #241.

**Comment by linehammer** [comment]
**Why use void(0) in JavaScript?**

The void operator evaluates the given expression and then returns undefined. If you have pass 0 as the unary expression operand to the void operator, JavaScript coerces 0 to "false" and returns, but [void](http://net-informations.com/js/iq/void.htm) doesn't care and simply returns undefined, which means "do nothing" . Put them together and you have composed a way to programmatically "do nothing" when a link is clicked. JavaScript Void(0) is often used when, inserting an expression into a web page may produce an unwanted side-effect.
