### ISSUE TITLE
Create bug from testcase in testrun 

### ISSUE THREAD

**Issue by Ywyder** [kiwitcms/Kiwi#1902]
**Problem**
When I execute a test case in a test run, there is the possibility to mark if the test case is passe, failed ... . 
In the situation that a case is failed there is no possibility to directly track a bug 
.../runs/2). Where also the link to the testcase is maintained. (..

**Solution**
I want to create a bug directly from the context of this test case. The bug should be linked to the test case as well. 

(
![Bildschirmfoto 2020-09-07 um 13 16 43](https://user-images.githubusercontent.com/10574053/92382474-f3c69200-f10c-11ea-953c-9ce991123627.png)

**Comment by Prome88** [comment]
You have the option to attach bug to selected test case execution a little bit lower in te GUI, see section Bugs and hyperlinks:

![image](https://user-images.githubusercontent.com/25688732/92389044-98020600-f118-11ea-8ca5-70f3f3f9e76c.png)

**Comment by atodorov** [comment]
The refresh part in the UI is currently broken, see https://github.com/kiwitcms/Kiwi/issues/479, the rest already exists.
