### ISSUE TITLE
Add testdevice spec to testcase

### ISSUE THREAD

**Issue by Ywyder** [kiwitcms/Kiwi#1903]
**Problem**
In our context it is important that we test on different devices, operating systems and browsers. There is are no dedicated fields for these information available. 

**Solution**
There should be the possibility to add the following fields:
- Device (a string where you can put for example Laptop, MacBook, Android Phone, iPhone, ...)
- Operating System (String field ... Windows, Linux, macOS, ... )
- Browser (string field)

Further another feature could be that the display of the fields can be managed by an admin per product, cause some fields may be not relevant for all products. But thats another feature ;-)

**Comment by atodorov** [comment]
For a workaround you can try using tags. A true resolution of the original problem is tracked in https://github.com/kiwitcms/Kiwi/issues/1344
