### ISSUE TITLE
2 timestamp fields in TestExecution class 

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1924]
Kiwi TCMS needs additional fields for the TestExecution class. This is a prerequisite for time tracking features & telemetry some of which is described at https://kiwitcms.org/blog/kiwi-tcms-team/2019/03/03/legacy-reports-become-telemetry/.

**Definition of Done**:
- [x] New field `TestExecution.start_date` of type `DateTimeField(db_index=True, null=True, blank=True)`
- [x] Rename `TestExecution.close_date` to `TestExecution.stop_date` and add `db_index=True`
- [x] New property `TestExecution.actual_duration` - the difference between the 2 fields
- [ ] New property `TestExecution.expected_duration` -> self.case.expected_duration; for convenience, see #1923 
- [x] API methods TestExecution.filter() and TestExecution.update() must support the new fields
- [x] Test coverage for all of the related changes. This means both positive/negative scenarios where this makes sense or scenarios which traverse different branches of the code where that makes sense.
- [ ] test class/test method names are descriptive and reflect the behavior of the subject under test.  A good scheme to follow is `Test<ClassUnderTest>.test_[who][what][expected_results]`
- [ ] CI pass
- [ ] All code review passed & PR merged

Hints:
- Coverage report is at https://codecov.io/gh/kiwitcms/Kiwi/tree/master/tcms
- Devel getting started docs: https://kiwitcms.readthedocs.io/en/latest/contribution.html#testing
- Django testing documentation: https://docs.djangoproject.com/en/3.0/topics/testing/

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

Note: after this is implemented we should bisect all of the existing automation framework plugins and open up issues for them to start updating these fields. Leave this comment as a reminder!

**Comment by atodorov** [comment]
Note: UI to enable setting the start_date & stop_date for TestExecutions should be enabled after the work on branch refactor_testrun_ui has been merged and the related issues resolved!

**Comment by APiligrim** [comment]
Hello, I'm one of MLH Fellows and I would like to work on this issue if possible. Please let me know and thank you for your time!
