### ISSUE TITLE
2 timestamp fields in TestRun class for planning

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1928]
Kiwi TCMS needs additional fields for the TestRun class. They are prerequisite for enabling TestRun planning functionality

**Definition of Done**:
- [x] New field `TestRun.planned_start` of type `DateTimeField(db_index=True, null=True, blank=True)`
- [x] New field `TestRun.planned_stop` of type `DateTimeField(db_index=True, null=True, blank=True)`
- [x] Make sure API methods TestRun.create() and TestRun.update() can handle these new fields
- [x] All 4 timestamp fields: start_date, stop_date (exist from before) + planned_start, planned_stop must be added to the `/runs/search/` page
- [x] All 4 timestamp fields: start_date, stop_date (exist from before) + planned_start, planned_stop must be added to the `/runs/edit/` page (not sure if we allow modification of all of them)
- [ ] Test coverage for all of the related changes. This means both positive/negative scenarios where this makes sense or scenarios which traverse different branches of the code where that makes sense.
- [ ] test class/test method names are descriptive and reflect the behavior of the subject under test.  A good scheme to follow is `Test<ClassUnderTest>.test_[who][what][expected_results]`
- [ ] CI pass
- [ ] All code review passed & PR merged

Hints:
- Coverage report is at https://codecov.io/gh/kiwitcms/Kiwi/tree/master/tcms
- Devel getting started docs: https://kiwitcms.readthedocs.io/en/latest/contribution.html#testing
- Django testing documentation: https://docs.djangoproject.com/en/3.0/topics/testing/

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

Note: after this is implemented the redesigned TestRun page should be modified a bit. Currently there is a Status button which is ON/OFF but a planned TR (e.g. for a future date) means a 3rd state. Also the UI should not allow modifications (can display an overlay on the screen) before the start date is set. Also when creating a new TR we should allow clearing the starting date to allow for TRs to be created ahead of schedule. <<< all these things are to be followed up in other issues.

**Comment by AirinB** [comment]
Hello, I am an MHL Fellow, I would like to work on this issue. Is this fine?

**Comment by AirinB** [comment]
So `planned_start` and `planned_stop` should be passed as arguments to` TestRun.create_execution`? And also there should be functions that will handle the update of these values, is this right?

**Comment by atodorov** [comment]
> So `planned_start` and `planned_stop` should be passed as arguments to` TestRun.create_execution`? 

These fields don't have anything to do with TestExecution model so the answer here is No. 

> And also there should be functions that will handle the update of these values, is this right?

I think you are referring to this sentence: `Make sure API methods TestRun.create() and TestRun.update() can handle these new fields`

which is something different. Kiwi TCMS has an API layer (see `tcms/rpc/api/testrun.py`).  The `create()` and `update()` methods rely on Django model forms and will probably not have any issues with the newly added fields. However tests will have to be updated to make sure. But this is secondary to the fields being available in the model.

**Comment by AirinB** [comment]
Thank you very much for the clarification!

**Comment by AirinB** [comment]
@atodorov for some reason this issue did not close after my PR was merged. Could you please close it?

**Comment by atodorov** [comment]
> @atodorov for some reason this issue did not close after my PR was merged. Could you please close it?

The reason is `Closes.#1928` which should have been `Closes #1928` - no dot.
