### ISSUE TITLE
Feature: customizeable TestCaseStatus

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#1932]
Similar to TestExecutionStatus the TestCaseStatus should become customizeable.  ATM we support translations of the names only. This feature will allow more semantics behind TestCases and more flexibility into organizing the workflow.

- enable in admin
- allow selection of color (in TP page) and status icons like TestExecutionStatus
- get rid of the get_proposed(), get_confirmed(), is_confirmed() methods -> replace with a boolean field that indicates whether or not this TestCase is ready to be executed.

**Comment by YouWhy** [comment]
I thought you are getting rid of the Boolean field for Test Case Status and keeping Proposed, Confirmed, Archived, Needs Update. I think it makes sense to keep it the way it is.
