### ISSUE TITLE
pbr is missing in requirements

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#195]
Please add pbr to requirements.txt since installation is failing due to missing package

**Comment by atodorov** [comment]
Do you mean this pbr?
https://pypi.python.org/pypi/pbr

If yes this is not something that we use directly so it doesn't belong to requirements.txt. If you can get me a stack trace from a failed installation this will go a long way at figuring out what's going on.

**Comment by GodfatherThe** [comment]
Before updating to the latest upstream it was ok. So it looks like something was changed.

One can get a error easily just by following Docker manual from the doc.  Here is my part of console output 
[log.txt](https://github.com/kiwitcms/Kiwi/files/1676793/log.txt)

**Comment by atodorov** [comment]
This is a problem with the latest update of Jira, which has been released meanwhile. See https://github.com/pycontribs/jira/issues/501

I will pin the version to 1.0.10 and work on the other issue related to testing these things.
