### ISSUE TITLE
Upload attachments to TestExecution

### ISSUE THREAD

**Issue by Dennis-Liu** [kiwitcms/Kiwi#1954]
can upload screenshot(attachment) in comments of running test case

--sorry for wrong spell

**Comment by atodorov** [comment]
> can upload screenshot(attachment) in commons of running test case

What do you refer to as "commons" ? Add a screenshot if possible.

**Comment by Dennis-Liu** [comment]
@atodorov  thanks for your reply, you can refer below screenshot. I can see there is one upload attachment button in running test case page, but uploaded attachment owner is test case, but not running test case. so can see the attachment in all test plan. thanks.
![image](https://user-images.githubusercontent.com/11959379/93750637-5f8d1c80-fc2e-11ea-81a7-b314a17b8fe7.png)

**Comment by atodorov** [comment]
Thanks for the explanation. This feature is on our backlog and will be implemented after the current refactoring of the TestRun page is completed!

**Comment by atodorov** [comment]
Adding attachments to test execution comments (anywhere where we have the rich text editor) has been possible for some time now. Closing this issue.
