### ISSUE TITLE
Set up automated build check 

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#196]
### Description of problem
I've just updated upstream for our team to the latest code. Last year I met issue with patternfly (#89). Now I have issue with missing dependency in requirements.txt (#195). I have a feeling that you don't have any automated build check, because it looks super basic - installation of the tool "from scratch" is failing.

So I would suggest to have some demo\staging\checkin\travis check, that the tool can actually be installed and run. Just perform all the steps from http://kiwitcms.readthedocs.io/en/latest/installing_docker.html automatically and make sure everything is fine (no errors during installation and welcome\login page is shown). Because if there are commits which were tested only in your dev environment, there definitely will be errors (and they already are) on clean machine\in clean container.

### Version or commit hash (if applicable)
 684f486

### How often reproducible
always

### Steps to Reproduce

```
<update code>
sudo docker-compose down
sudo make docker-image
sudo docker-compose up -d
```

### Actual results
failure with error

### Expected results
pass

### Additional info
Or, if you consider master as non-stable, could you please indicate, which version\branch should we use for production run in our team?

**Comment by atodorov** [comment]
The sanity tests for building & running & restarting the docker image are now integrated in Travis as part of #627. They will also call `./manage.py migrate` and make sure the login page is shown. Closing this issue.
