### ISSUE TITLE
Some text layout bugging after translation

### ISSUE THREAD

**Issue by baraksoa** [kiwitcms/Kiwi#1966]
### Steps to Reproduce

1. Set language to Hungarian.
2. Click 'Keresés' - 'Teszttervek keresése' ('Search' - 'Search Test Plans')
3. Click on an existing testplan and check the text layout.

Or

1. Set language to Hungarian.
2. Click 'Keresés' - 'Teszt futtatások keresése' ('Search' - 'Search Test Runs')
3. Click on an existing testrun and check the text layout.

### Actual results
Some translated text doesn't fit in it's original location.

![kiwi_text](https://user-images.githubusercontent.com/49455883/94340054-eb23f600-fffe-11ea-9bf2-6ca6e7cb3d3c.png)

![kiwi_text_2](https://user-images.githubusercontent.com/49455883/94340058-eeb77d00-fffe-11ea-9d79-ed27ca290ae9.png)

### Expected results
All translated text should fit in its original location.

**Comment by atodorov** [comment]
The layout issue has been resolved as part of the UI updates on this page coming with v8.8. However there is a bug with the serialization on the backend and statuses displayed in the table will appear in English even if they are translated.

Leaving this open to address the translation problem with test case status.
