### ISSUE TITLE
Improve test run change notification email

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#199]
Right now there are email notifications being sent after test run change, but they don't really contain important info *what exactly* was updated.

> Test run 8 has been updated for you.
> ### Links ###
> Test run: XXXrun/8/
> ### Basic run information ###
> Summary: XXX
> Managed: XXX.
> Default tester: XXX.
> Product: XXX
> Product version: XXX
> Build: XXX
> Estimated time: 0:00:00
> Notes:
> ### Test plan information ###
> Test Plan: XXX

Actual change was in setting "Finished" to True and this is not displayed at all in the email. I would expect having only changes in email, but not all test run details

**Comment by atodorov** [comment]
See my comment on #216. Unfortunately we don't have the internal machinery to easily make the distinction what has been changed. I'll keep researching on this topic since it is a good feature request.
