### ISSUE TITLE
make docker-image. Trouble executing the command from file tests/check-build

### ISSUE THREAD

**Issue by valghar** [kiwitcms/Kiwi#1990]
I am forced to use Docker Desktop on Windows. This may be why I'm having trouble executing the command `make docker-image`. An error occurs:
```cli
Step 12/13 : RUN ./tests/check-build
 ---> Running in b78ebf965d3f
..... Clean up first
env: 'python\r': No such file or directory
ERROR: .mo files not found
The command '/bin/sh -c ./tests/check-build' returned a non-zero code: 1
make: *** [docker-image] Error 1
```

After some time, I changed the line in the [file ./tests/check-build#L18](https://github.com/kiwitcms/Kiwi/blob/20e661ed83a973eb152794955b9898eb6f433fc5/tests/check-build#L18) to this type:
```bash
# ensure fresh translations are compiled in
find tcms/locale/ -name "*.mo" -delete
# ./manage.py compilemessages
django-admin compilemessages # new line

if [ -z "$(find -type f -name "*.mo")" ]; then
    echo "ERROR: .mo files not found"
    exit 1
fi
```

and the step continued.

**Comment by valghar** [comment]
@asankov

**Comment by atodorov** [comment]
This is a Linux only script and we don't support building the docker images on Windows, nor we have access to one, nor we even plan to do so.

Somebody wrote this blog post about running Kiwi TCMS Docker images on Windows: 
https://medium.com/@siriwardhane.yuwin/running-kiwi-tcms-as-a-docker-container-in-windows-10-home-82d74b107202

If it helps great, if it doesn't  get a Linux machine.
