### ISSUE TITLE
Bug assignee unable to update

### ISSUE THREAD

**Issue by thindata** [kiwitcms/Kiwi#2012]
Running current kiwi release and when I open a bug and assign to another user they receive a notification email but after opening the bug they don't see the reply box at the bottom? I've added all permissions both as a group and a user and still doesn't work.

**Comment by atodorov** [comment]
Tried the proposed scenario in https://public.tenant.kiwitcms.org/bugs/311/ and @kiwitcms-bot  who is the assigned user is perfectly able to comment. Indeed that account (is not a super-user account) is also able to comment and even close other bugs such as https://public.tenant.kiwitcms.org/bugs/310/.  Hence closing.

Make sure that users have the `django_comment.add_comment` permission.
