### ISSUE TITLE
Add permissions to be able to have very restricted user

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#202]
I've created group like "restricted" with no permissions added, but if I create a user and assign him to this group, looks like he is still able to view test plans and test cases. 

Expected result:
User in group with no rights should not be able to view anything

Actual result:
User is able to see test plans and test cases

**Comment by atodorov** [comment]
> User in group with no rights should not be able to view anything

what is the point of such a user then ? How are they going to interact with Kiwi TCMS in this case?

You can try disabling accounts is you don't want them to be active anymore. Not sure if this is what you need.

**Comment by GodfatherThe** [comment]
Our initial idea was to restrict user's rights until he will be approved (#203). So that user can see the interface, but cannot see any actual content. 
With #203 implemented this one won't be such important any more, but still - it sounds natural to have "view" permissions.

**Comment by atodorov** [comment]
What is the user going to "view" in this case? 

Django's policy around views is that they:

1) Create or delete data
2) Get and interact with existing data.

view permissions equals 2) and if they are missing newly registered accounts will only see a blank page and the menu, which isn't really helpful. OTOH once the accounts have been approved they will need to interact with Kiwi TCMS so they automatically gain view perms. In fact almost all pages require the user to be logged in.

Once #203 is implemented I think this request becomes obsolete.

**Comment by atodorov** [comment]
I am closing this as wontfix for now. I think the changes related to #203 are sufficient for the moment. If a user isn't approved they won't be able to login anyway so there's no need for special category of permissions.
