### ISSUE TITLE
Newly created user has is_staff=True

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#204]
### Description of problem
Looks like in core/contrib/auth/backends.py at line 233 is_staff=True is being set unconditionally for newly created users. According to comment it was done for adding product\builds\etc, but at the moment there are permissions which are configurable thru admin panel. So I believe if default user group doesn't have any "write" permissions, this is not required and moreover it confuses user - you have "Admin" bullet in menu when you're done with registration - looks strange.

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
latest

### How often reproducible
always

### Steps to Reproduce

1. Create a new user
2. Make sure line 233 in backends.py was executed and user has is_staff=True in admin panel

### Actual results
 is_staff=True 

### Expected results
 is_staff=False  OR status should be calculated dynamically depending on actual rights granted by default group.

**Comment by atodorov** [comment]
FYI is_staff controls whether or not users can access some parts of the admin panel, which is what provides the pop-up dialogs for adding new products, builds, etc. What is your use case here and what are you trying to accomplish ?

**Comment by GodfatherThe** [comment]
When I have default group for new users which doesn't contain any admin rights I don't expect those new users to be "staff".
Plus, it's confusing for user themselves - why is there "Admin" link accessible on top for me?

**Comment by atodorov** [comment]
I'm closing this as wontfix for now. `is_staff` is Django's internal mechanism which allows access to the admin part of the site. This includes auto-generated pages and forms for adding, editing and deleting records in the database. For example Product, Version, Build, etc. This is all handled automatically by Django. 

In some places (e.g. adding a new Product when creating a TestPlan) opens a popup window. This is the same part of the admin panel as described above.  Without `is_staff` all of these are not accessible to the user.


If you would like to restrict user access to Products, etc you can try removing some of their permissins, adding them into a new default group or setting the `is_staff` attribute to False. You should be able to do this by registering a signal handler for the new `user_registered` signal.
