### ISSUE TITLE
The punctuation mark ( ’ ) which include in the test plan title shows &#x27;

### ISSUE THREAD

**Issue by Cuijus** [kiwitcms/Kiwi#2061]
### Steps to Reproduce
1.Create a test plan which the title include a punctuation mark ( ’ )
2.Save this plan and search the plan 
3.In the search result list page, the punctuation mark shows (\&#x27; )

### Actual results
The punctuation mark shows (\&#x27; )

### Expected results
It should still show a punctuation mark ( ’ )

### Additional info (Python traceback, logs, etc.)
https://public.tenant.kiwitcms.org/plan/3835/tester-s-plan#testcases

**Comment by atodorov** [comment]
This is a side effect of the RPC layer HTML escaping all strings which is necessary to prevent XSS attacks, most notably in shared environments like public.tenant where all input data is untrusted. This will happen everywhere where strings are received dynamically via the API and rendered directly with JavaScript. At this point I don't believe there's anything we can do about it.

**Comment by nfk** [comment]
@atodorov can we reconsider this issue in 2022? Sharing test plan with this glitch is not smooth.

![gnome-shell-screenshot-7thzf2](https://user-images.githubusercontent.com/662724/189904285-fd630fdf-b833-4e8c-886a-21997f373f19.png)
