### ISSUE TITLE
Newer Google Chrome blocks synchronous XHR requests in main thread

### ISSUE THREAD

**Issue by localocavn** [kiwitcms/Kiwi#2100]
### Description of problem
From Test plan page, I can't add test case by using the search button

### Version or commit hash (if applicable)
8.8 and public.tenant.kiwitcms.org

### Steps to Reproduce

1. Go to test plan (from any) https://public.tenant.kiwitcms.org/plan/3910/teppy-test?
2. Click search button 
![image](https://user-images.githubusercontent.com/50696593/99514353-3c78b200-29be-11eb-86ca-d127d356e3a6.png)

3.Select test case (s) from search page:
![image](https://user-images.githubusercontent.com/50696593/99514524-6f22aa80-29be-11eb-94ab-b7fc1aee7c38.png)

### Actual results
 It backs to Testplan page with info "No records found"

### Expected results
 It backs to Testplan page with the list of testcases have been selected in previous step.

**Comment by atodorov** [comment]
I've been able to select & add exactly the same test cases to the same test plan as shown in the images:
https://public.tenant.kiwitcms.org/plan/3910/teppy-test

What browser is this - name/version/OS ? 

Are you using any ad blocker plugins, popup blockers or maybe other plugins which will block communication between pages ? 

If you go to https://public.tenant.kiwitcms.org/plan/new/ and click on the `+` button are you able to add new Product or Version via popups ?

**Comment by localocavn** [comment]
Hi Atodorov,

The browser is: Chrome/Version 87.0.4280.67 (Official Build) (x86_64).
The OS: MacOS Catalina(10.15.7).

I don't use any ad blocker plugins.
I can create Product/Version via popups from https://public.tenant.kiwitcms.org/plan/new/

**Comment by asankov** [comment]
I managed to reproduce this on **MacOS Catalina 10.15.5** with **Chrome Version 86.0.4240.198 (Official Build) (x86_64)**.

It works just wine with **Firefox 82.0.3**.

Haven't dug further into the network tab to see what requests are being made and what comes back from the back-end. For sure, when I select TCs on the TC page and click **Select**, the plan page gets refreshed, but the table stays empty.

**Comment by atodorov** [comment]
- Chrome 81.0.4044.92 on Linux - WORKS
- Chrome 87.0.4280.66-1 on Linux - FAILS
- Firefox 68.5.0esr on Linux - WORKS

From what I could see the console quickly flashed a message about synchronous XHR requests in the main thread, which I suspect Chrome started blocking in their latest versions while other browsers still haven't.

This is a bug which needs fixing but for now there is a workaround - use an older or different browser.

**Comment by asankov-cb** [comment]
more info: https://www.chromestatus.com/feature/4664843055398912

**Comment by asankov** [comment]
more info: https://www.chromestatus.com/feature/4664843055398912

**Comment by shiron-truong** [comment]
Another workaround is: 

enable "Allows synchronous XHR requests in page dismissal" by goto chrome://flags/#allow-sync-xhr-in-page-dismissal and enabled it.

**Comment by filipjonckers** [comment]
Can reproduce this issue too with Chrome Version 88.0.4324.96 (Official Build) (x86_64)
On Mac OSX Catalina 10.15.7
Expect that XHR will be blocked in near future by Firefox and other browsers too.
This could also be a potential bigger issue as the opt-out option as proposed as fix is only temporary.
