### ISSUE TITLE
New Testcase - support select component (the same as search Testcase form)

### ISSUE THREAD

**Issue by localocavn** [kiwitcms/Kiwi#2102]
**Is your feature request related to a problem? Please describe.**
I can't assign component when add a new testcase (the first/default one, then we can add more on edit Testcase later).

**Describe the solution you'd like**
Make the new Testcase form the same as the search Testcase form.

**Additional context**
current: 
![image](https://user-images.githubusercontent.com/50696593/99608011-a5ecd500-2a3f-11eb-8116-d82e1e4250c9.png)

Expect:
![image](https://user-images.githubusercontent.com/50696593/99608157-ee0bf780-2a3f-11eb-9894-99fd491dbd9b.png)

**Comment by atodorov** [comment]
Components, like tags have a many-to-many relationship with TestCase. All such records can be modified after creation.
