### ISSUE TITLE
Search - Allow_select - support "Select all" option 

### ISSUE THREAD

**Issue by localocavn** [kiwitcms/Kiwi#2103]
**Is your feature request related to a problem? Please describe.**
I want to add all searched testcases to a component. Currently, I should click one by one.

**Describe the solution you'd like**
add a select all option like this:
![image](https://user-images.githubusercontent.com/50696593/99608868-5ad3c180-2a41-11eb-8130-02c71cf36d72.png)

**Comment by brymut** [comment]
@atodorov, submitted new expense at https://opencollective.com/kiwitcms/expenses/31583
