### ISSUE TITLE
Test Run Creation On Parent Test Plan can Include Child Plan

### ISSUE THREAD

**Issue by fahdilahady** [kiwitcms/Kiwi#2152]
**Is your feature request related to a problem? Please describe.**
I manage the test plan consisting test cases from particular feature, but the test plan also created in Tree (parent child).
when I initiate a test run on the parent test plan I cannot include test cases from the child.

**Describe the solution you'd like**
view of list of test cases on the test plan can be in Tree View so we can select the test cases defined in the child test plan

**Describe alternatives you've considered**
if I remember the tree view is already exist in the former Kiwi Version (dont remember which one) maybe Im wrong

**Comment by atodorov** [comment]
> **Is your feature request related to a problem? Please describe.**
> I manage the test plan consisting test cases from particular feature, but the test plan also created in Tree (parent child).
> when I initiate a test run on the parent test plan I cannot include test cases from the child.
> 
> **Describe the solution you'd like**
> view of list of test cases on the test plan can be in Tree View so we can select the test cases defined in the child test plan
> 
> **Describe alternatives you've considered**
> if I remember the tree view is already exist in the former Kiwi Version (dont remember which one) maybe Im wrong

With version 8.9 you can add any test case to an existing test run. Thus you can add test cases from a parent test plan or even from a test plan related to a completely different product.  Try the latest version on https://public.tenant.kiwitcms.org - if that doesn't solve your issue we'll need a more detailed example of what needs to happen.
