### ISSUE TITLE
Cannot add multiple test cases to test plan at once

### ISSUE THREAD

**Issue by uipavec** [kiwitcms/Kiwi#2189]
### Description of problem
Cannot add multiple test cases to test plan at once.

### Version or commit hash (if applicable)
v8.9

### Steps to Reproduce
1. Open test plan
2. Select magnifying glass icon. New window opens.
3. Search for some test cases and select 1 or more (checkbox).
4. Click "Select" button at the bottom of the table.
5. Window closes we are back on test plan window.

### Actual results
Selected test cases were not added to test plan.

### Expected results
Selected test cases should be added to test plan.

### Additional info (Python traceback, logs, etc.)
The problem can be reproduced also at https://public.tenant.kiwitcms.org

**Comment by atodorov** [comment]
What browser version are you using ? I believe this is a duplicate of https://github.com/kiwitcms/Kiwi/issues/2100

**Comment by uipavec** [comment]
You are right. It's a duplicate of #2100.

It's seems it really depends on the browser. It does not work with:
Chrome: Version 87.0.4280.88 (Official Build) (64-bit)
Brave, Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

but it works with Firefox:
84.0.1 (64-bit)

**Comment by uipavec** [comment]
Closing as it's a duplicate of #2100
