### ISSUE TITLE
Uncaught ReferenceError: grappelli is not defined

### ISSUE THREAD

**Issue by lvchongen** [kiwitcms/Kiwi#2195]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

I deploy the kiwi tcms in my local environment. But when I open browser to access it, the debug tool will throw error message as below:

"Uncaught ReferenceError: grappelli is not defined"

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
> I deploy the kiwi tcms in my local environment.

You are missing a whole bunch of details here. What exactly are your steps and what do you mean by "deploy" ?


> But when I open browser to access it, the debug tool will throw error message as below:
> 
> "Uncaught ReferenceError: grappelli is not defined"

The `debug tool` is called Django Debug Toolbar and is only available during local development. 

Does this error prevent anything from working, does something crash ?

**Comment by atodorov** [comment]
Closing due to not enough information.
