### ISSUE TITLE
Detect HTTP\HTTPS and use in in links

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#220]
At the moment all the links from email notification are http://.... However our Kiwi instance is HTTPS, so I'm getting error in browser

> Bad Request
> Your browser sent a request that this server could not understand.
> Reason: You're speaking plain HTTP to an SSL-enabled server port.
> Instead use the HTTPS scheme to access this URL, please.

It would be nice if KIWI knows which protocol does it use and make links with correct protocol.

**Comment by GodfatherThe** [comment]
Just found out there is  `        protocol = getattr(settings, "PROTOCOL", "http")` line in UrlMixin class. So it seems Kiwi expects to have PROTOCOL variable defined in settings. 

If that's true, please add it to the doc and also maybe it makes sense to create placeholder in settings file like 
` # Change to https if you're running Kiwi under https
 PROTOCOL = 'http'`

**Comment by atodorov** [comment]
The proper way to fix this is to reliably get the URL of the Kiwi instance and not rely on settings. The registration confirmation emails already do this but other probably don't. 

We'll inspect all of the templates and make changes where necessary when we come to this item.

**Comment by atodorov** [comment]
@GodfatherThe if you are using the docker container this should not be an issue because Apache is configured to redirect all plain text requests back to HTTPS:

```
# Force the use of ssl:
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI}
</IfModule>
```


That said I acknowledge this is a problem that needs to be fixed. However some of these links are probably hard-coded in the templates as well so we'll have to inspect all of them.
