### ISSUE TITLE
Bug tracker integration with Open Project

### ISSUE THREAD

**Issue by baokhuu-ew** [kiwitcms/Kiwi#2203]
**Is your feature request related to a problem? Please describe.**
I would like the be able to 1-click file a bug from Kiwi to Open Project

**Describe the solution you'd like**
A bug tracking system integration with Open Projects. The ability to traverse links back and forth between those systems.
Nice to have: bug status integration between those systems

**Describe alternatives you've considered**

**Additional context**

**Comment by atodorov** [comment]
@mfonism ping
