### ISSUE TITLE
Honor Test cases sorting when cloning Test Plans

### ISSUE THREAD

**Issue by SrNetoChan** [kiwitcms/Kiwi#2218]
**Is your feature request related to a problem? Please describe.**
It would be nice if, when cloning a Test Plan, the children Test Plan keep the order of the Test cases.

Currently, it seems to order the cloned Test Plan orders the Test cases by TC ID.

**Comment by atodorov** [comment]
https://public.tenant.kiwitcms.org/plan/4115/tp-for-2218 - an initial TP where test cases are sorted in reverse order. See their summary and IDs.

A cloned TP which also clones the test cases:
https://public.tenant.kiwitcms.org/plan/4116/clone-of-tp-4115-with-clone-tc-yes

IDs are now increasing in size but the order of the test cases is still the same as in the source TP, see the summary.

A third TP which is again a clone but links/reuses the existing TC records:
https://public.tenant.kiwitcms.org/plan/4117/clone-of-tp-4115-with-clone-tc-no

It also has the same sortkey/IDs as the first TP.

@SrNetoChan can you explain  your use case or what are you seeing/proposing in more details b/c according to what I see there is no issue here.

**Comment by SrNetoChan** [comment]
Let me recheck. Maybe I was doing something wrong.

**Comment by SrNetoChan** [comment]
Look at these cases:

https://qgis.tenant.kiwitcms.org/plan/6/installation-smoke-tests-base

and its clone

https://qgis.tenant.kiwitcms.org/plan/22/copy-of-installation-smoke-tests-base

**Comment by SrNetoChan** [comment]
Independently of the IDs order, one can manually sort the TCs in a test plan, to make more sense to the tester to follow.

![image](https://user-images.githubusercontent.com/3607161/105789664-beff8e00-5f7a-11eb-9ecf-be4d735f2438.png)

When I clone the test plan, what I am seeing is that this manual order is changed and the IDs take over again:

![image](https://user-images.githubusercontent.com/3607161/105789733-ddfe2000-5f7a-11eb-972b-d5bd260fb115.png)

**Comment by atodorov** [comment]
> Look at these cases:
> 
> https://qgis.tenant.kiwitcms.org/plan/6/installation-smoke-tests-base
> 
> and its clone
> 
> https://qgis.tenant.kiwitcms.org/plan/22/copy-of-installation-smoke-tests-base

FTR I can't access these unless you grant access to `atodorov`.

**Comment by atodorov** [comment]
> Independently of the IDs order, one can manually sort the TCs in a test plan, to make more sense to the tester to follow.

Do you mean to sort by the sort widget which allows you to sort via Summary, Category, Author, etc ?

**Comment by SrNetoChan** [comment]
@atodorov Sorry, I probably didn't use the right terms. I am talking about the re-order functionality. And an animated gif worth a thousand words :-)

![Peek 2021-01-27 22-55](https://user-images.githubusercontent.com/3607161/106065383-23455d80-60f3-11eb-8cf2-d204f1256c24.gif)

**Comment by atodorov** [comment]
> @atodorov Sorry, I probably didn't use the right terms. I am talking about the re-order functionality. And an animated gif worth a thousand words :-)
> 

What I see is that you started to reorder the rows but didn't finish the process. Once satisfied with the new order you have to click the check-mark button to cause the sort order to be updated in the database. You will notice that the button changes and the UI changes slightly as well.

**Comment by SrNetoChan** [comment]
That got me curious, but although I seem to have been able to save the order of the parent TP, the child are still ordered/sorted by IDs. Unless I am missing something else.

![Peek 2021-01-28 15-14](https://user-images.githubusercontent.com/3607161/106158768-01dc8400-617c-11eb-87c1-dc8de824625b.gif)

**Comment by SrNetoChan** [comment]
Uhmm, I will try to do as you say, using selection first. Also good to know that I can clone using only a few selected TCs I was deleting specific platform specific TCs.

**Comment by SrNetoChan** [comment]
@atodorov selecting a subset of TCs did not seem to work. The cloned TP has all the TCs of the original one. I also was not able to make the ordering work even using the select all option.

**Comment by nfk** [comment]
Hi,

I can confirm this issue. When a TP is cloned the order is lost.

From my code review the issue can come from the clone method when we add a test case. The sortkey param is not set. https://github.com/kiwitcms/Kiwi/blob/35e0de63e90089325f60ccc364b8ebd400122d4a/tcms/testplans/models.py#L154

A `TestCasePlan` should be done to get the sortkey value of the current TP.

Le me check that with a local instance of Kiwi.
