### ISSUE TITLE
Uploaded Test Case picture goes out of the Margins.

### ISSUE THREAD

**Issue by Civiani** [kiwitcms/Kiwi#2220]
![image](https://user-images.githubusercontent.com/8633194/105713609-a57b2980-5f1b-11eb-9648-dc8ea3ca8cf7.png)

HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
Uploaded Test Case picture goes out of the Margins.

### Steps to Reproduce

1. Create New Test Case
2. Upload a bitter resolution picture in the description.
3. Picture goes out of the margins.

### Actual results
Picture goes out of the margins.

### Expected results
Picture should be resized to smaller one.

**Comment by atodorov** [comment]
Markdown redering to html doesn't enforce max size for images, nor does Patternfly.
