### ISSUE TITLE
Allow tenants to be public for reading

### ISSUE THREAD

**Issue by SrNetoChan** [kiwitcms/Kiwi#2229]
**Is your feature request related to a problem? Please describe.**

Not really a problem, but as part of a large open source community, with many different kinds of intervenients (developers, users, documentation writer, translator and testers), it is hard for us to attract new people for testing without allowing them to freely check how our test plans and test cases are organized.

Another case, is when you interact with the community in mailing lists and github. It would be nice to be able to provide a URL for a Test Case, to ask a user to follow a particular test case, or a developer to review it.

Currently, we need users to register, inform us of their registry and we need to give them permissions to the tenant. Since we use the public tenant, they will have full read\write access to the TCs

**Describe the solution you'd like**

Would be nice to have an option in settings that would make the tenant public for read-only purposes. That is, no need to login or register. Users would be able to view, search for test cases, test plans executions, etc... but not able to edit or execute tests.

**Describe alternatives you've considered**

An alternative would be to create a guest account that we could freely give to everyone. The remaining problem is that every accounts have write permissions, and I would be afraid that some random visitor could ruin the prepared test cases or plans.

**Additional context**
We are using kiwi TCMS for running manual test as a complement to unit test for www.qgis.org
We are in the early stages of the manual QA implementation.

**Comment by SrNetoChan** [comment]
@atodorov do you guys agree with this feature? If so, what would be needed to implement this? Do you have an estimated cost for it?

Thanks!

**Comment by atodorov** [comment]
1) A boolean field for the Tenant model which is False by default
2) Some page allowing setting the filed to True to enable public access b/c as of now tenants admin page is not exposed to the general public, only to super-users in the Kiwi TCMS database.
3) Adjustment to middleware to not block access to public tenants & possibly an authentication backend that grants view permmissions (similar to the existing one in the sources). 

Most of these changes should to under https://github.com/kiwitcms/tenants and be fully covered with tests.

**Comment by atodorov** [comment]
@SaurusXI once you are finished with your work on #2335 I think this one would be interesting to you. And/or some other work in the tenants repository as well afterwards.

**Comment by SrNetoChan** [comment]
@atodorov I wouldn't mind to help sponsor this feature. Any idea of how much would cost to implement it?

**Comment by atodorov** [comment]
> @atodorov I wouldn't mind to help sponsor this feature. Any idea of how much would cost to implement it?

@SrNetoChan thanks for offering sponsorship. 

FTR we don't really price issues in terms of how much they would cost to implement because that varies wildly between contributors even on the core team. Our pricing for bounties till now has been based on "perceived value", iow how much we think an issue is worth having in the project sooner rather than later.  

That said I believe a 300 EUR bounty on this issue is a good match compared to others!  If you agree to that please head over to https://opencollective.com/kiwitcms/contribute !

**Comment by SrNetoChan** [comment]
I think it's fair enough. Can I do it with a donation? Is this the correct way?

**Comment by SrNetoChan** [comment]
@atodorov donation done. You should receive the confirmation in a few days. Thanks

**Comment by atodorov** [comment]
@SrNetoChan a pre-release has been deployed live. Can you give it a try. See PLUGINS -> Tenant -> Edit.

For example here's how it looks like on our end:
https://tcms.tenant.kiwitcms.org/runs/2/

**Comment by SrNetoChan** [comment]
Thank you @atodorov I surely will!!

**Comment by SrNetoChan** [comment]
Hello @atodorov When I try to open PLUGINS > Tenant > Edit I am always pushed to the authentication page.

![image](https://user-images.githubusercontent.com/3607161/122855720-8c7d7580-d30d-11eb-9a42-cdbdcdfa907f.png)

Maybe something related to permissions?

Thanks for your work!

**Comment by SrNetoChan** [comment]
Opening the https://tcms.tenant.kiwitcms.org/runs/2/ worked fine by the way.

**Comment by atodorov** [comment]
> 
> Maybe something related to permissions?
> 

Indeed. Should be fine now, please try again.

**Comment by SrNetoChan** [comment]
@atodorov worked like a charm, thank you very much. I hope this feature is helpful for others too. For us, I think it will be very important.
