### ISSUE TITLE
No emails received for replies/update to existing bugs

### ISSUE THREAD

**Issue by saf0102** [kiwitcms/Kiwi#2232]
### Description of problem
Assignee (Default bug owner) opens a bug and assigned bug to a user who receives an email notification.  
Assigned user replies in Kiwi TCMS to the bug.  
Assignee updates/replies to the bug.
No email notification is received for the bug replies/updates.

### Steps to Reproduce
1. Assignee opens a bug.
2. Bug is assigned to another user.
3. Assigned user receives an email notification and navigates to the bug in Kiwi TCMS and enters a comment/reply.
4. Assignee enters a comment/reply.
5. Emails notifications are checked/verified for Assignee and Assigned Bug users.

### Actual results
Assigned user receives a Bug email notification and navigates to the Kiwi TCMS link and updates/replies to the bug.
Assignee replies/updates to the bug in Kiwi TCMS.
Assignee and Assigned user DO not appear to receive email notification of any replies/updates to the Bug.

### Expected results
Assignee and Assigned users to received email notification when replies/updates have been applied to a Bug in Kiwi TCMS.

**Comment by saf0102** [comment]
Tested in **public.tenant.** 
Note in our own Kiwi-TCMS environment we have 2 different email users.  
For security reasons I did not want to use these.  So I could only use the one email user as the Assigned and Assignee on this public tenant.

Raised Bug : Bug 331 raised by owner (saf0102) and to be assigned to user (saf0102).
Assigned user (saf0102) received the email, as per image below.

Assigned user navigates to link and adds a comment/reply.
![image](https://user-images.githubusercontent.com/78427095/109285719-51fd4380-7819-11eb-8e62-8080d71e2f17.png)
![image](https://user-images.githubusercontent.com/78427095/109285838-75c08980-7819-11eb-956a-5334ab4055b2.png)

Bug owner (Assigned) adds an additional comment.
**No further email notifications are received after the first initial email.**

Can you please provide feedback with regard to this issue please, as we would like to use the email notification feature.

**Comment by atodorov** [comment]
@mfonism FYI ^^^. I think the root cause here is that we don't trigger anything on comments, probably lacking the appropriate signal handlers. See `tcms/signals.py` and tcms/bughs/views.py for more hints. I'm not even sure we need signals here since the emailing function is executed in a different thread anyway.

**Comment by saf0102** [comment]
Thank you for the feedback. 
Also this is applicable for when a bug is reassigned and the person it has been re-assigned to, currently does not receive email notification.

**Comment by saf0102** [comment]
My company advised me they are prepared to pay the 50 Euro Bounty in order for this feature to be progressed upon ASAP.

**Comment by atodorov** [comment]
> My company advised me they are prepared to pay the 50 Euro Bounty in order for this feature to be progressed upon ASAP.

Feel free to make your donation at https://opencollective.com/kiwitcms#category-CONTRIBUTE

**Comment by cmbahadir** [comment]
Hello @mfonism if you or anyone else have not started to work on this, I would like to pull it.

**Comment by atodorov** [comment]
> My company advised me they are prepared to pay the 50 Euro Bounty in order for this feature to be progressed upon ASAP.

@saf0102 we already have a contributor working on this. They've also [contributed in the past](https://github.com/kiwitcms/Kiwi/pulls/cmbahadir).  Please consider supporting the community by delivering on your promise. Go to https://opencollective.com/kiwitcms#category-CONTRIBUTE to make your contribution.

**Comment by saf0102** [comment]
Hi

My company shall be sending the 50 Euro Bounty today or tomorrow.

Many Thanks.

Sally

**Comment by thindata** [comment]
Hi sounds like a useful feature is there an install/upgrade guide for this fix?
