### ISSUE TITLE
Update custom SSL certificate to production with Docker

### ISSUE THREAD

**Issue by KartikEK** [kiwitcms/Kiwi#2238]
I have followed the steps given to run the kiwi tcms with docker. I can successfully setup the process.
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html

But, im not sure how to use my own certificate files this website. I saw this line, but i dont know how this can be done, i'm very new to Docker and linux based OS system. 

![image](https://user-images.githubusercontent.com/20593145/107027217-d25bf600-67d1-11eb-868b-4a56c6a29248.png)

I have used my custom domain "testportal.mycompany.com" in initial setup of docker compose. I haver certificate files of "*.mycompany.com" domain. I just want to apply it now.  

Please help to proceed on this further.

**Comment by atodorov** [comment]
> But, im not sure how to use my own certificate files this website. I saw this line, but i dont know how this can be done, i'm very new to Docker and linux based OS system.

This makes it a support question so you should follow the instructions at https://kiwitcms.org/support/
