### ISSUE TITLE
Request to claim bounties for closing #2145, #1610 and #1615

### ISSUE THREAD

**Issue by pandafy** [kiwitcms/Kiwi#2262]
Open Collective expense link: https://opencollective.com/kiwitcms/expenses/34509

**Comment by pandafy** [comment]
@atodorov what about enabling GitHub Discussions on this repository and using it for tasks like support and claiming bounties?
The Discourse forum link on https://kiwitcms.org/community/ seems broken as well. It will also keep issue tracker clean.

**Comment by atodorov** [comment]
Approved.
