### ISSUE TITLE
Printing a test run adds entity paths

### ISSUE THREAD

**Issue by dkoerner85** [kiwitcms/Kiwi#2263]
### Description of problem

When printing a test run, KIWI TCMS adds entity paths in brackets after the entity names. This creates a bloated report that's hard to read.

### Version or commit hash (if applicable)

9.0.1-Enterprise

### Steps to Reproduce

1. Open a test run (e.g. https://public.tenant.kiwitcms.org/runs/2861/)
2. Hit CMD+P to print.

### Actual results

"Produkt: Kiwi TCMS (/runs /search/?product=2660)"
"Version: unspecified (/runs /search/?product=2660& product_version=3562)"
"Build: 2020-12-14 (/runs /search/?product=2660& product_version=3562& build=2882)"

### Expected results

"Produkt: Kiwi TCMS"
"Version: unspecified"
"Build: 2020-12-14"

### Additional info (Python traceback, logs, etc.)

I'm using macOS 11.1 Big Sur and Firefox 85.0, german locale.

**Comment by atodorov** [comment]
The test run page can benefit from removing these URLs when it is printed. Adding a `noprint` CSS class usually works. See the attached images for reference:

![links_01](https://user-images.githubusercontent.com/1002300/108985882-37509080-769a-11eb-8be2-fde5e4180f60.png)

![links_02](https://user-images.githubusercontent.com/1002300/108985875-36b7fa00-769a-11eb-8163-5a8d782469d0.png)
