### ISSUE TITLE
Printing a test run adds buttons

### ISSUE THREAD

**Issue by dkoerner85** [kiwitcms/Kiwi#2264]
### Description of problem

When printing a test run, the buttons to add users, tags or attachments are printed as well. This creates a bloated report that looks unprofessional.

### Version or commit hash (if applicable)

9.0.1-Enterprise

### Steps to Reproduce

1. Open a test run (e.g. https://public.tenant.kiwitcms.org/runs/2861/)
2. Hit CMD+P to print.

### Actual results

The upload buttons are printed:

```
Befestigung
Datei Besitzer Datum
Keine Belege gefunden
Upload attachment:
Durchsuchen... Keine Datei ausgewählt.
Add attachment
```
### Expected results

Upload buttons should be omitted.

```
Befestigung
Datei Besitzer Datum
Keine Belege gefunden
```

### Additional info (Python traceback, logs, etc.)

I'm using macOS 11.1 Big Sur and Firefox 85.0, german locale.

**Comment by atodorov** [comment]
> When printing a test run, the buttons to add users, tags or attachments are printed as well. 

Do you mean the `+` buttons? If possible add a screenshot with the buttons you think should not be visible in the printed page.

**Comment by dkoerner85** [comment]
From a users perspective, I think that all elements that suggest interactivity should be removed from the printed page. I have marked all elements that fall into this category.

![2](https://user-images.githubusercontent.com/32361860/109001812-b0091a00-76a5-11eb-8bb6-66b83ab9e86b.png)
![3](https://user-images.githubusercontent.com/32361860/109001815-b13a4700-76a5-11eb-9a57-ea47f7725a4a.png)
![1](https://user-images.githubusercontent.com/32361860/109001817-b1d2dd80-76a5-11eb-9ea6-ccae647383d5.png)

**Comment by atodorov** [comment]
@pandafy you may be interested in taking this one and #2263 too.

**Comment by pandafy** [comment]
I am interested indeed,  thanks for pinging me :smile: 

Should I solve these two issues in a single PR? Patches for these issues will be almost the same.
