### ISSUE TITLE
Test Case Search Page does include Test Plan as a filtering option

### ISSUE THREAD

**Issue by YouWhy** [kiwitcms/Kiwi#2283]
**Is your feature request related to a problem? Please describe.**
When I go to the Test Case Search page, I cannot search for Test Cases that belong to a Test Plan. Also, in the results displayed, I dont see what Test Plans a Test Case is associated with. 

**Describe the solution you'd like**
Consider allowing user to choose Test Plan on the Test Case Search Page. Consider displaying what test plans the test cases are associated with in the output of the results.

**Describe alternatives you've considered**
Cant think of any

**Additional context**
I would use Test Plans as a way to group test cases together. So, I should have the ability to search for Test Cases within a test plan.

**Comment by sha-marsig** [comment]
Yes I have a similar use case. I am trying to find out all the unassigned test cases and the only way I can see is to navigate into each test case.

**Comment by atodorov** [comment]
@mfonism can you take a look at this issue?

**Comment by mfonism** [comment]
Yes. You can assign it to me.
