### ISSUE TITLE
Anonymous users have access rights

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#230]
Back to security\auth\restrictions topic. Just found out that even for anonymous users they have access to all the data (test plans, test runs).

Can we have only login\register pages available for anonymous users?

**Comment by atodorov** [comment]
@GodfatherThe this is a quick fix but we'd like to keep the current functionality available. Anonymous access is useful for open source projects for example, who want others to be able to see the test results, etc. 

IMO all views should be login_required by default but then you need to be able to relax this if you want to give access to other people.
