### ISSUE TITLE
Cannot create Testrun

### ISSUE THREAD

**Issue by bluesource** [kiwitcms/Kiwi#2303]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
Upgraded from ver 8.6 to ver 10.0.0 via docker
migration.py went fine
manage.py showmigrations showed all migrations applied successfully

A Testrun cannot be created, the "Save" button has no function.

Error in Browser-Console:
"grappelli.min.js:1 Uncaught ReferenceError: grappelli is not defined
at grappelli.min.js:1"

NOTE: The same error is also at your public tenant, but nevertheless the testrun there has been created.

### Version or commit hash (if applicable)
v10.0

### Steps to Reproduce

1. Search Testplan
2. Click on a given Testplan
3. Select on or more Test-Cases
4. Click "New TestRun"
5. Click the "Save" Button

### Actual results
Upon clicking the save button, the sites refreshes, nothing happens

### Expected results
TestRun is created

**Comment by atodorov** [comment]
> Error in Browser-Console:
> "grappelli.min.js:1 Uncaught ReferenceError: grappelli is not defined
> at grappelli.min.js:1"
> 

This error is unrelated I think. 


> NOTE: The same error is also at your public tenant, but nevertheless the testrun there has been created.

Then we need more information to be able to reproduce. A screencast would be a good first item to provide.

**Comment by bluesource** [comment]
Hi Alex,

**Screencast:** https://user-images.githubusercontent.com/3057403/111272321-bfd7a680-8632-11eb-9de9-17879e0b6e8c.mp4

**httpd stoud logs while screencast:**

`web_1_f85a966859ed | 172.21.0.1 - - [16/Mar/2021:07:28:18 +0000] "GET /runs/new/?p=40&c=2941&c=2942 HTTP/1.0" 200 3321 "https://tcms.bluesource.at/plan/40/mp-client" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
web_1_f85a966859ed | 172.21.0.1 - - [16/Mar/2021:07:28:21 +0000] "POST /runs/new/ HTTP/1.0" 200 3321 "https://tcms.bluesource.at/runs/new/?p=40&c=2941&c=2942" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"`

regards,
Michael

**Comment by atodorov** [comment]
You don't have a build selected. 

The changes in master already make sure to show an error message when the build isn't selected and also change a few more items on this page.
