### ISSUE TITLE
Don't set TR.start_date automatically

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#2323]
Following up on https://github.com/kiwitcms/Kiwi/pull/2307#discussion_r597958888

Currently `start_date` is set automatically but that doesn't need to always be the case. An argument can be made for a manager creating test runs for future execution, distributing them among the team and setting planned_start/planned_stop. But we still want the actual start/stop timestamps to reflect when the work was performed, rather than setting them arbitrary.

I can think of 2 cases:

-  If start_date is None then set that automatically upon receiving any status on any test execution
-  Convert the Started/Finished toggle button to a 3 state button to explicitly have the start reflected.

Also related https://github.com/kiwitcms/Kiwi/issues/1939

**Comment by atodorov** [comment]
@AirinB do you want to take a stab at this one and the related #1939 ? I'm not quite sure how we want to solve them but they are connected.

**Comment by AirinB** [comment]
> @AirinB do you want to take a stab at this one and the related #1939 ? I'm not quite sure how we want to solve them but they are connected.

@atodorov Sure, yes.

**Comment by AirinB** [comment]
@atodorov I hope now it's fine
