### ISSUE TITLE
Kiwi TCMS and Nomad by Hashicorp

### ISSUE THREAD

**Issue by iovcho** [kiwitcms/Kiwi#2330]
### Description of problem
Hello. I try run kiwi tcms in Nomad by Hashicorp. After pull the images I run ./manage.py initial_setup 
Everything looks good and I can login in tcms, If I try to create test plan after save button I have error 500. The test plan is created, but if I try to access it, I have error 500 again.
I use kiwitcms/kiwi latest image for docker and mysql/mysql-server:5.7
I set ''DEBUG = True'
/venv/lib/python3.6/site-packages/tcms/settings/product.py 
In /var/log/httpd/ don't have any logs and errors. 

### Version or commit hash (if applicable)
Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)
docker image: mysql/mysql-server:5.7
docker image: kiwitcms/kiwi latest
### Steps to Reproduce
Here is the kiwitcms.nomad file

job "kiwi" {
  datacenters = ["xx"]
  type        = "service"

  constraint {
    attribute = "${node.unique.name}"
    value = "xxx"
  }

  group "kiwi" {
    count = 2

    volume "kiwi" {
    type      = "host"
    read_only = false
    source    = "kiwi"
    }

    volume "mysql" {
    type      = "host"
    read_only = false
    source    = "mysql"
    }

    restart {
      attempts = 10
      interval = "5m"
      delay    = "25s"
      mode     = "delay"
    }

    task "kiwi" {
      driver = "docker"

      env {
        KIWI_DB_HOST = "xxx"
        KIWI_DB_PORT = "3306"
        KIWI_DB_NAME = "xxx"
        KIWI_DB_USER = "xxx"
        KIWI_DB_PASSWORD = "xxx"

        EMAIL_HOST = "mail.domain.com"
        EMAIL_PORT = "25"
        EMAIL_HOST_USER = "kiwi@domain.com"
        EMAIL_HOST_PASSWORD = "xxx"

      }

      config {
        image = "kiwitcms/kiwi"

        port_map {
          web = 8443
        }
      }

      volume_mount {
        volume      = "kiwi"
        destination = "/Kiwi/uploads"
        read_only   = false
      }

      resources {
        cpu    = 500
        memory = 2048

        network {
          mbits = 1
          port  "web" { static = 9090 }
        }
      }

      service {
        name = "dbwebapp"
        port = "web"

        check {
          type     = "http"
          path     = "/health"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
##
    task "mysql-server" {
      driver = "docker"

      config {
        image = "mysql/mysql-server:5.7"

        port_map {
          db = 3306
        }

        volumes = [
          "docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/",
        ]
      }

      template {
        data = <<EOH
CREATE DATABASE xxx;
CREATE USER 'xxx'@'%' IDENTIFIED BY 'xxx';
GRANT ALL PRIVILEGES ON xxx.* TO 'xxx'@'%';
EOH

        destination = "/docker-entrypoint-initdb.d/db.sql"
      }

      volume_mount {
        volume      = "mysql"
        destination = "/var/lib/mysql"
        read_only   = false
      }

      resources {
        cpu    = 500
        memory = 1024

        network {
          mbits = 10

          port "db" { static = 3306 }
        }
      }

      service {
        name = "mysql-server"
        port = "db"

        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}

**Comment by iovcho** [comment]
I run mysql and kiwi in two different jobs and now works correctly.

**Comment by atodorov** [comment]
This is a vendor specific support question. If you'd like more people to see it and maybe answering follow the instructions on
https://kiwitcms.org/support/ and
https://github.com/kiwitcms/Kiwi/issues/new/choose and post your question on StackOverflow with the kiwi-tcms tag!
