### ISSUE TITLE
Settings items repeating in menu

### ISSUE THREAD

**Issue by KartikEK** [kiwitcms/Kiwi#2348]
if group of people using this site, everyone is getting the setting menu of opened object in their window.  Refer the screenshot,
![image](https://user-images.githubusercontent.com/20593145/115341955-18b4d480-a1c7-11eb-8ed2-27e44156ef73.png)

I feel, this needs to corrected, it only shows the respective users object setting. But not others.

**Comment by atodorov** [comment]
Duplicate of #991 and fixed in v10.0
