### ISSUE TITLE
How components should be associated with Test Plan or Test Case?

### ISSUE THREAD

**Issue by KartikEK** [kiwitcms/Kiwi#2349]
I don't find way to associated components with new test plans or test cases.

Refer new test plan, no way to add component,
![image](https://user-images.githubusercontent.com/20593145/115342256-9842a380-a1c7-11eb-9446-5258c4467f45.png)

Refer new test case, here too no option to add component,
![image](https://user-images.githubusercontent.com/20593145/115342334-b8726280-a1c7-11eb-8ef5-2e1f55d2e786.png)

Seems it is bug?

**Comment by atodorov** [comment]
Not a bug.  Many-to-many relationships can be manipulated after creating a new object. For test case see the actual test case page:

![Screenshot_2021-04-22 Kiwi TCMS - TC-10260 Do we have advertising banner for on site presence](https://user-images.githubusercontent.com/1002300/115719176-84906c00-a384-11eb-9f66-25e8213b8bd4.png)
