### ISSUE TITLE
Add possibility to customize test execution statuses

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#236]
### Description of problem
At the moment there are 8 (eight!) statuses for Test case run: Idle, Passed, Failed, Blocked, Waived, Paused, Running, Error.
I see the point that it was done to cover all theoretical cases, but still required statuses vary from team to team, so it's better to provide possibility to customize them. For example, for us it would make sense to have "investigation\external feedback required" or something like thisand in the same time we don't need "waived, paused, error" statuses.
As a workaround we agree in our team which statuses to use, but still it's better to be done on Kiwi side.

### Additional info
When I went thru the code, I've found out that it's heavily hardcoded, even the order of the fields in the DB is important, so it seems a lot of refactoring will be required here...

**Comment by atodorov** [comment]
Note: statuses are also hard-coded in `tcms_api/immutable.py::TestCaseRunStatus`.
