### ISSUE TITLE
set the base Url, but still showing the IP when I open the portal

### ISSUE THREAD

**Issue by Anuj1314** [kiwitcms/Kiwi#2375]
I have configured Kiwi on the AWS ec2 instance.
routing it through Nginx, which is on a different machine.
I have set up the domain as tcms.mycompany.com by docker command,
**docker exec -it kiwi_web /Kiwi/manage.py set_domain tcms.mycompany.com**

still, whenever I open the link, it opens the Dashboard with PrivateIP if the machine e.g. https://10.30.217.223/

DNS is mapped with Nginx machine and Nginx is routing it to the instance of Kiwi which is 10.30.217.223.

**Comment by atodorov** [comment]
From https://kiwitcms.readthedocs.io/en/latest/installing_docker.html?highlight=set_domain#configuration-of-kiwi-tcms-domain

> This is used to construct links to test plans, test cases, etc.

These links are used for email notifications, bug comments, etc. This has nothing to do with how the machine thinks its name is or how other machines on the network think it is called.

> DNS is mapped with Nginx machine and Nginx is routing it to the instance of Kiwi which is 10.30.217.223.

I don't understand what this means but I don't think it is correct. Nginx in this case is a reverse proxy. A DNS server is for example bind or Route63 on AWS which map addresses to names.
