### ISSUE TITLE
Redmine: automatically assign newly created issues

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#2383]
Redmine.report_issue_from_testexecution() will open a new issue which is unassigned.  A new feature request has been identified where Kiwi TCMS should provide the ability to assign the newly created issues automatically.

I propose the following for maximum flexibility: 
settings.REDMINE_NEW_ISSUE_ASSIGNEE = None # "username in Redmine"
settings.REDMINE_NEW_ISSUE_CALLBACK = "path.to.function"

where `function(execution, user, issue)` <- default implementation will be to search for assignee based on settings.

**Comment by atodorov** [comment]
@mfonism can you take a look at this one too please? (Note: I can assign it to you after you comment on react on this issue, otherwise I can't).

**Comment by mfonism** [comment]
I can work on this one.

**Comment by nfk** [comment]
We are facing with the same kind of issue with gitlab. Can we override the behaviour of a given IssueTracker with a Kiwi plugin ?

I have in mind to override the behaviour of the function `report_issue_from_testexecution` to customize following our needs the title, description, label, assignees...  https://github.com/kiwitcms/Kiwi/blob/a92ad6b4105a899cd2fc15b3bbb37d49fc8518cc/tcms/issuetracker/types.py#L240

**Comment by atodorov** [comment]
See https://kiwitcms.org/blog/tags/customization/ for a workaround. You can override everything by providing an implementation which does exactly what you need. At the moment this is a bit cumbersome.

**Comment by nfk** [comment]
Thank you @atodorov, I exactly did that and it works great. Really easy to customize the default Kiwi behaviour.
