### ISSUE TITLE
Start_date field in Testrun is giving the None instead of the actual date

### ISSUE THREAD

**Issue by ravitejapagala** [kiwitcms/Kiwi#2392]
HINT: try to 
### Description of problem
While retrieving the test run details as a response from the jsonrpc , getting the start_date field as a None value instead of the actual startdate&time.

When I open the any testrun it is not showing the start_date-value but once it is finished it is showing the finished date and time.
### Steps to Reproduce

1.
2.
3.

### Actual results
start_date:None

### Expected results
Current date&time
Ex :
start_date: 2021-05-19 21:18:39.412523

**Comment by atodorov** [comment]
I've tested this on https://public.tenant.kiwitcms.org/runs/2833/ and  the results look fine
![tr_start_date](https://user-images.githubusercontent.com/1002300/118887117-9113d000-b902-11eb-96c9-a0c824e37ff0.png)

@rajatkverma feel free to reopen when you can provide *Version* and *Steps to reproduce*!

**Comment by ravitejapagala** [comment]
Hi

Regarding the issue with Date and time field in  Testrun page
In the issue 2392:
In the above screenshot of TestRun.filter({"id":2833})
But from the 2985(id of the Testrun) it is not showing the start_date value.
I tried in the https://public.tenant.kiwitcms.org/runs/search/    ------>for all testruns
and https://public.tenant.kiwitcms.org/runs/2999/   ------>testrun
Here I am attaching the screenshots of the jsonrpc and ui of the testrun page

Still observing the same issue where time stamp is not displayed
steps to reproduce:
1. Login to tcms
2. navigate Testing ---> New Test Run
3. Fill summary and other necessary details and click save
4. After testrun is created the timestamp field remains empty
issue observed in verison 10.0
Screenshot attached 
kindly let me know if you need more details.
Thank you
![Screenshot from 2021-05-20 17-00-59](https://user-images.githubusercontent.com/84474944/118973444-4e4c0980-b98f-11eb-9b24-431395daff6b.png)
![Screenshot from 2021-05-20 17-05-54](https://user-images.githubusercontent.com/84474944/118973457-50ae6380-b98f-11eb-8e8e-100710327e9b.png)
