### ISSUE TITLE
UI Issue in error message while adding build in Creating a test run

### ISSUE THREAD

**Issue by popoycrp** [kiwitcms/Kiwi#2404]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
During creating a test run, adding current build, makes an error message that cannot be seen

### Steps to Reproduce

1.  Search a test plan and select it
2.  In test cases below select All and create a New Test Run
3.  on the right portion, click the + button
4.  Click the "+" button in ADD build screen
5.  Type a existing value and Product
6.  Error message appears

### Actual results
The text error message cannot be read because it was camouflaged with the red background since the text also is red

### Expected results
Text should be more visible in the eye not blended with the background

### Click the image captured
https://drive.google.com/file/d/1t9O5L_R19ySLCj965TntV3noIifn7owV/view?usp=sharing

**Comment by atodorov** [comment]
FTR the problematic widget has the "errorlist" CSS class which we override in `static/style/patternfly_override.css` and it looks like that in `admin/base_site.html` this file gets loaded too early and doesn't override Django's defaults.
