### ISSUE TITLE
Getting Start_date field none in new testrun creation, but it should provide the datetime once click on the save button

### ISSUE THREAD

**Issue by ravitejapagala** [kiwitcms/Kiwi#2405]
getting null in rpc while creating the testrun from the ui.

It should create the current datetime automatically once testrun creation 

but i am getting the null 

i will share the screenshot
![Screenshot from 2021-06-02 11-03-32](https://user-images.githubusercontent.com/84474944/120429215-a113c100-c392-11eb-83b6-2fe980288f56.png)

**Comment by atodorov** [comment]
As mentioned previously in #2392 and #2394 this is working as intended. The "Started at" field represents when testing has started, not when the test run was created. These two events don't always happen at the same time. You have big colorful buttons with hints next to the timestamp fields if you wish to start/stop testing.
