### ISSUE TITLE
[Docker] A few improvements could be made to the Docker image

### ISSUE THREAD

**Issue by Dr-Shadow** [kiwitcms/Kiwi#2436]
Version tags are missing from Docker Hub so unless we build our image, we are stuck with "latest" tag which is not tied to a specific version.

SSL termination is hardcoded in the Dockerfile, it would be better to support SSL offloading on the reverse proxy if applicable. (We should be able to enable/disable SSL through environment variables)

EDIT : For anyone wondering, I just discovered SSL enforcement can be disabled through this ->
```
environment:
    KIWI_DONT_ENFORCE_HTTPS: "true"
```

**Comment by atodorov** [comment]
> Version tags are missing from Docker Hub so unless we build our image, we are stuck with "latest" tag which is not tied to a specific version.
> 

This is a decision made on purpose, see main website, it says: "Only latest releases". 

The other reason is that Docker Hub started enforcing a version retention limit so this isn't something we can control, see:
https://kiwitcms.org/blog/kiwi-tcms-team/2020/08/18/kiwi-tcms-container-images-now-available-via-red-hat-quayio/


> SSL termination is hardcoded in the Dockerfile, it would be better to support SSL offloading on the reverse proxy if applicable. (We should be able to enable/disable SSL through environment variables)
> 
> EDIT : For anyone wondering, I just discovered SSL enforcement can be disabled through this ->
> 
> ```
> environment:
>     KIWI_DONT_ENFORCE_HTTPS: "true"
> ```

So looks like the SSL enable/disable functionality isn't a problem.  

A better SSL implementation will be available once we implement support for Let's Encrypt which is on the roadmap:
https://kiwitcms.org/blog/atodorov/2021/01/29/project-roadmap-2021/

**Comment by Dr-Shadow** [comment]
I always forget to check Quay.io, thank you !
