### ISSUE TITLE
legal notice / about us

### ISSUE THREAD

**Issue by xbln** [kiwitcms/Kiwi#249]
In some countries a link to some legal notice / about us stuff is mandatory and should be reachable on the website any time (in German we call it Impressum). It is almost impossible and very dangerous (violations will incur heavy fines) to run a website like kiwi without this link.  

Where and how can I place such a link?

**Comment by atodorov** [comment]
I think this needs to be a webpage on the website repository:
https://github.com/kiwitcms/kiwitcms.github.io

and then probably linked from the help section of the application. 

Thanks for bringing this up! I wil take care of it.

**Comment by atodorov** [comment]
@xbln fixed at http://kiwitcms.org/legal/ with link in footer. I've added a link from the help menu for the demo site. It will be visible in a few days when the demo is updated to the latest version.
