### ISSUE TITLE
Create-User permission also needs SuperUser in order to create an account for another user.

### ISSUE THREAD

**Issue by geeky-neo** [kiwitcms/Kiwi#2496]
**Is your feature request related to a problem? Please describe.**
SuperUser permissions needed by an admin, to create an account for another user(tester, engineer etc).

**Describe the solution you'd like**
SuperUser permissions should NOT be needed to create an account for another user.

**Describe alternatives you've considered**
Granting admin SU permissions temporarily.

**Additional context**

**Comment by atodorov** [comment]
This is working as designed. Regular users can either create accounts for themselves - nothing is stopping them from doing so, or super-user creates accounts for them. This is not going to change.

**Comment by geeky-neo** [comment]
Thanks a lot for your prompt response @atodorov .

We have an open source project, so don't want bots creating accounts. Hence we want to manage our team of testers by invitation only.

Also, there is a permissions system with a line saying "Create user". It is counter-intuitive (hence the bug report) that we can create a group Administrator with such permission and they are not allowed to actually create a user unless they are granted super user status. In particular, this is the role we'd like to use for our test team managers, without granting them full permission on the system for features that can potentially break the instance.

**Comment by atodorov** [comment]
> Also, there is a permissions system with a line saying "Create user". It is counter-intuitive (hence the bug report) that we can create a group Administrator with such permission and they are not allowed to actually create a user unless they are granted super user status. 

Reopening, that's something different and could also be a bug, we'll have to look. 

To elaborate: The "Can Add User" aka `auth.add_user` permission label controlls whether or not objects can be added in the DB. 

Notes:
I've tried assigning auth.view_user & auth.add_user to the account kiwitcms-bot and it was able to navigate to the Add button but the view resulted in a 403.  

I see that we're overriding has_change_permission to allow only super-user to be able to change password, nothing obvious for has_add_permission. Could be related, needs more investigation.

**Comment by atodorov** [comment]
> We have an open source project, so don't want bots creating accounts. Hence we want to manage our team of testers by invitation only.

@geeky-neo ping. I am curious to know which OSS project that is and if we can collaborate more closely. My email is in my profile, you can also use the official @kiwitcms.org address (see our support page).

**Comment by geeky-neo** [comment]
> > We have an open source project, so don't want bots creating accounts. Hence we want to manage our team of testers by invitation only.
> 
> @geeky-neo ping. I am curious to know which OSS project that is and if we can collaborate more closely. My email is in my profile, you can also use the official @kiwitcms.org address (see our support page).

Thanks for the interest @atodorov . I've shared your email ID with the concerned person.
