### ISSUE TITLE
Private scope for a pre-released work.

### ISSUE THREAD

**Issue by geeky-neo** [kiwitcms/Kiwi#2498]
**Is your feature request related to a problem? Please describe.**
Private scope for a pre-released work.

Suppose I create a test plan/case/run for a Product X, that is to be released in the coming 3 months, I would not want that test plan/case/run to be visible to other users as it might leak the product specification and features.

**Describe the solution you'd like**
Any test case/plan/run shouldn't be visible to any unintended user. By default it should be visible only to the user who has created it.

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by atodorov** [comment]
> Suppose I create a test plan/case/run for a Product X, that is to be released in the coming 3 months, I would not want that test plan/case/run to be visible to other users as it might leak the product specification and features.

That means you don't trust the rest of your team to keep your secrets. That's an organizational problem IMO. 


You can exclude all permissions from the standard groups/users and assign object-level permissions on each TR/TC/TR that you want to keep secret, possibly allowing only yourself to be seeing all of this. It would be a bit cumbersome but will get the job done. 

Such functionality is already available within Kiwi TCMS so nothing more to do here.

**Comment by geeky-neo** [comment]
Hi @atodorov 

Thanks a lot for the prompt response.

I might have fallen short on explaining, actually missed a point to tell, that our's is an Open Source project and the testers are a **group of volunteers**, so is the need of such a tight user access control system.

We also don't want bots creating accounts . Hence we want to manage our team of testers by invitation only

**Comment by atodorov** [comment]
> Hence we want to manage our team of testers by invitation only

And what's the problem to have your super-user create their accounts then ?

**Comment by atodorov** [comment]
> that our's is an Open Source project

You may want to look into our OSS Friends program that would allow you to have a free-of-charge SaaS tenant, see website.

**Comment by geeky-neo** [comment]
> > Hence we want to manage our team of testers by invitation only
> 
> And what's the problem to have your super-user create their accounts then ?

Actually we don't want grant QA Manager(s) SuperUser access, and still want them to create/add user.

Also Is there any way to disable **register an account** option, since we would like to restrict ad-hoc users/bots use this to get an account and keep the user registration/creation invitation based?
