### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by sniperyi09** [kiwitcms/Kiwi#2519]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
@sniperyi09 which page triggers the problem for you? What are your steps to reproduce ?

**Comment by atodorov** [comment]
Closing due to missing information. Feel free to reopen when you can provide more details.
