### ISSUE TITLE
 Progress bars in Runs tab are not color coded

### ISSUE THREAD

**Issue by soulflyman** [kiwitcms/Kiwi#254]
### Description of problem
The progress bars in the Runs tab inside the a plan is not working. It is always monochrome and not displaying any coloured progress.

### Component (web, API, etc)
WEB

### Version or commit hash (if applicable)
Version 4.1.0 (Docker)

### How often reproducible
always

### Steps to Reproduce

1. Create Test Plan
2. Add Test Case to Test Plan
3. Create Test Run
4. Complete Test Run
5. Set Test Run to finished
6. Look at the Run tab inside the Test Plan

### Actual results
Progress bar is always grey
![2018-03-16 11_56_00-](https://user-images.githubusercontent.com/379492/37517411-a103a082-2911-11e8-88a5-a14ba070060f.png)

### Expected results
Progress bar displays different colours representing the Test Run status like inside the details view of a Test Run.
![2018-03-16 12_01_00_](https://user-images.githubusercontent.com/379492/37517541-0d2b0c32-2912-11e8-806a-163e1b0633af.png)

**Comment by atodorov** [comment]
These progressbars have been removed recently so closing.
