### ISSUE TITLE
Investigate possibility to ignore JS from cache in case of update

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#255]
### Description of problem
Several times I had an issue when updated Kiwi bits to the latest ones, my browser still used "old" cached JS file and it led to unexpected errors.  AFAIK some frameworks have some "revisioning" of js\css files and allow to explicitly tell browser to force update JS. It would be nice to have it here as well

### Component (web, API, etc)
web

### Additional info
Some of quick-googled answers, maybe will help https://stackoverflow.com/a/45338997/1657819

**Comment by atodorov** [comment]
Versioned static files are enabled by default for our downstream distribution `mrsenko/kiwi`. That said you can use the `ManifestStaticFilesStorage` from Django to configure this on the upstream distribution.

**Comment by GodfatherThe** [comment]
@atodorov  can it be enabled by default?
