### ISSUE TITLE
Publish tagged version on docker hub

### ISSUE THREAD

**Issue by nfk** [kiwitcms/Kiwi#2596]
**Is your feature request related to a problem? Please describe.**

It could be dangerous in production to use the **latest** image of the project. I did not find on [docker hub](https://hub.docker.com/r/kiwitcms/kiwi/tags) the version 10.4 of kiwi.

**Describe the solution you'd like**

Publish a public container about each kiwi stable version on docker hub.

**Describe alternatives you've considered**

Build by ourself the container and add it in our private registry.

**Additional context**
```
$ docker pull kiwitcms/kiwi:10.4
Error response from daemon: manifest for kiwitcms/kiwi:10.4 not found: manifest unknown: manifest unknown
```

**Comment by nfk** [comment]
It is a known issue, I have just seen the warning [here](https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#start-with-docker-compose). You have probably a reason about this choice.

**Comment by atodorov** [comment]
> It is a known issue, I have just seen the warning [here](https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#start-with-docker-compose). You have probably a reason about this choice.

Yes, see https://kiwitcms.org/#subscriptions. This is a WONTFIX for now.

**Comment by mqu** [comment]
I am also concerned by this issue.

**Comment by mqu** [comment]
I have created a personnal project on gitlab.com with some scripting based on gitlab-ci ; this job is run every month and can tag and push docker image with versionning:
- projet : https://gitlab.com/mqu/kiwi-tcms/
- registry : https://gitlab.com/mqu/kiwi-tcms/container_registry
- tags: registry.gitlab.com/mqu/kiwi-tcms:11.4 ; registry.gitlab.com/mqu/kiwi-tcms:latest

I am going to wait for a new release. You may ask me to become member of this project. 

TODO: remove "mqu/" in registry URL.

**Comment by mqu** [comment]
we have now nearly 1 year of tagued images here : https://gitlab.com/mqu/kiwi-tcms/container_registry

**Comment by mqu** [comment]
> we have now nearly 1 year of tagued images here : https://gitlab.com/mqu/kiwi-tcms/container_registry

this task still working, having versions from 11.4 to 13.1.1.
