### ISSUE TITLE
Timezone not setting correctly when running in Docker 

### ISSUE THREAD

**Issue by max-wa** [kiwitcms/Kiwi#2605]
Bug connected to Stackoverflow Question: [Setting Timezone in KiwiTCMS](https://stackoverflow.com/questions/69811728/setting-timezone-in-kiwitcms)

### Description of problem
We are running KiwiTCMS as a docker image and we are trying to change the timezone from UTC to Europe/Berlin. We set the localtime of the server running the containers to "Europe/Berlin". `date` also shows the correct time (e.g. `Thu Nov 18 16:07:22 CET 2021`). We then set the timezone of the database and kiwi container by adding localtime as a volume (`- /etc/localtime:/etc/localtime:ro`) to each container. This seems to work as `date` in both containers also shows the time in CET (database-container: `Thu Nov 18 16:11:29 CET 2021` and kiwi-web container: `Thu Nov 18 16:11:56 CET 2021`).

After that we tried to set the timezone inside Kiwi in the docker-compose.yml by using the environment variable `KIWI_TIME_ZONE: Europe/Berlin` mentioned in the [documentation](https://kiwitcms.readthedocs.io/en/latest/configuration.html).

This only changed the name of the timezone inside Kiwi, the time itself didn't change, so the web based clock now shows the time as follows: `Nov. 18, 2021, 3:16 p.m. Europe/Berlin` even tho its already 4:16 pm as seen in the `date` commands of the containers. The last login of each user inside the admin interface is also shown as the UTC time.

The same problem occurs when we set the python variable mentioned in the documentation directly inside our manualy created settingsfile `default_config.py`. There we set `TIME_ZONE = 'Europe/Berlin' and include the settingsfile as a volume in the docker-compose.yml as follows:
```
volumes:
    - ./my_settings_dir/default_config.py:/venv/lib64/python3.8/site-packages/tcms_settings_dir/default_config.py
```
Other settings made in that file (e.g. `AUTO_APPROVE_NEW_USERS = False`) work just fine, but the web based clock still shows the UTC time with the timezones name changed to `Europe/Berlin` as mentioned before.

### Steps to Reproduce
Since i mentioned both ways we tried to change the timezone, im going to add steps for both of them.

1.
    1. Change the localtime of the server that will run kiwitcms to `Europe/Berlin`
    2. Clone the kiwitcms repository into local filesystem
    3. Add the servers localtime as a volume to both containers
    4. Add the environment variable `KIWI_TIME_ZONE: Europe/Berlin` in the docker-compose.yml after `KIWI_DB_PASSWORD`
    5. Run `docker-compose up`
    6. Check web based clock and last user login in admin interface
2.
    1. Change the localtime of the server that will run kiwitcms to `Europe/Berlin`
    2. Clone the kiwitcms repository into local filesystem
    3. Add the servers localtime as a volume to both containers
    4. Create directory `my_settings_dir` in the directory that contains the docker-compose.yml
    5. Create the file `default_config.py` and add `TIME_ZONE = 'Europe/Berlin` as content
    6. Add the file as a volume inside the docker-compose.yml as mentioned above
    7. Run `docker-compose up`
    8. Check web based clock and last user login in admin interface

### Actual results
The name of the timezone of the web based clock changes but neither the time shown in the clock nor the time of last logins in admin panel.

### Expected results
The name of the timezone of the clock and the time itself change to the selected timezone.

**Comment by eddywu** [comment]
KIWI_USE_TZ: "True"
            KIWI_TIME_ZONE: Europe/Berlin

**Comment by max-wa** [comment]
Thank you very much for clearing things up, with `KIWI_USE_TZ: "True"` it works like it is supposed to.

Looks like we either didn't see that parameter existed or thought it was `true` by default because the comment only mentions what would happen if you set it to `false`.
