### ISSUE TITLE
Cannot access page New Test Case

### ISSUE THREAD

**Issue by Pink174** [kiwitcms/Kiwi#2613]
![image_2021_11_30T08_48_02_993Z](https://user-images.githubusercontent.com/95277818/144014821-5e144abd-6993-4f90-bf5e-7299be706428.png)
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Steps to Reproduce

1. Go to the Homepage
2. Click on to the Testing
3. Choose New Test Case

### Actual results
Message "500 Internal Server Error"

### Expected results

Show page "New Test case"

**Comment by atodorov** [comment]
There is no actionable information here.  Check-out the documentation
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#troubleshooting and extract the error logs. 

For further support questions see https://kiwitcms.org/support/ and follow the instructions.
