### ISSUE TITLE
Unable to start kiwi_web after update

### ISSUE THREAD

**Issue by thindata** [kiwitcms/Kiwi#2614]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
After updating kiwi to latest version web fails to start

### Steps to Reproduce

1.
2.
3.

### Actual results

kiwitcms/kiwi:latest         "sh -c ln -snf /usr/…"   14 minutes ago      Restarting (1) 5 seconds ago                       kiwi_web

db_1   | => sourcing 40-datadir-action.sh ...
db_1   | 2021-11-30 16:17:33 0 [Note] Using unique option prefix 'ignore-db-dir' is error-prone and can break in the future. Please use the full name 'ignore_db_dirs' instead.
db_1   | 2021-11-30 16:17:33 0 [Note] Using unique option prefix 'ignore-db-dir' is error-prone and can break in the future. Please use the full name 'ignore_db_dirs' instead.
db_1   | ---> 16:17:34     Running datadir action: upgrade-warn
db_1   | ---> 16:17:34     MySQL server version check passed, both server and data directory are version 10.3.
web_1  | ln: missing file operand
web_1  | Try 'ln --help' for more information.
web_1  | ln: missing file operand
web_1  | Try 'ln --help' for more information.
web_1  | ln: missing file operand
web_1  | Try 'ln --help' for more information.
web_1  | ln: missing file operand
web_1  | Try 'ln --help' for more information.

### Expected results
web starts

**Comment by thindata** [comment]
if i remove sh -c it works but then get

web_1  | ln: target 'web' is not a directory

**Comment by atodorov** [comment]
The startup logs for the web container look like this:

```
tcms_kiwitcms_org_web | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.802583 2021] [ssl:warn] [pid 10:tid 139808445696320] AH01909: 172.20.0.4:443:0 server certificate does NOT include an ID which matches the server name
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.806691 2021] [ssl:warn] [pid 10:tid 139808445696320] AH01909: 172.20.0.4:8443:0 server certificate does NOT include an ID which matches the server name
tcms_kiwitcms_org_web | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.921403 2021] [ssl:warn] [pid 10:tid 139808445696320] AH01909: 172.20.0.4:443:0 server certificate does NOT include an ID which matches the server name
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.922052 2021] [ssl:warn] [pid 10:tid 139808445696320] AH01909: 172.20.0.4:8443:0 server certificate does NOT include an ID which matches the server name
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.922177 2021] [lbmethod_heartbeat:notice] [pid 10:tid 139808445696320] AH02282: No slotmem from mod_heartmonitor
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.935253 2021] [mpm_event:notice] [pid 10:tid 139808445696320] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
tcms_kiwitcms_org_web | [Wed Dec 08 15:08:24.941476 2021] [core:notice] [pid 10:tid 139808445696320] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

Your logs show a `"sh -c ln -snf /usr/` command which is something that you have introduced yourself and isn't related to Kiwi TCMS. 

And as evident from the log messages there is a mistake or a typo: 
```
web_1 | ln: missing file operand
web_1 | Try 'ln --help' for more information.
```

For further support questions see https://kiwitcms.org/support/ and follow the instructions.
