### ISSUE TITLE
Unable to connect to repositories under GitLab subgroups

### ISSUE THREAD

**Issue by PDallaPiazzaEdalab** [kiwitcms/Kiwi#2643]
### Description of problem
When the depth of the repository has more than two levels, the kiwitcms is unable to communicate with GitLab

### Steps to Reproduce

1. Create a group on GitLab (G1)
2. Create a subgroup in it (G2)
3. Create a project in the subgroup (P1)
4.  Open a new issue on P1 
5. Setup the bug tracker as following:
* BASE_URL= https://gitlab.com/G1/G2/P1
* API_URL= https://gitlab.com
* username and password according to your settings
6. Health check:  https://gitlab.com/G1/G2/P1/-/issues/1

### Actual results
Two banners with failed communication (404 Can't find project) and the integration does not work 

### Expected results
It should work

### Additional info (Python traceback, logs, etc.)
I guess that the problem is in the GitlabThread class, in the repo_id method. 

`return "/".join(bug_system.base_url.strip().strip("/").split("/")[-2:])`

**Comment by rene-schoene** [comment]
I can confirm this bug, happens in the latest version of Kiwi as well.

A possible fix could be to use `urlparse`, e.g.,

```python
import urlparse

return urlparse.urlparse(bug_system.base_url).path.lstrip('/')
```
