### ISSUE TITLE
Quotes Are Not Escaped Properly on Bug Title and Test Case Title

### ISSUE THREAD

**Issue by sumargoraymond** [kiwitcms/Kiwi#2658]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
Quotes on bug or test case's title is not escaped properly.

### Steps to Reproduce

1. Create new bug/test case with quotes ""
2. Search for bugs

### Actual results
Quotes is escaped on title as &quot;

### Expected results
Quotes is escaped properly

<img width="292" alt="Screen Shot 2022-01-07 at 08 38 47" src="https://user-images.githubusercontent.com/6355510/148472533-007c9574-36b5-4ee0-ad02-3ea5de0b4fd9.png">

**Comment by atodorov** [comment]
This is working as intended. Many parts of the UI are rendered through JavaScript / JSON-RPC calls and unescaping quotes opens up the possibility for XSS attacks. Won't fix!
