### ISSUE TITLE
Test case preview is not equal to the final test display

### ISSUE THREAD

**Issue by nfk** [kiwitcms/Kiwi#2659]
### Description of problem

The engine to preview a test case and the one to display the test case view differs.  From my point of view on preview the code highlight (especially for gherkin syntax) and the markdown support looks better.

* On the public instance with the version 10.5 the version preview looks buggy to highlight the code. JS error about `prism.js`
* The bullet order restart after the code block when we display the test case while on the preview the order is honoured.

### Version or commit hash (if applicable)

v10.4

### Steps to Reproduce

1. Create a test case with a bash block like below
```
1. Have a beautiful day
2. and sun glasses
    ```bash
echo "hello world" && echo ${HOME}
    ```
3. Here an action
4. then an assertion
```
2. Look the preview of the test case
3. Save the test case

### Actual results

**preview:**
![Screenshot 2022-01-07 at 16-47-26 Kiwi TCMS - Edit TestCase](https://user-images.githubusercontent.com/662724/148569067-d5a15fff-7b7b-4b31-b76e-8ef30fcb39ac.png)

**default render**
![Screenshot 2022-01-07 at 16-47-43 Kiwi TCMS - TC-12660 test case nico about preview](https://user-images.githubusercontent.com/662724/148569058-0010f6c3-1bb9-4904-9382-1d665fa2cd3f.png)


### Expected results

![Screenshot 2022-01-07 at 16-52-02 Kiwi TCMS - Edit TestCase](https://user-images.githubusercontent.com/662724/148569573-4b494e68-b528-42bf-bef9-21ab97df40aa.png)


### Additional info (Python traceback, logs, etc.)

https://public.tenant.kiwitcms.org/case/12660/

**Comment by atodorov** [comment]
Notes: these differences are due to the 2 different rendering engines used for FE & BE. It could be resolved by rewriting the preview button to use the `Markdown.render()` RPC call. This will also simplify the editor overrides in the part and get rid of the prism.js dependency.
