### ISSUE TITLE
Searching test case - "Test plan" - Dropdown not show

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#2679]
### Description of problem
From Test Run search for adding a test case

### Version or commit hash (if applicable)
V10.5

### Steps to Reproduce
![Movie](https://user-images.githubusercontent.com/9214815/149658641-333686ce-e652-408e-ac92-c8d3a782a460.gif)

### Actual results
Drop down box not show

### Expected results
Product should be disabled too (with '-------').

### Additional info 
Workaround - After refreshing product Test plan drop down shows

**Comment by patelutpal** [comment]
@atodorov  this is a defect. We are seeing it to.
