### ISSUE TITLE
500 error when resetting password

### ISSUE THREAD

**Issue by Gareth-Lee-PBH** [kiwitcms/Kiwi#2681]
### Description of problem

In short: Reset password gives 500 error and sending a test email produces an error - my assumption is these are linked?

I recently upgraded kiwi from 10.1 to 10.5, prior to my upgrade emails from kiwi had been working.

A user tried to reset their password and was presented with a 500 error:
![image](https://user-images.githubusercontent.com/59441304/149958185-0f610a75-6d46-489d-91a6-5f6d627baf7e.png)

The first thing I checked (and one of the few things I know to check) was the sending of a test email. I got the following output:
![image](https://user-images.githubusercontent.com/59441304/149958641-468b6bc0-673d-478a-ba8d-9679f6245bec.png)

I've run kiwi with debug = true in my local_settings.py file, and checked my email settings, but I still get 500 with no more info
![image](https://user-images.githubusercontent.com/59441304/149959058-9da3ba04-9131-4460-9844-650bd8d620ae.png)

I've tried also running the docker container in the foreground but I don't see any other useful outputted that would explain why the reset password page is failing:

![image](https://user-images.githubusercontent.com/59441304/149959369-10d9afbb-3ae2-49b2-8529-a6df7998b676.png)

I have managed to reset the password using docker exec -it kiwi_web /Kiwi/manage.py changepassword USER_X

I'm not sure how to investigate this or generate any more useful logs to diagnose the issue, any advice on where to look or how to begin diagnosing this is greatly appreciated.

Thanks

**Comment by atodorov** [comment]
It looks like either your email settings are misconfigured or the SMTP server is refusing the connection. You can see that in the Python traceback the connection comes from smtplib.py. 

For troubleshooting hints see https://kiwitcms.readthedocs.io/en/latest/configuration.html#e-mail-settings
