### ISSUE TITLE
Test plan creation: version issue "Nothing selected"

### ISSUE THREAD

**Issue by kiwifanboy** [kiwitcms/Kiwi#2702]
### Steps to Reproduce

1.The following product was created for demonstration purposes:
![Selection_068](https://user-images.githubusercontent.com/98819592/151970616-d05534c0-f667-47ac-83ab-d30456a4e323.png)

2. After the product has been created, the following version was available:
![Selection_069](https://user-images.githubusercontent.com/98819592/151970774-2b168933-60ee-40fd-bf48-943cd20f246e.png)

3.When trying to create a test plan for this product, you cannot select the version:
![Selection_070](https://user-images.githubusercontent.com/98819592/151970906-79c94f0e-8359-4ea8-807c-0e7939cc1d3a.png)

4. This can be fixed by pressing the Save button, which will initially result in an error message, but will then result in all available versions for the product being selectable:
![Selection_072](https://user-images.githubusercontent.com/98819592/151971025-baa217dc-7c8e-40a6-94c6-0c7b78ce2c5a.png)

5. After the desired version has been selected, the plan can be saved using "Save".

### Actual results
Version is not selectable without the workaround described above.

### Expected results
All available versions for the product should be selectable.

**Comment by atodorov** [comment]
Created a new TP here https://public.tenant.kiwitcms.org/plan/5303/a-new-tp by selecting only the product  and writing the name, nothing else. Closing. 

Reopen when you can reproduce on https://public.tenant.kiwitcms.org and provide more information otherwise there's nothing that we can do here.
