### ISSUE TITLE
Azure Boards API interaction: Make api-version configurable

### ISSUE THREAD

**Issue by JakobD97** [kiwitcms/Kiwi#2717]
**Is your feature request related to a problem? Please describe.**
Azure DevOps-Server cannot be used with the Bug tracker integration due to the api-version.
In the Bug tracker integration with Azure DevOps the api-version 6.0 is hardcoded. If this would be configurable, also DevOps-Server (The on premise installation of AzureDevops) could be used.

**Describe the solution you'd like**
The AzureBoardsAPI class sets the api_version to "?api-version=6.0". This is fine for Azure-DevOps running on azure, but the DevOps-Server does not support this version.
The required API-Endpoints seem to be simmilar to version 5.0 so the code would work fine with version 5.0
See: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/list?view=azure-devops-server-rest-5.0 for details.

When defining the AzureBoards Bug-tracker a field to set the api-version in the ui would enable all DevOps-Server users to create bugs on their DevOps-Server installation.

**Describe alternatives you've considered**
One could also create a second AzureBoardsAPI that has api-version 5.0 and name it AzureDevopsServerBoardsAPI

**Additional context**
The functionality I am talking about was implemented in the following Issue: https://github.com/kiwitcms/Kiwi/issues/1979

**Comment by atodorov** [comment]
FTR this can also very easily be solved by providing your own Azure Boards integration class, which overrides `self.api_version` as documented in:

- https://kiwitcms.org/blog/atodorov/2020/07/11/customize-the-information-used-for-1-click-bug-reports/
- https://kiwitcms.org/blog/atodorov/2019/11/11/how-to-override-bug-details-in-kiwi-tcms/
