### ISSUE TITLE
Replace custom Build.list method with Build.objects.filter

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#272]
Not only is this custom class method useless and not necessary, but it also has a bug in it. 

It works by being passed a query dict like this: 
` query = {'param_one': 'value: one', 'param_two': 'value_two'}; Build.list(query)`

Internally it does the following: 
`if query.get('param_one'): builds.objects.filter(param_one=query['param_one']`
However, when working with booleans, if `param_one` is `False` it would never filter the objects by `param_one = False`, because `query.get('param_one')` will return `False` and it would not go into the `if` body.

This can easily be replaced by Django query with kwargs: `Builds.objects.filter(**query)`. It would do the same job, but it would not fail with booleans.

As far as `Builds` are concerned this method is used only in two places, and can easily be refactored. Also, we need to investigate whether some other model uses similar methods and refactor them too.

**Comment by atodorov** [comment]
Can you pin-point this in the code. I don't see `Build.list`, there's `Build.list_active` but it is not related to what you say in the original comment. I'm wondering if this issue is still a problem or has been resolved meanwhile.

**Comment by asankov** [comment]
It looks like it has been refactored. Closing the issue.
