### ISSUE TITLE
Plugins are not loading for KIWI tcms Web UI

### ISSUE THREAD

**Issue by venkip541** [kiwitcms/Kiwi#2729]
Hi Team,

We are exploring KIWI tcms for our organization, installed using docker compose, after logged in to dashboard plugins dropdown is showing empty. 

Is there a way how can we achieve this.

BR
Venkatesh. P

**Comment by atodorov** [comment]
> Is there a way how can we achieve this.

Yes, create and install plugins -> https://kiwitcms.readthedocs.io/en/latest/plugins/index.html
