### ISSUE TITLE
CSRF Problems since updating to 11.2

### ISSUE THREAD

**Issue by Spittal** [kiwitcms/Kiwi#2751]
### Description of problem
I've had an issue where the app has automatically pulled the 11.2 docker image— this is because Kiwi _only_ publishes a latest tag on Dockerhub which is a major pain. I would love to be able to pin a version but that isn't an option I get because of the choice to only push a single Docker tag.

The issue I'm having now with version 11.2 is that, behind a reverse proxy with the environment variable `KIWI_DONT_ENFORCE_HTTPS=true` I am now seeing the following CSRF error.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/1229177/157504160-b3ada2b4-d052-46a6-89ce-75ad8091acc0.png">

It says I should use Debug to get a trace, but I've set `DEBUG=True`, restarted the server and I don't get any additional information. The logs in stdout/stderr just show a normal access log, and provide no insight into the error.

I've attempted using the `/Kiwi/manage.py` tool to set the domain, to run migrations, among various other things. And still nothing works.

### Version or commit hash (if applicable)
11.2

### Steps to Reproduce

1. Deploy the latest Docker image with `KIWI_DONT_ENFORCE_HTTPS=true`. Behind a reverse proxy. And then attempt to use the application.

### Additional Info
It seems like I might not be the only one experiencing this issue: https://stackoverflow.com/questions/71401818/getting-csrf-verification-failed-with-kiwi-tcms-running-from-docker

**Comment by jlvgit** [comment]
I'm having the same problem, I think [this is the issue](https://docs.djangoproject.com/en/4.0/ref/settings/#csrf-trusted-origins), but I don't know how to fix it. Setting the Env variable manually didn't seem to do anything.

**Comment by atodorov** [comment]
This is not a support channel as indicated on https://kiwitcms.org/support/ and https://github.com/kiwitcms/Kiwi/issues/new/choose. Follow up on the original thread on StackOverflow.
