### ISSUE TITLE
Update django-modern-rpc to 1.0

### ISSUE THREAD

**Issue by alorence** [kiwitcms/Kiwi#2795]
Hello,

As the main developer of django-modern-rpc, I would like to know if you had a chance to test the alpha of future 1.0.0 version. Since this milestone is a pretty important refactoring of the library, and considering Kiwi is the most important project depending on django-modern-rpc, I prefere to contact you to ensure averything works as expected with the new version before publishing it as stable release.

If you have a few time, can you update from django-modern-rpc 0.12.1 to 1.0.0a2 and check with your system that nothing has been broken ?

Best regards,

**Comment by atodorov** [comment]
Thanks for reaching out. 

Do you mind opening a PR which updates django-modern-rpc version in `requirements/base.txt` so we can see if/what will breaks. Afterwards I can try it out manually as well b/c the existing automation doesn't cover the JSON-RPC protocol endpoint. Only the XML-RPC one.

**Comment by alorence** [comment]
I just opened #2796 as a starting point for the checks.

Testing only XML-RPC endpoint is a good starting point as django-modern-rpc has a strong test coverage that try to perform the same tests for both protocols (as long as this is possible).

Let's see if something is broken with current tests, and maybe we coult consider adding more tests for JSON-RPC endoints
