### ISSUE TITLE
Configuration setting to disable unsecure connection warning when running behind a SSL enabled proxy

### ISSUE THREAD

**Issue by sorin25** [kiwitcms/Kiwi#2806]
**Is your feature request related to a problem? Please describe.**
I have to run kiwi on a system shared with multiple other tools. The frontend is a apache that is configured with SSL and uses mod_proxy + mod_proxy_html to forward requests to kiwi running in docker. I would like to run kiwi in http mode, because there is no point of having ssl both on proxy and 

**Describe the solution you'd like**
the ideal solution would be to get rid of the warning, anyone savvy enough to set `KIWI_DONT_ENFORCE_HTTPS=true` can be trusted to know the possible issues. 
But if that is not acceptable, at least an additional environment variable `I_DONT_KNOW_NAMING_IS_HARD`  which when set to true would hide the warning.

**Describe alternatives you've considered**
running SSL both on the proxy and the docker container, but that is resource intensive

**Additional context**
![image](https://user-images.githubusercontent.com/2103887/172678983-ad9a9435-e5f1-40d6-9492-c1e3a289530c.png)

**Comment by atodorov** [comment]
> anyone savvy enough to set `KIWI_DONT_ENFORCE_HTTPS=true` can be trusted to know the possible issues.

I disagree. We've seen horendous things just out there over the web. There are people savvy enough to disable HTTPS and run Kiwi TCMS on the wild web over plain/text. 

>  running SSL both on the proxy and the docker container, but that is resource intensive

Do you have any actual data to back this up? We're running all our containers in production with SSL enabled across the board and haven't experienced any resource related issues. If you do have the actual data please share it so we can compare. 

To answer your original question: Your Apache proxy isn't configured properly to let Kiwi TCMS know that it is running over a secure connection at the front, see
https://github.com/django/django/blob/main/django/http/request.py#L252
https://docs.djangoproject.com/en/4.0/ref/settings/#secure-proxy-ssl-header

**Comment by sorin25** [comment]
> Do you have any actual data to back this up? We're running all our containers in production with SSL enabled across the board and haven't experienced any resource related issues. If you do have the actual data please share it so we can compare.

So you are basically saying that I have to prove to you that 1+1 > 1 ?

**Comment by sorin25** [comment]
For anyone having the same issue, note that [SECURE_PROXY_SSL_HEADER](https://docs.djangoproject.com/en/4.0/ref/settings/#secure-proxy-ssl-header) is none by default and you have to use the approach described at https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#customization to set it (@atodorov is there is a better way ?)

As for adding the header in apache:
`RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}`
(and enable mod_headers)

hth

**Comment by atodorov** [comment]
>  (@atodorov is there is a better way ?)

Don't disable HTTPS. You gain nothing by doing that.

**Comment by sorin25** [comment]
> Don't disable HTTPS. You gain nothing by doing that.
LOL, way to condescend your users, you know better. I'm amazed how this project succeeded so far!
