### ISSUE TITLE
feature request: rpc method to return all tags associated to test case

### ISSUE THREAD

**Issue by bhashagemini** [kiwitcms/Kiwi#2808]
I am using pytest markers to tag my test cases.  I do not see a way to get all of the associated tags with a test case currently.

This would be useful to have so that I can apply an update to the test case to remove any tags that are no longer applicable.

**Comment by atodorov** [comment]
It's `Tags.filter(case=12345)`. Same method but different lookups, https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.html#how-does-the-rpc-interface-work
