### ISSUE TITLE
Special symbols in product name cause search failure

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#283]
Actually it's the same as #78 but for different field

### Description of problem
Looks like special symbols in Test Plan - Product field are not being escaped properly

### Component (web, API, etc)
web

### How often reproducible
Always

### Steps to Reproduce

1. Create product with "\\" symbols in the name i.e. "Test Product with Windows\Chrome"
2. Create a Test Plan with this product
2. Try to search this test plan (jsut search for all test plans)
3. Make sure error will appear (testplans_table)
![image](https://user-images.githubusercontent.com/918446/32109495-2d3ebfa0-bb35-11e7-9719-daf872898724.png)

### Actual results
Error appears

### Expected results
Test plan should be found

### Additional info
Maybe the same error exists for other fields as well

**Comment by atodorov** [comment]
This is dealth with in https://github.com/kiwitcms/Kiwi/pull/499/commits/ca3e119d1a96a1e5402c65b11f857a7611515353 together with redesigning this page.
