### ISSUE TITLE
Reporting a bug to Jira on click creates an issue type sub-task

### ISSUE THREAD

**Issue by vuxile-1991** [kiwitcms/Kiwi#2833]
### Description of problem
When I try to report a bug to integrated bug tools in the test executions, 
Jira in my case, after clicking on the button "Report bug", it opens 
a Jira page for creating a new issue with a type issue sub-task.

### Version or commit hash (if applicable)
11.3

### Steps to Reproduce

1. Open a running test execution
2. Click the dropdown button on the right side of the test case displayed as three dots positioned vertically
3. Select Report bug
4. Expand the Issue Tracker dropdown 
5. Select Jira as an integrated bug tool
6. Click on the button "Report bug"

### Actual results
The Jira page is opened in a new tab with an already defined issue type, which is a subtask.

### Expected results
The Jira page should be opened in a new tab with an already defined issue type, which is a bug.

**Comment by atodorov** [comment]
The fact that "sub-task" is selected means that RPC works. 

The Jira integration code will search for an issue type "Bug" and if not found it will default to the first one which is probably what's happening. Make sure "Bug" issue type exists.

Starting with v11.4 it will be possible to override this behavior, see https://kiwitcms.readthedocs.io/en/latest/modules/tcms.issuetracker.types.html#tcms.issuetracker.types.JIRA.get_issue_type_from_jira
