### ISSUE TITLE
Getting this error when clicking on any tests plans

### ISSUE THREAD

**Issue by gabrielpvbw** [kiwitcms/Kiwi#2874]
### Description of problem
database error when clicking on tests plans to see the detail of each test plan. What's db version is recommended to use ? I am current using aws Aurora MySQL

### Version or commit hash (if applicable)
kiwi latest version from docker hub
5.6.mysql_aurora.1.22.2

### Steps to Reproduce

1.
2.
3.

### Additional info (Python traceback, logs, etc.)
![image](https://user-images.githubusercontent.com/100797215/182931179-80e08154-24fe-4774-adaa-5a035e45d095.png)

**Comment by gabrielpvbw** [comment]
![image](https://user-images.githubusercontent.com/100797215/182952767-9ea4ed79-c99a-4fc0-b7b1-f235a1c879f0.png)

**Comment by atodorov** [comment]
From https://kiwitcms.org/features/:

Database engine:
 MariaDB >= 10.2.2
 MySQL >= 8.0, *running without ONLY_FULL_GROUP_BY*

This limitation is imposed by https://github.com/matthiask/django-tree-queries/#django-tree-queries
