### ISSUE TITLE
Add possibility to create "link-only" bug tracker

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#289]
At the moment "Bug tracker type" field is required when creating a new bug tracker in Kiwi. But my BT is not in the list and I don't want any API-related functionality, I'm fine with only having regexp-based links to issues. 
As a workaround I can select any of existing BT types, but it looks ugly, please add possibility to select nothing.

### Additional info:
Probably it will affect reporting because in geports generation there is unconditional assumption that bug has not null bug system

**Comment by atodorov** [comment]
CC @na-Itms.

FYI this should land early next week.
