### ISSUE TITLE
Kiwi Upgrde Static content  - browser cache issue.

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#2896]
**You can use** - https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage

**Also discribe here** -
https://forum.djangoproject.com/t/override-cached-static-files-on-browser-as-it-is-updated-on-the-server/12350/7

**_Workaround For Now_**:
https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

_Originally posted by @NirBY in https://github.com/kiwitcms/Kiwi/issues/2711#issuecomment-1221299202_

**Comment by atodorov** [comment]
> **You can use** - https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage

You can also configure your settings for that if you want to use it.
