### ISSUE TITLE
Refactor TCMSLog

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#292]
`TCMSLog` is a simple class used for logs. However, it is filled with smelly code and too complex logic for its simple task. Two class attributes `self.who` and `self.action` are defined outside of the `__init__` method, and used in other class methods. However, since they are defined outside of the constructor, we need checks whether they have been instantiated. 

The class does one thing - it makes logs. So the `make` method calls `get_new_log_object` which itself calls `get_log_create_data`. The `self.who` and `self.action` parameters are instantiated at the `make` method and used in the other two methods. IMO they don't have to be class attributes, but rather method parameter passed from one method to another.

Also, the class is not tested, so tests need to be added as well.

**Comment by atodorov** [comment]
Adding tests for this class is not the way to go here. We need to have a complete history/version logging machinery that will work automatically behind the scenes. Something like django papertrail. 

Then remove TCMSLog and related classes/models and the current history logging capabilities.

**Comment by atodorov** [comment]
This model has been deleted.
