### ISSUE TITLE
RFE: Make it possible to track all changes to models (aka history)

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#294]
At the moment it is not possible to track all changes to models.

There's a very poor history capabilities implemented but nothing like django papertrail. 
OTOH there's also action logging implemented in some cases but it is still inconsistent and needs to be invoked manually before it records anything into the database.

So figure out how to implement this and we can resolve tons of related issues, see:

#216 and #292

**Comment by okainov** [comment]
Looks like it could be easily doable by replacing post_save to pre_save signal. In pre_save you can get object instance and compare it to kwargs["instance"].

**Comment by atodorov** [comment]
looks like tracking changes with FieldTracker could be done easily and is generic enough that it can replace our home grown object History views:
http://django-model-utils.readthedocs.io/en/latest/utilities.html#field-tracker

I will investigate more.

**Comment by atodorov** [comment]
https://django-simple-history.readthedocs.io/ also looks promising
