### ISSUE TITLE
Executions on Test Case

### ISSUE THREAD

**Issue by linked-kiwi** [kiwitcms/Kiwi#2968]
### Description of problem

I loaded a Test Plan with four test cases, created a test run and selected the first of my Test Cases.  I then initiated an execution. I then marked the execution as Passed, and closed the Test Run.  When I look at the Test Case, under >>Executions it shows a link to TP-1: <my test plan>.  It also has TP-1 under Test Plans below in the lower right.

### Version or commit hash (if applicable)
11.5

### Steps to Reproduce

As above

### Actual results

TP-1 showing under >>Executions

### Expected results

TE-1 showing under executions

### Additional info (Python traceback, logs, etc.)

![tcissue](https://user-images.githubusercontent.com/111942740/199628330-8ae927ec-fdfc-4db4-bafa-d9aef661c564.png)

**Comment by atodorov** [comment]
What happens if you click on the arrow icon? Does the row `TP-1: SSH Access Control` expand ? 

It should look something like this:
![image](https://user-images.githubusercontent.com/1002300/200292538-c27e3862-d903-45aa-b1e8-86ca3c3ee811.png)

See https://public.tenant.kiwitcms.org/case/14660/

**Comment by linked-kiwi** [comment]
Hi Alexander

 

Ahhhhh…..my bad.   Indeed it does, thank you.  I had clicked on TP-1 but not tried expanding it. 

 

Just as an FYI, my testing was to get screen shots for the course we are developing at Offensive Security.  This has been written but is still going through the editing process before we release it.   I still have a note to let you know when this is released. KiwiTCMS is the primary tool we are using to explain the use of documenting testing, and it works really well.

 

I am also working with the Kali development team on developing a Kali defensive platform that we can provide as free-to-use, as we do with the Kali offensive platform. I expect to include KiwiTCMS in that, and tomorrow I’ll be running a workshop for the lecturers in the Australian Certificate IV in Cybersecurity community so that they can include it in their training courses throughout Australia. I ama big fan of KiwiTCMS!

 

Regards

 

Malcolm
