### ISSUE TITLE
Investigate CsrfDisableMiddleware

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#297]
This middleware negates the Django CSRF mechanism, so we need to consider if it is a good idea to leave it as it is, or it is better to remove it.

Also, it extends a class that is soon to be deprecated.

**Comment by atodorov** [comment]
Notes:
- see comments in latest commits referencing this issue.
- the majority of these AJAX call are from the TP page
- remaining 2 are from TR page
- JSON-RPC also uses ajax/POST - needs testing with update/create methods which perform form validation and where the underlying form is both ModelForm or just a generic form, defined by hand.

**Comment by atodorov** [comment]
Note: also needs testing by hand b/c some forms don't appear to have csrf_token (e.g. testcases/modify.html) but autotests disable the standard check for ease of use.
