### ISSUE TITLE
API to create & query Environment objects via XML-RPC

### ISSUE THREAD

**Issue by alexiade** [kiwitcms/Kiwi#3034]
https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.environment.html is an api for editing environment properties. But nowhere can I find the RPC API for creating and searching environments...

**Comment by atodorov** [comment]
> But nowhere can I find the RPC API for creating and searching environments...

Such API methods don't exist b/c they have not been necessary up to now. Converting this issue into a feature request.

**Comment by alexiade** [comment]
In case you are wondering why I need it - I have several test utilities that are quite often executed on developers local environments. I want to automatically create any such environments and collect test result information for all runs with appropriate environment information added.
