### ISSUE TITLE
Gitlab bug tracker self-signed certificate problem with gitlab in local environment

### ISSUE THREAD

**Issue by LorisArne** [kiwitcms/Kiwi#3050]
Hi,

i have a gitlab installed in local environment (so, not exposed in internet) with a self signed certificate, when i try to submit a bug using the gitlab bug tracker i receive an error, could you help me please?

I tried use both ip and FQN in the configuration of the bug tracker.

![Immagine 2023-01-26 093903](https://user-images.githubusercontent.com/45354311/214792059-9f2e0fa2-3783-49db-9659-c450e3d1593b.png)

**Comment by atodorov** [comment]
This is working as expected. By default Python will complain if it can't verify the SSL certificate of an https connection, like in this case. This is outside of scope of Kiwi TCMS.
