### ISSUE TITLE
API for creating (not updating) TestExecutions

### ISSUE THREAD

**Issue by alexiade** [kiwitcms/Kiwi#3067]
To my utter surprise I find that it is impossible to create test executions using the RPC API, similar to prior issue with environments.

As stated here - Update is available, but not execution creation. https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.testexecution.html

This is such a surprise primarily because KiwiTCMS has a "plugin" for collecting robot framework run results that uses RPC... As execution is only object where you can indicate status... I'm a bit confused what it does if not this... If someone can enlighten me how the test result collection facilities are supposed to be used if I am trying to do something illogical, id appreciate it. Because I am clearly doing something nobody else has attempted before.

What I am trying to do is making various home brew testing utilities that run at developers machines and CI machines to report the results automatically to a central location. Sounds like very much something that TCMS could be of use for...

**Comment by atodorov** [comment]
https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.testrun.html#tcms.rpc.api.testrun.add_case

**Comment by alexiade** [comment]
@atodorov I do not understand.... Could you provide some explanation how this is supposed to work? Execution has a key for run... Adding a case to run will automatically create an execution? Or? 

I absolutely do not understand how TestPlan, TestCase, TestRun and TestExecution are interlinked or supposed to be used.

**Comment by atodorov** [comment]
> I absolutely do not understand how TestPlan, TestCase, TestRun and TestExecution are interlinked or supposed to be used.

Then you should start from here before trying to guess what any of the API methods does:
https://kiwitcms.readthedocs.io/en/latest/guide/introduction.html#data-organization-within-kiwi-tcms

**Comment by alexiade** [comment]
@atodorov I read that. I also tried to read https://kiwitcms.readthedocs.io/en/latest/db.html#db, but the pictures are too low resolution to actually see so I mapped out my understanding based on reading FK definitions in API source code.  None of it helped. I can see how the foreign keys run but there are so many seemingly optional double linkages that none of it links to a sensible API usage flow.

Up to and including  creating test cases, it makes sense. Then I get lost as to what needs to happen. 

Plan has no FK-s to either case or run and has only information about the version in question.

Run has reference to plan. A mandatory one, but no status and no case references.

Execution has the status and the linkage to the case, but NO linkage to plan and reference to run is optional.

So pretty please, can you hint an API call usage flow that allows for all of these to be created sensibly with dependencies resolved? Because by shortness of your answers you assume it is something obvious or deductible from data model. It is unfortunately not the case...

**Comment by alexiade** [comment]
(the images in ER diagram are browser scaled apparently so if you pop them out, you can read them... It's still not helping... It's like being given a road map when what you need is the bus schedule)

**Comment by alexiade** [comment]
Trying to parse this apart this here to spare some next poor soul the confusion...

RPC TestRun.add_case(run_id, case_id)
Add a TestCase to the selected test run.

Returns:	
A list of serialized tcms.testruns.models.TestExecution objects

So, as there is no way of creating an execution with data in the API and you claim this does it am I to assume that an EMPTY Execution object, without expecting any values to be added is created by this call and returned as one member of this list? and if I execute the same case 4 times, I add it 4 times and every time the list grows?

Okay... A LIST of Test Execution objects is returned, presumably all the ones relating to this case, by reading source? How to I know which of them is the current/last one? The one I just created? The test utility in some cases executes multithreaded... So, what Execution ID in this list is mine to update with the actual run information?

**Comment by alexiade** [comment]
I have generally found the API to be reasonable and consistent. Up to this point. The data model is without any limitation of having multiple executions of the same case in the same run and yet the API forces it in a rather odd way and to make it even weirder by breaking an established API patten of having a create and an update for all other objects just for execution. 

A sensible API flow for this would be 
# Create Run (or select already created one) referencing a plan
# Create an execution for a case when execution starts
# Add it to the run
# Update when it completes

But that is not how it works... steps 3 and 4 a squashed into a shorthand that eliminates the possibility of reusing a case in the same run...

Why this is a bit of an issue for me - some of the tests that I'm collecting results are concurrency tests. Same test case is executed in parallel with the same run. This limitation means a lot of workarounds for me to log any sensible result from them.

So I would say that my my feature request in fact is not really done... But I guess the existence of that shorthand implies that despite what data model allows someone along the way decided not to support multiple executions of the same case and then this becomes from mere API change to a functionality change that has implications elsewhere... And that makes developers grumpy usually at least in equal measure to me being now grumpy having to work around this limitation.
