### ISSUE TITLE
Uploads in Test Case Editor are stored in uploads/attachments/auth_user/

### ISSUE THREAD

**Issue by lmoellendorf** [kiwitcms/Kiwi#3103]
### Description of problem

When editing a test case and using the "Attach File" dialog of the editor, the attachment is uploaded to `uploads/attachments/auth_user/<uid>/<attachment>`

If the Test Case is in readonly mode and the "Upload attachment:" in lower right corner is used. The attachment is stored to  `uploads/tenant/public/attachments/testcases_testcase/<uid>/<attachment>`. 

Please have a look at https://public.tenant.kiwitcms.org/case/17688/

You will find 3 attachments:

https://public.tenant.kiwitcms.org/uploads/tenant/public/attachments/auth_user/14123/cfg.tml
https://public.tenant.kiwitcms.org/uploads/tenant/public/attachments/auth_user/14123/cfg_UnwYlXv.tml
https://public.tenant.kiwitcms.org/uploads/tenant/public/attachments/testcases_testcase/17688/cfg.tml

Our use case is to have a file named `cfg.tml`  attached to multiple test cases. As it is implemented now, this is only possible via the "Upload attachment:" dialog in readonly mode. 

### Steps to Reproduce

1. Create a test case
2. In test case editor upload file via "Attach File" dialog
3. Create another test case
4. In test case editor upload file with same name as in 2)  via "Attach File" dialog

### Actual results

File in step 4) is stored to a user specific directory and therefore renamed to avoid file collision.

### Expected results

Files in step 2) and 4) should be stored in a test case specific directory to support attaching files with same name to multiple test cases.

**Comment by atodorov** [comment]
This is working exactly as it was designed. There is no issue here.

The text editor doesn't know anything about other objects other than the currently logged in user. In some cases, e.g. creating a new test case there's no object to attach files to so the only sensible default is to attach to the logged in user. 

Upon saving a record Kiwi TCMS will make a best effort to move the files uploaded under the currently logged in user under the record that was just saved. This may or may not work in all situations. Regardless images and files uploaded via the text editor will still be available as markdown links or rendered in-place.
