### ISSUE TITLE
500 internal server error all the time

### ISSUE THREAD

**Issue by diviatrix** [kiwitcms/Kiwi#314]
### Component (web, API, etc)
Core

### Version or commit hash (if applicable)
4.14 (Latest)

### How often reproducible
Every time

### Steps to Reproduce

1. docker pull kiwitcms/kiwi
2. docker-compose up 

### Actual results
App launches but every time error 500. 
Debug: true wont help.

### Expected results
It works

### Additional info

Also, setting up Debug to True does nothing. Do not know why, maybe `/tcms/settings/product.py` is a wrong place?

![image](https://user-images.githubusercontent.com/1908948/38741948-ded77ac6-3f43-11e8-9b7e-68672d3981ba.png)

![image](https://user-images.githubusercontent.com/1908948/38741969-eb4f7d3a-3f43-11e8-88b0-1474b40bbb14.png)

![image](https://user-images.githubusercontent.com/1908948/38742270-c1fc191a-3f44-11e8-9fc8-b67abca32ab1.png)

**Comment by diviatrix** [comment]
Is there any way to disable SSL?
Is there any way to make it work, but not to pay you instantly? I just want to test if it suits us, Locally.
Is there possibility that manual will be more clear any day?

**Comment by atodorov** [comment]
Please describe all the actions that you did when setting up Kiwi. It sounds like you have not executed all of the setup steps and something is missing.

Also post the httpd logs stored on the host because without them I can't see what's wrong with your environment.
