### ISSUE TITLE
use a package manager

### ISSUE THREAD

**Issue by danieleades** [kiwitcms/Kiwi#3144]
Is there any appetite for migrating to a modern package manager such as [Poetry](https://python-poetry.org/)?

This would also include migrating from `setup.py` to `pyproject.toml`.

The latter change can be done without moving to Poetry, though it probably makes sense to consider them together.

**Comment by atodorov** [comment]
> Is there any appetite for migrating to a modern package manager such as [Poetry](https://python-poetry.org/)?

What does Poetry bring to the table which is an improvement over pip ? 

> This would also include migrating from setup.py to pyproject.toml.

Same question here. I'm not familiar with `pyproject.toml` and what could be the benefits of this.

**Comment by danieleades** [comment]
Compared to Pip, Poetry-

- improves developer experience by abstracting and managing the virtual environment
- does smart semver-aware dependency solving
- provides repeatable builds by pinning transitive dependencies
- provides a bunch of utility methods for managing dependencies, running scripts, publishing packages, etc.

Pyproject.toml is the modern, declarative alternative to setup.py.
Poetry requires a pyproject.toml file (though Pip supports it as well)

**Comment by atodorov** [comment]
Thanks for the explanation above however none of the arguments are issues which we've seen to affect Kiwi TCMS (or affect it strongly enough to warrant a change). pip is working well for us at the moment. 

Closed. Wontfix.
