### ISSUE TITLE
Erratic check box placement in the "Automated" section of "New Test Case"

### ISSUE THREAD

**Issue by KiraResari** [kiwitcms/Kiwi#315]
### Description of problem
When  creating a new test case, the check boxes in the "Automated" section are arranged erratically and it is somewhat confusing which checkbox belongs with which option.

![2018-04-13 kitecms automatisation selection bug](https://user-images.githubusercontent.com/28697173/38784618-78be7b1e-414f-11e8-814e-c3798ab18597.png)

### Component (web, API, etc)
Kiwi TeCMS web portal

### Version or commit hash (if applicable)
4.1.3

### How often reproducible
100%

### Steps to Reproduce
1. Click on "New Test Case" (either from the NavBar: Testing > New Test Case or inside a Test Plan: Case > Write new case

### Actual results
The check boxes in the "Automated" section are arranged erratically and it is somewhat confusing which checkbox belongs with which option.

![2018-04-13 kitecms automatisation selection bug](https://user-images.githubusercontent.com/28697173/38784618-78be7b1e-414f-11e8-814e-c3798ab18597.png)

### Expected results
That the checkboxes are arranged in a way that looks intentional and makes it clear beyond a doubt which checkbox belongs to which option

### Additional info
We're using FireFox 59.0.2

**Comment by Prome88** [comment]
Same here, regardless of browser (tested in latest Chrome, Opera, Firefox).

**Comment by atodorov** [comment]
Will be resolved by the redesign of this page which is handled by @asankov

**Comment by atodorov** [comment]
This has been fixed with the redesign of this page. Closing.
