### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by danieleades** [kiwitcms/Kiwi#3159]
All PRs are currently failing due to broken CI. Makes it a little challenging to get good feedback on PRs.

**Comment by atodorov** [comment]
This is not true. I see you have one PR for which test executions were not approved.

**Comment by danieleades** [comment]
> This is not true. I see you have one PR for which test executions were not approved.

one of the worflows not requiring approval is showing a 'failed' status. [This one](https://scrutinizer-ci.com/g/kiwitcms/Kiwi/inspections/6dad3285-4f2b-40e0-9990-cc567356b6d8) to be specific.

If it was just a matter of approval, I would expect the PR to have an orange indeterminate status, not a failed status.
