### ISSUE TITLE
Expansion Arrow fix for Test Plan

### ISSUE THREAD

**Issue by patelutpal** [kiwitcms/Kiwi#3163]
### Description of problem
The expansion arrow for nested test plans needs to be fixed. The direction of the  arrows should be the same when the Test Plans are NOT EXPANDED.
![image](https://user-images.githubusercontent.com/95658656/231216902-919e3ecf-b2e0-4e30-9eff-aa561ba55c66.png)

**Comment by atodorov** [comment]
This seems to be the test plan tree widget on the Test Plan page (right corner). However I can't reproduce. The arrows seem to be rendered in the correct orientation depending on whether the child items are expanded or not. If a child item doesn't have any children of its own then there is no arrow icon shown. 


https://public.tenant.kiwitcms.org/plan/7285/parent-test-plan
![image](https://user-images.githubusercontent.com/1002300/232307544-b09fecbb-b431-4814-9bbf-7f3b5b8b9eab.png)

https://public.tenant.kiwitcms.org/plan/7288/another-parent-tp
![image](https://user-images.githubusercontent.com/1002300/232307569-f5ce5e94-8567-415a-baa3-34f9b25dd3be.png)


Please provide more detailed steps to reproduce, which page it is, information about the relationships between all test plans on this page and what's the current state of expanded/collapsed entries.

**Comment by patelutpal** [comment]
@atodorov  Here is a more detailed screenshot.
![image](https://user-images.githubusercontent.com/95658656/232553515-903089fc-d42a-43fb-b841-cfa5c8fc6f60.png)
I hope this helps.
