### ISSUE TITLE
Handle form validation in testruns.view.get_all

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#318]
`get_all` is the method that gets all test runs from the database and displays them to the user. 

Internally, after getting the results from the DB it populated the form and calls `form.is_valid()` to check whether there are any errors. However, the result from `is_valid` is not used anywhere, so even if there are errors they would go to the user unhandled.

**Comment by atodorov** [comment]
`get_all` has been removed as part of
https://github.com/kiwitcms/Kiwi/pull/497/commits/c29993ac75c85da264655bac24bb3f982fbc7f6f
