### ISSUE TITLE
cant login 

### ISSUE THREAD

**Issue by Shakteswar** [kiwitcms/Kiwi#3216]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Steps to Reproduce

1. go to login
2. put in my username and password
3. click login

### Actual results
says incorrect id or password

### Expected results
should log me in

### Additional info (Python traceback, logs, etc.)
when i try to reset my password it asks for gmail. But even after submitting my registered mail ( greatshak.freefire@gmail.com) it doesnt send any mail to reset password

**Comment by atodorov** [comment]
There is no account registered with address `greatshak.freefire@gmail.com`. 

If there was such an account in the past it has been removed due to inactivity according to our privacy policy described at https://kiwitcms.org/legal/

**Comment by Shakteswar** [comment]
But it says account registered with this mail

**Comment by Shakteswar** [comment]
Hi sorry for the issue
 It was problem at my end it's fixed now. Thanks for your help
