### ISSUE TITLE
suggestion to develop Chinese version

### ISSUE THREAD

**Issue by mahaixue** [kiwitcms/Kiwi#324]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
hello,is it impossible  to develop Chinese version.

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
You can contribute Chinese translations. See the docs for more info on how to do this:
http://kiwitcms.readthedocs.io/en/latest/contribution.html#translation

The core Kiwi TCMS doesn't speak Chinese so we can't do this for you.
