### ISSUE TITLE
Feature Request: Enable adding video to test case

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#326]
Would it be possible to integrate (add Insert video button) the installed [Media plugin ](https://www.tinymce.com/docs-3x/reference/plugins/Plugin3x@media/) from TinyMCE 3.5.11 into the Test case editor to enable adding of video materials?

Could you also point out where we can set the maximum allowed filesize for attachment upload?

**Comment by atodorov** [comment]
> Could you also point out where we can set the maximum allowed filesize for attachment upload?

Configure FILE_UPLOAD_MAX_SIZE, see:
http://kiwitcms.readthedocs.io/en/latest/configuration.html

**Comment by atodorov** [comment]
Closing as WONTFIX. This requires lots of customizations on the text editor side as well as custom Markdown format because Markdown doesn't have a native syntax for displaying inline videos (like it does for images). 

As a workaround add the video as an attachment.
