### ISSUE TITLE
Unable to Upload Large Files despite Increasing FILE_UPLOAD_MAX_SIZE

### ISSUE THREAD

**Issue by McRx71** [kiwitcms/Kiwi#3262]
### Description:
We encountered an issue while attempting to increase the maximum file upload size (**FILE_UPLOAD_MAX_SIZE**) for larger files in our project. Despite adjusting the parameter to a higher value, we were unable to successfully upload files larger than 2MB. This is perplexing since the default **FILE_UPLOAD_MAX_SIZE** is set to 5MB.

### Steps to Reproduce:

1. Attempt to upload a file larger than 2MB.
2. Observe that the file upload fails.

### Expected Behavior:
The file upload should succeed for files larger than 2MB, as the **FILE_UPLOAD_MAX_SIZE** parameter was increased.

### Actual Behavior:
The file upload fails, indicating that the increased **FILE_UPLOAD_MAX_SIZE** value is not being recognized.

### Troubleshooting and Solution:

1. We referred to the [Django Documentation](https://docs.djangoproject.com/en/2.1/ref/settings/#data-upload-max-memory-size) to investigate the issue further.
3. After reviewing the documentation, we discovered that the correct variable to configure for managing file upload size is **DATA_UPLOAD_MAX_MEMORY_SIZE**, not **FILE_UPLOAD_MAX_SIZE**.
4. We replaced **FILE_UPLOAD_MAX_SIZE** with **DATA_UPLOAD_MAX_MEMORY_SIZE** in the configuration.
5. Following this adjustment, we were able to successfully upload larger files without any issues.

### Additional Feedback:
We found it frustrating that it was not immediately apparent where to change the settings for the Nginx configuration within the Docker container. It would be helpful if this information were documented in a more accessible location, such as the **common.py** file, rather than solely in the **/Kiwi/etc/nginx.conf** file.

### Screenshot:
![grafik](https://github.com/kiwitcms/Kiwi/assets/50086322/69d70fb2-e13d-47db-affa-da663f35de32)

Thank you for your attention to this matter. We hope this report assists in improving the project's documentation and helps resolve the issue with file uploads.

**Comment by atodorov** [comment]
> ### Description:
> 
> We encountered an issue while attempting to increase the maximum file upload size (**FILE_UPLOAD_MAX_SIZE**) for larger files in our project. Despite adjusting the parameter to a higher value, we were unable to successfully upload files larger than 2MB. This is perplexing since the default **FILE_UPLOAD_MAX_SIZE** is set to 5MB.
> ### Steps to Reproduce:
> 
>     1. Attempt to upload a file larger than 2MB.
> 
>     2. Observe that the file upload fails.
> 

Can you specify exactly what failure do you see? 

Are you seeing an error message `File exceeds maximum size of 5.0 MB` or are you seeing `HttpBadRequest (status_code=400)` response ? 


FTR I am not able to reproduce with v12.7, see https://public.tenant.kiwitcms.org/plan/8530/testing-maximum-file-upload-size. I was able to upload two files which are exactly 5MiB large:

```
-rw-r--r--. 1 atodorov atodorov 5242880 Dec  4 22:40 large-file.txt
-rw-r--r--. 1 atodorov atodorov 5242880 Dec  4 22:28 large-file.zero
```

Trying with a file which is 1 byte larger:
```
-rw-r--r--. 1 atodorov atodorov 5242881 Dec  4 22:44 large-file.log
```
results in the `File exceeds maximum size of 5.0 MB` error message as expected.





> 
> ### Expected Behavior:
> 
> The file upload should succeed for files larger than 2MB, as the **FILE_UPLOAD_MAX_SIZE** parameter was increased.
> ### Actual Behavior:
> 
> The file upload fails, indicating that the increased **FILE_UPLOAD_MAX_SIZE** value is not being recognized.
> ### Troubleshooting and Solution:
> 
>     1. We referred to the [Django Documentation](https://docs.djangoproject.com/en/2.1/ref/settings/#data-upload-max-memory-size) to investigate the issue further.
> 
>     2. After reviewing the documentation, we discovered that the correct variable to configure for managing file upload size is **DATA_UPLOAD_MAX_MEMORY_SIZE**, not **FILE_UPLOAD_MAX_SIZE**.
> 

Indeed Django's configuration variable is **DATA_UPLOAD_MAX_MEMORY_SIZE**. **FILE_UPLOAD_MAX_SIZE** is the configuration for the django-attachments library which handles uploaded files.

**Comment by atodorov** [comment]
> * We replaced **FILE_UPLOAD_MAX_SIZE** with **DATA_UPLOAD_MAX_MEMORY_SIZE** in the configuration.
> 
> * Following this adjustment, we were able to successfully upload larger files without any issues.

Django's own [source code](https://github.com/django/django/blob/main/django/core/exceptions.py#L79-L85) says:

```
class RequestDataTooBig(SuspiciousOperation):
    """
    The size of the request (excluding any file uploads) exceeded
    settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
    """
```


So this change doesn't sound like it has any effect. Maybe it was something else which made it possible for you to upload larger files but it's highly unlikely it was adjusting the `DATA_UPLOAD_MAX_MEMORY_SIZE` setting.
