### ISSUE TITLE
Tagged release for Docker images

### ISSUE THREAD

**Issue by winterheart** [kiwitcms/Kiwi#3273]
**Is your feature request related to a problem? Please describe.**
Currently there no tagged releases for Docker images, and users may only use `latest` tag. Because of this we can't create fully reproducible environment for testing/prod sites without tagging images manually in local cache.

**Describe the solution you'd like**
Please add tagged releases on Docker Hub and Quay to resolve this issue.

**Comment by atodorov** [comment]
Tagged releases are available only to subscribers, see https://kiwitcms.org/#subscriptions.
