### ISSUE TITLE
No notification mail when updating Test case

### ISSUE THREAD

**Issue by vdsonw** [kiwitcms/Kiwi#3274]
### Description of problem
Test email (sendtestemail) works, but when modifying test case, there is no update.

### Precondition
- Install via kiwi Docker in local server

### Steps to Reproduce

1. Update test case, add email account in CC
2. Click Save

### Actual results
- No notification mail

### Expected results
- Receive notification mail 

### Additional information

- Try with SMTP server (self-build server):

SERVER_EMAIL = DEFAULT_FROM_EMAIL = 'user@domain.com'
EMAIL_SUBJECT_PREFIX = '[Kiwi-TCMS] '

EMAIL_HOST = 'mail.domain'
EMAIL_PORT = 25 
EMAIL_HOST_USER = 'user@domain.com'
EMAIL_HOST_PASSWORD = 'password'

EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

- Try with AWS SES

SERVER_EMAIL = DEFAULT_FROM_EMAIL = 'user@domain.com'
EMAIL_SUBJECT_PREFIX = '[Kiwi-TCMS] '

AWS_SES_REGION_NAME = 'us-east-2'
AWS_SES_REGION_ENDPOIT = 'email.us-east-2.amazonaws.com'
EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_SES_ACCESS_KEY_ID = 'xxxxxxx'
AWS_SES_SECRET_ACCESS_KEY = 'xxxxxxxxxxx'

EMAIL_USE_TLS = True
EMAIL_USE_SSL= False 
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

**Comment by atodorov** [comment]
> Update test case, add email account in CC

Kiwi TCMS will exclude the current user from any email notifications b/c you are aware what changes you are making. 

If the event that email notifications aren't received by other users, not the one making the changes troubleshoot your email configuration first: https://kiwitcms.readthedocs.io/en/latest/configuration.html#testing-and-debugging-e-mail-configuration
