### ISSUE TITLE
Refactor tcms.testplans.views.choose_run

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#329]
Currently this method `choose_run` handles both `GET` - choose run to add cases and `POST` - add cases to run. 

IMO, this logic should be separated into two methods - one for the `GET` request and one for the `POST` request. There are other method in out code, which work in the same way. I think this is wrong for many reason, one of them being the violation of the Single Responsibility Principle and we should fix this.

**Comment by atodorov** [comment]
This method doesn't exist anymore so closing.
