### ISSUE TITLE
Remove fmt_queries()

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#330]
This function appears to replace some field names with others. Instead of doing that we can simply rename the fields in the corresponding forms (used at only a few places) to match the model fields which are going to be queried.

**Comment by atodorov** [comment]
This function is mostly used in Advanced search which is scheduled for removal #448

**Comment by atodorov** [comment]
@asankov - next one for you to spice things up!

**Comment by asankov** [comment]
Will look into this next.
