### ISSUE TITLE
Feature request: Test Run - Filter - Asignee - Implement filter by username

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#332]
**Where:**
1. Open one active test run
2. Click Show filter options

**Current behavior:**
The field will only filter results if user enters asignee's email address.

**Desired behavior:**
User can filter asignee also via asingee's username. If this could be done with some sort of dropdown list of applicable Kiwi usernames or input field which would autocomplete with Kiwi usernames.

**Comment by atodorov** [comment]
Fixed meanwhile in v8.9
