### ISSUE TITLE
Disabled Priority records still shown in UI

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#334]
### Description of problem
We only use two "priorites" so we disabled three of default five priorites, but they are sill shown in test plan tabs (Cases, Reviewing Cases) and test case editor.

### Component (web, API, etc)
Web.

### How often reproducible
Always

### Steps to Reproduce

1. Open https://kiwi.is.awesome/admin/management/priority/
2. Open one priority category
3. Uncheck button "Is active"
4. Confirm change with click on Save button
5. Open one test plan
6. Navigate to both Cases  tab
7. Hoover over Priority button

and
5. Open one test plan
6. Navigate to Reviewing cases tab
7. Hoover over Priority button

and
5. Open one test plan
6. Open one test case
7. Click on Priority dropdown

### Actual results
Both active and inactive priority categories are shown.

### Expected results
Only active priority categories to be shown.

![kiwi_priority_admin](https://user-images.githubusercontent.com/25688732/39578111-8f4d20be-4ee3-11e8-9ada-426599d83ebc.png)
![kiwi_priority_test_case](https://user-images.githubusercontent.com/25688732/39578112-8f6f355a-4ee3-11e8-94ac-a171bd8e18d1.png)
![kiwi_priority](https://user-images.githubusercontent.com/25688732/39578115-8f91bf76-4ee3-11e8-857c-567c1a03a6a9.png)

**Comment by Prome88** [comment]
This is also true for Test Plan filter view:
![image](https://user-images.githubusercontent.com/25688732/49149909-a8623b80-f30b-11e8-9859-b8200d4bf675.png)


and Test Run filter view:
![image](https://user-images.githubusercontent.com/25688732/49149879-9385a800-f30b-11e8-956d-efc3ed14ee9e.png)

**Comment by atodorov** [comment]
+1, this is legit bug.
@Prome88 can you open another issue with the latest attachment. That is in completely different part of the code.
