### ISSUE TITLE
Not allowed file attachments

### ISSUE THREAD

**Issue by frentmeister** [kiwitcms/Kiwi#3349]
### Description of problem

after the change in version 1.22 there is a restriction of file attachments. But nowhere is visible which file attachments are allowed here, or which I can possibly add. 

I can't find anything in the documentation.

### Steps to Reproduce

1. Open Kiwi
2. Add a File to kiwi like Python
3. upload

### Actual results
Not allowed

### Expected results
Find a way to upload different Files

**Comment by frentmeister** [comment]
I found this information: https://github.com/kiwitcms/Kiwi/security/advisories/GHSA-fwcf-753v-fgcj

**Comment by atodorov** [comment]
> Actual results
>
> Not allowed


There is an actual error message printed on screen. What is it?
