### ISSUE TITLE
Feature request: Create new case -> Enlarge Summary input field

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#336]
**Location:**
1. Testing
2. New test case
3. Summary

**Current implementation:**
Summary input field is only half of the lenght of other fields and only shows around 33 characters.

![kiwi_summary_input_field](https://user-images.githubusercontent.com/25688732/39617218-1813ccb8-4f7f-11e8-8be1-cc1e9cedc01d.png)

**Desired implementation:**

Field is as long as Component window and is automatically expanded with additional line below if user enters an input that would be longer than the available input field size on screen.

**Comment by atodorov** [comment]
Will be resolved by the redesign of this page which is handled by @asankov

**Comment by atodorov** [comment]
https://demo.kiwitcms.org/cases/new/ - Summary field occupies full length of the screen.
