### ISSUE TITLE
Test plan - Cases  / Reviewing Cases - - Display of list longer than 9 items

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#339]
### Description of problem
When one of the components of test case (Setup, Breakdown, Actions, Expected results) has a list with 10 or more items, the display of the test is broken.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
4.1.4

### How often reproducible
Always:
Opera - 52.0.2871.64
Chrome - 66.0.3359.139 
Firefox - 59.0.3

### Steps to Reproduce

1. Create new test case with 10+ items in ordered list
2. Save test case
3. Check the test case display in Test plan

### Actual results
![test_case_display](https://user-images.githubusercontent.com/25688732/39865825-72899b72-544e-11e8-8ea8-6c93b20e7995.png)

### Expected results
Test case text should be shown inside the field border.

**Comment by atodorov** [comment]
Thanks for the report. Looks like maybe an issue with the underlying component or HTML styling, not sure ATM.

**Comment by atodorov** [comment]
Note to self:
https://demo.kiwitcms.org/plan/1219/performance-baseline-tp-at-2018-10-26-14-39-56#testcases
Case #1715, second row

will be fixed when this page is redesigned.
