### ISSUE TITLE
Numbered List button does not number the lines

### ISSUE THREAD

**Issue by AkaZLOY** [kiwitcms/Kiwi#3390]
### Description of problem

Numbered List button does not number the lines when new test case is creating. Every new line numbered as "1."

![image](https://github.com/kiwitcms/Kiwi/assets/75592299/62c02c84-c1e7-4d45-ac7a-428165dd05c7)

How it looks in Kiwi:

https://github.com/kiwitcms/Kiwi/assets/75592299/97181438-8986-4ff0-9621-9c0d206e51b0

How it looks, for example, in Jira:

https://github.com/kiwitcms/Kiwi/assets/75592299/c26b20f2-7c40-4fa1-b8a8-af9017fdbe15

### Version or commit hash (if applicable)

12.6.1

### Steps to Reproduce

1. Open Kiwi main dashboard;
2. Click on "Testing" button;
3. Click on "New test case" button;
4. Write some lines with random information;
5. Select all crated lines;
6. Click on "Numbered List" button;

### Actual results

Every created lines number as "1."

### Expected results

Each line created is numbered according to the line number

![image](https://github.com/kiwitcms/Kiwi/assets/75592299/f5766eb7-81c0-4ac7-ab16-4189b31eba0d)

### Additional info (Python traceback, logs, etc.)

That issue reproduce on https://public.tenant.kiwitcms.org/

**Comment by somenewacc** [comment]
EasyMDE has it out of the box

**Comment by somenewacc** [comment]
BTW, it will be rendered just fine:
![image](https://github.com/kiwitcms/Kiwi/assets/62895232/325f5d91-3e02-4c35-a0f4-ec56c529b354)

**Comment by atodorov** [comment]
In the latest version of Kiwi TCMS, if you click the numbered list button it starts off with `1.`. Then you type your item text and press Enter the numbering continues with `2.`, then `3.`, etc. so it is all working correctly.

Regardless of that numbered lists where all items are `1.`, `1.`, etc are still considered valid Markdown syntax and are still rendered correctly. 

There's nothing to be fixed here.
