### ISSUE TITLE
Test run - Test case - Report bug - Bug can't be reported, no error visible to user in application

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#341]
### Description of problem
When trying to report bug from test case to connected JIRA bug tracker user is stuck on confirmation dialogue without any feedback. 

### Component (web, API, etc)
Web + JIRA connector

### Version or commit hash (if applicable)
4.1.4

### How often reproducible
Always.

### Steps to Reproduce

1. Connect Kiwi to JIRA
2. Create test run
3. Open test case and click Report
4. In dropdown Issue Tracker select JIRA
5. Click report

### Actual results
Nothing happens.

### Expected results
In case of error user should be informed that something is wrong.

### Additional info
Error from error_log

ERROR:django.request:Internal Server Error: /caserun/36/bug/
 Traceback (most recent call last):
   File "/venv/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
     response = get_response(request)
   File "/venv/lib64/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/venv/lib64/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/venv/lib64/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
     return func(request, *args, **kwargs)
   File "/venv/lib64/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
     return view_func(request, *args, **kwargs)
   File "/venv/lib64/python3.5/site-packages/tcms/testruns/views.py", line 891, in bug
     return func()
   File "/venv/lib64/python3.5/site-packages/tcms/testruns/views.py", line 837, in file
     url = tracker.report_issue_from_testcase(self.case_run)
   File "/venv/lib64/python3.5/site-packages/tcms/issuetracker/types.py", line 273, in report_issue_from_testcase
     comment = "Filed from caserun %s\\n\\n" % caserun.get_url()
 AttributeError: **'TestCaseRun' object has no attribute 'get_url'**

**Comment by JacobColyer** [comment]
If you're running this from a Docker container, it appears as if the Docker container isn't up-to-date with the latest codebase. I've been looking through the commit history and it appears as if @atodorov has made changes to refactor get_url() to get_full_url(). You can see this in commits https://github.com/kiwitcms/Kiwi/commit/2f8ccd83183e1d3a8c226cc32a4126cf7152e7e9, https://github.com/kiwitcms/Kiwi/commit/3a3bc569cb1f223e3809d5e96cc7cdedf9e9ba50, https://github.com/kiwitcms/Kiwi/commit/663458a196739ef5b5be0b2322e1c625773e203f, and https://github.com/kiwitcms/Kiwi/commit/de174a09945dddfe327b871435c00086809191cc.

I'm going to take a look at the Docker container and see if I can get it working on my environment and I'll report back what I can.

**Comment by JacobColyer** [comment]
An update to the issue:

The current docker container is, in fact, out of date. In order to get the JIRA integration to work, you need to modify the types.py file in /tcms/issuetracker/ and change the call(s) get_url() to get_full_url(). After changing these calls, I was finally able to get a new tab to open with the JIRA information provided. It is worth noting that in Chrome, I had to add a popup blocker exception to my Kiwi webpage in order for it to open new windows and open the issue.

I've tried creating a new Docker image using the Dockerfile provided in the source code, but when Docker builds the image, there are issues where some RUN commands do not work because there isn't a python command included.

This can be observed by cloning the git repository as is and running '_docker build -t <tag_name> ._' There are several warnings (OK) and a few errors where it states 'No file or directory'. I think I'll create a separate issue identifying the Dockerfile not building the image.

**Comment by Prome88** [comment]
@JacobColyer did you have to reinitialize/restart the application/docker container after making the code changes in types.py ?

**Comment by JacobColyer** [comment]
My apologies, you are correct. What I meant by out of date is that the container doesn't match the current master branch. Which makes sense, you don't want to rebuild the container after every commit.

And yes, it appears to have been fixed in other commits which aren't in the container yet.

**Comment by JacobColyer** [comment]
@Prome88 if you edited the file directly in your running container, you are going to need to follow a few steps.
1. 'docker compose down'
2. 'docker container ls -a'
3. 'docker container commit <CONTAINER_ID>' where CONTAINER_ID is the ID of the container you edited.
4. You can tag your new image at this point, if so, do 'docker images' and then 'docker image tag <IMAGE_ID>' where IMAGE_ID is the new image you created.
5. Edit the docker-compose.yml file. In the web: section, edit the image from kiwitcms/kiwi:latest to whatever tagname you gave your image.
6. 'Docker-compose up -d' and then you should be good to go.

I might have missed a step in there, but that's about all I can remember. An easier solution might be to just mount the host types.py file to the guest's types.py file. If you've got the latest changes in master, you can use that file and it should resolve the issue for you.

**Comment by Prome88** [comment]
Resloved with 4.2 .
