### ISSUE TITLE
Test Plan not set with TestCase.Create - API jsonrpc

### ISSUE THREAD

**Issue by elian-neagu** [kiwitcms/Kiwi#3423]
### Description of problem
Using the jsonrpc 2.0, when trying to create a new test case, the test plan is not set even though it's specified in the parameters section.
The user has to add it manually

### Version or commit hash (if applicable)
kiwi:latest 
c2a9b82871d9 docker id

### Prerequisites
Use Postman (any version)
Use json-rpc (https://localhost/json-rpc/)

### Steps to Reproduce

1. Get an session id token using Auth.login method
2. Using TestCase.create method, send add an existing test plan id in the params section.
3. Click send
4. This is the request body i'm sending: 
5. {
    "jsonrpc": "2.0",
    "method": "TestCase.create",
    "params": [
        {
            "summary": "Testplan foobar3432432424242",
            **"plan" : 2,**
            "is_automated" : true,
            "category" : 1,
            "priority":1,
            "case_status": 2,
            "text":"THis is a test"
            
        }
    ],
    "id": "jsonrpc"
}

### Actual results
The test case is created successfully but it's not added to the test plan automatically and also in the respons body, the plan is also not mentioned. 

this is the response body i'm receiving:
{
    "id": "jsonrpc",
    "jsonrpc": "2.0",
    "result": {
        "id": 20,
        "is_automated": true,
        "script": "",
        "arguments": "",
        "extra_link": null,
        "summary": "Testplan foobar3432432424242",
        "requirement": null,
        "notes": "",
        "text": "THis is a test",
        "setup_duration": "None",
        "testing_duration": "None",
        "case_status": 2,
        "category": 1,
        "priority": 1,
        "author": 2,
        "default_tester": null,
        "reviewer": null,
        "create_date": "2023-11-17T08:49:11.985"
    }
}

### Expected results
If the user provides a test plan id, when creating a new test case, that test case should be added automatically to that test plan without the user having to add it manually after words.

**Comment by atodorov** [comment]
Many-to-many fields are explicitly excluded from the API functions which is also consistent with the webUI creation pages. 

You can use [TestPlan.add_case())[https://kiwitcms.readthedocs.io/en/latest/modules/tcms.rpc.api.testplan.html#tcms.rpc.api.testplan.add_case) after creating the test case to achive the same result.
