### ISSUE TITLE
Documentation : add git clone command

### ISSUE THREAD

**Issue by aferre** [kiwitcms/Kiwi#344]
Hi,

From the docs http://kiwitcms.readthedocs.io/en/latest/installing_docker.html it is not clear that one should have to clone the Kiwi Github repo and then launch the specified command it he cloned repo (docker-compose up -d).

It would be helpful for the new to Docker installs (like me)

**Comment by atodorov** [comment]
@asankov can you look into this.

FYI ReadTheDocs fails to build b/c we're using Python 3.6 and they only have 3.5 which is missing the `secrets` module. Once the docs are patched we have to see how to resolve the build issue on RTD.

**Comment by realkot** [comment]
@asankov 
I think, you forget to add steps after clonning the repo. For running "docker-compose up -d" you need to change the working directory. Please update the docs.
