### ISSUE TITLE
Feature request - Test Run - Comments section - Automatically expand Comments History if there are comments present

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#349]
**Current behavior:**
When user adds comment to test case the comment is hidden on test run view until user clicks on button Show all under comments history.

![image](https://user-images.githubusercontent.com/25688732/40349253-57e88060-5da6-11e8-8bf8-d1e96b3030d3.png)

**Desired behavior:**
Adding comments to test case results is very common and should be visible to user without the need for an additional click.

![image](https://user-images.githubusercontent.com/25688732/40349286-76951ca8-5da6-11e8-89fe-3ff0445164ee.png)

**Comment by okainov** [comment]
+, would be nice to have

**Comment by ohporter** [comment]
Since deploying kiwi for a project here, I've also noticed this would be great to have. I find I refer to a test run case by link in our team irc channel and comments on a failure or otherwise would be handier if autoexpanded. I might try looking into adding this...

**Comment by atodorov** [comment]
@ohporter,
probably the easiest way will be to attach the function that expands the comments to the onclick event for the result row, however I haven't looked at that part of the code in details.

Be warned there's some hairy JavaScript in there which needs some love.

**Comment by ohporter** [comment]
@atodorov another approach is to default to show all in the template. I'm using this atm:

`
diff --git a/tcms/templates/case/get_details_case_run.html b/tcms/templates/case/get_details_case_run.html
index dcba9b8..fbed087 100644
--- a/tcms/templates/case/get_details_case_run.html
+++ b/tcms/templates/case/get_details_case_run.html
@@ -46,11 +46,13 @@
                                <h4 class="borderB">Comments History ({{ comments_count }}):
                                {% ifequal comments_count 0 %}
                                        <span>[ <a id="showText" href="javascript:void(0);">Show All</a> ]</span>
-                               {% else %}
-                                       <span>[ <a id="showText" class="js-show-comments" data-param="comment{{ test_case_run.pk }}" href="javascript:void(0);">Show All</a> ]</span>
-                               {% endifequal %}
                                </h4>
                                <ul class="comment" id="comment{{ test_case_run.pk }}" style="display:none;">
+                               {% else %}
+                                       <span>[ <a id="showText" class="js-show-comments" data-param="comment{{ test_case_run.pk }}" href="javascript:void(0);">Hide All</a> ]</span>
+                               </h4>
+                               <ul class="comment" id="comment{{ test_case_run.pk }}">
+                               {% endifequal %}
                                        {% for comment in caserun_comments %}
                                        <li>
                                                <span>#{{ forloop.counter }}</span>
`
