### ISSUE TITLE
No possibility to cancel crowdin dialog

### ISSUE THREAD

**Issue by dleidert** [kiwitcms/Kiwi#3515]
### Description of problem

When turning on/off the "Übersetzungsmodus", one is stuck with the crowdin dialog. There is no exit or cancel option, nothing. When refreshing or re-entering the domain, one is still stuck with this dialog.

### Version or commit hash (if applicable)

Latest Docker image, but also on <public.tenant.kiwitcms.org> currently (today).

### Steps to Reproduce

1. Open the main page
2. Click on the world symbol and "Übersetzungsmodus"
3. The crowdin dialog appears

### Actual results

There is no way back from there, no cancel or exit. Also a refresh or entering the main URL does not bring me back to the main page.

### Expected results

It should be possible to cancel.

### Additional info (Python traceback, logs, etc.)

![Bildschirmfoto vom 2024-02-05 18-24-59](https://github.com/kiwitcms/Kiwi/assets/14413364/e6a520e4-0a4b-4c7e-8f1f-e4fc88e8400f)

**Comment by atodorov** [comment]
It's a 3rd party service which is designed to work like that. Clearing your cookies should solve it.

**Comment by dleidert** [comment]
Thanks for your feedback. You include that service, though. I am not convinced that having to clear (all) cookies in a user's browser is a working solution. I'm currently examining multiple test management solutions, and having a user stuck at:

![Bildschirmfoto vom 2024-02-12 01-57-20](https://github.com/kiwitcms/Kiwi/assets/14413364/13c43d4b-5a14-4e9d-a574-992656a00f3c)

independent of which URL they enter, is a real blocker.

**Comment by barkside** [comment]
I had this issue when I clicked on it by mistake. I just had to create an account and log in to move on.  And then Afterwards I configured Kiwi to disable the Crowdin plugin altogether.
