### ISSUE TITLE
500 eror on web operations when duplicate email addresses exist

### ISSUE THREAD

**Issue by ohporter** [kiwitcms/Kiwi#352]
### Description of problem

When two users are created with the same email address, various queries will fail due to multiple objects being found with the same email address. This might commonly happen by reusing the admin email address when creating a user through the admin panel. This results in a failure on any web action that results in sending an email alert to a user. The common one where I first noticed it is creating a new test run.

### Component (web, API, etc)

web

### Version or commit hash (if applicable)

4.1.4

### How often reproducible

Always

### Steps to Reproduce

1. Logged in as admin, create a new user with the same email as admin
2. Create a test plan and confirmed test case
3. Create a new test run with the test case and click Save

### Actual results

500 error

with debug enabled we get MultipleObjectsReturned get() returned more than one User -- it returned 2!

### Expected results

Operation successful, in the case of a test run ,we expect the run to be created after save and the notification email sent.

### Additional info

Workaround is to make sure the admin does not manually create any users with duplicate email addresses. Users created by the registration option are forced to have a unique email address. It might be a good idea to have the same check within the Admin interface for adding users.

**Comment by atodorov** [comment]
similar to #68.

@ohporter can you post information how are you able to create users with duplicate email addresses ?

**Comment by ohporter** [comment]
1. Set up KiWi TCMS as normal ending with creation of initial user, **admin** with email address of **foo@bar.com**
2. Login as **admin** user
3. Click Admin->Users and Groups
4. Click User+ (add user)
5. Enter username and password of **user**
6. Click Save and Continue to Edit
7. Enter **foo@bar.com** in password field
8. Click Save 

There are now two users with the same email address in the database.

**Comment by atodorov** [comment]
@asankov here's a challenge for you.
