### ISSUE TITLE
Replace HttpResponse(json_object, content-type='application-json') with JsonResponse

### ISSUE THREAD

**Issue by asankov** [kiwitcms/Kiwi#356]
As discussed in #331, there are some places in the code that use `HttpResponse(json_object, content-type='application-json'`. They can be replaced with `JsonResponse(json_object)`. However, there may be some places where that could not happen automatically and further work need to be done in order for the serialization of the object to be succesfull.

**Comment by atodorov** [comment]
Not a bug. JsonResponse expects an object, while HttpResponse expects a string. converting object to json string and then trying to serialize this as JSON is asking for troubles.
