### ISSUE TITLE
New test plans redirection to 127.0.0.0:8000

### ISSUE THREAD

**Issue by bishnupradhan** [kiwitcms/Kiwi#362]
I have run  Kiwi TCMS as a Docker container on AWS ECS container.
But I noticed that any new Test Plans created, It's redirected to 127.0.0.0:8000.
After manually corrected the URL to the domain name, the required page open and the rest of thing working fine.
Is there anything to configure?

**Comment by JacobColyer** [comment]
Did you follow the instructions provided [here](http://kiwitcms.readthedocs.io/en/latest/admin.html#configure-kiwi-s-base-url)?

I was getting the same issue until I switched the base_url. !27.0.0.1:8000 is intended for development, i.e. on your local machine and not on an AWS ECS container. You need to get the server url of your AWS ECS instance and use that for your base URL.
