### ISSUE TITLE
Don't spam emails during test case run status updates

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#367]
tcms/testruns/models.py 
>    def update_completion_status(self, is_auto_updated, is_finish=None):

Looks like self.save is being called almost *always* and it causes tons of spam emails during test run execution. Please don't spam on useless events.

**Comment by atodorov** [comment]
@okainov - the answer of "why remove it" is that this feature as it was implemented was more trouble than it's worth it.  I personally think this should be done automatically without asking when the last test case has been executed (this is missing, feel free to request it and let's count the +1s). 

OTOH I like to keep runs unfinished so they are available on my dashboard until I don't need them anymore.
