### ISSUE TITLE
Maybe rethink of localization?

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#368]
Maybe it's some kind of off-topic, but maybe it worth to rethink about localization and its approach. I would think that it's so low priority so it's just "best efforts". Moreover, since Kiwi is a tool targeted to software engineers, every user most probably knows some basic English to work with it.

But ATM some templates are full of one big "blocktrans" tag which makes it impossible to use {for} in template and other more complicated tags. The same is for translation - one big blob is not really useful for translation, you should use something like `trans "Product version"`, so limit the text to smaller meaningful pieces.

**Comment by atodorov** [comment]
> so limit the text to smaller meaningful pieces.

smaller pieces without context may not be that meaningful to everyone. That says this is a low priority and PRs are welcome. We're happy with whatever works best for contributors so if you have templates that you would like to update please send a PR and we are going to review them.
