### ISSUE TITLE
Docker Image for Arm Architecture

### ISSUE THREAD

**Issue by bevolve-ankur** [kiwitcms/Kiwi#3707]
**Is your feature request related to a problem? Please describe.**
It'd be great to have ARM architecture images for KIWI-TCMS. I am glad to contribute if given better direction

**Describe the solution you'd like**
I am trying to generate images on local using `docker buildx`. I suggest following change in 
`Makefile`
```
.PHONY: docker-image
docker-image:
	rm -rf dist/
	docker pull registry.access.redhat.com/ubi9-minimal
	docker buildx build --platform linux/arm64 -t kiwitcms/buildroot-arm -f Dockerfile.buildroot .
	docker run --rm --security-opt label=disable \
	            -v `pwd`:/host --entrypoint /bin/cp kiwitcms/buildroot-arm \
	            -r /Kiwi/dist/ /host/
	docker run --rm --security-opt label=disable \
	            -v `pwd`:/host --entrypoint /bin/cp kiwitcms/buildroot-arm \
	            -r /venv /host/dist/
	docker buildx build --platform linux/arm64 -t kiwitcms/kiwi-arm:latest .

```
Please note the docker image names `kiwitcms/buildroot-arm` and `kiwitcms/kiwi-arm` is just for reference to show you here. The actual image name should be same.

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
How much important following step is in `Dockerfile.buildroot`? I saw some failures in this step while building images for ARM
```
RUN ./tests/check-build
```

**Comment by bevolve-ankur** [comment]
Just to confirm here I was able to create an ARM image successfully and I have hosted this image internally as well.
I was able to run following command successfully
```
docker exec -it kiwi_web /Kiwi/manage.py initial_setup
```
I believe this contains tests as well and no test case failed. Maybe this can be implemented safely.

**Comment by atodorov** [comment]
https://kiwitcms.org/containers/
