### ISSUE TITLE
Password reset email was sent! but not received

### ISSUE THREAD

**Issue by Kaviyarasansf4298** [kiwitcms/Kiwi#3782]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

Password reset email was sent! but not received in mail box

### Version or commit hash (if applicable)

Version : 3.15

### Steps to Reproduce

1. Mail need to receive 
2.
3.

**Comment by atodorov** [comment]
https://kiwitcms.readthedocs.io/en/latest/configuration.html#e-mail-settings
