### ISSUE TITLE
 account confirmation emails are not sent

### ISSUE THREAD

**Issue by ERIKASKO** [kiwitcms/Kiwi#3785]
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
Looks like unconfigured email delivery backend: https://kiwitcms.readthedocs.io/en/latest/configuration.html#e-mail-settings
