### ISSUE TITLE
Openining a test plan causes a redirection using 127.0.0.1 instead of the correct ip

### ISSUE THREAD

**Issue by ntriquenaux** [kiwitcms/Kiwi#379]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
When clicking on a testplan to open it, or when validating its creation (and thus opening the testplan)
a bad redirection is performed from 
w.x.y.z.:8060/plans/new/ to 127.0.0.1:8000/plan/8/sqsdqsdqdqds
or 
w.x.y.z.:8060/accounts/root/recent/ to 127.0.0.1:8000/plan/8/sqsdqsdqdqds

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
dockerised version from docker hub -> kiwitcms/kiwi:4.1.4

### How often reproducible
Always

### Steps to Reproduce

1. click on a test plan from the home page
2. create a new test plan and validate it
3. any action that will result in opening a test plan

### Actual results
getting redirected to 127.0.0.1:8000/plan/8/sqsdqsdqdqds

### Expected results
getting rediected to w.x.y.z.:8060/plan/8/sqsdqsdqdqds

### Additional info
Also i got these bad redirection when i used the docker locally on my computer as it was performing 
a redirection to port 8000 instead or port 8060. (as i was on the localhost, i did not saw also the bad ip at that time)

**Comment by atodorov** [comment]
Configure your base IP address, see the first note in the docs:
http://kiwitcms.readthedocs.io/en/latest/configuration.html
