### ISSUE TITLE
Request new language: Ukrainian

### ISSUE THREAD

**Issue by OleksandrNemchenko** [kiwitcms/Kiwi#3833]
Hello!
If it is possinle to enable Ukrainian language in Crowdin for Kiwi usage?

**Comment by atodorov** [comment]
Enabled in https://github.com/kiwitcms/Kiwi/pull/3836. Happy translating.

**Comment by OleksandrNemchenko** [comment]
Thanks! Step by step I'll translate it. How to send you results? Could you give me e-mail for the simplicity? I'll send you translated version.

**Comment by atodorov** [comment]
See https://kiwitcms.readthedocs.io/en/latest/contribution.html#translation

**Comment by OleksandrNemchenko** [comment]
I've fixed newly created by you `tcms/locale/uk_UA/LC_MESSAGES/django.po`.  I attached it here as django.po.txt .
[django.po.txt](https://github.com/user-attachments/files/17645879/django.po.txt)
Is it possible just to commit it to the code? Because I have some trouble while build Kiwi locally. And as far as I understand I need to rebuild docker image to use new translation

**Comment by atodorov** [comment]
@OleksandrNemchenko can you please open a PR for this file.
