### ISSUE TITLE
Create test run - test cases are marked as unconfirmed while saving the test run

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#388]
### Description of problem
Test cases with status confirmed cannot be added to test run.

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
4.2

### How often reproducible
Always.

### Steps to Reproduce

1. Create new test run or editi existing one
2. Check some test cases
3. Click on Run
4. Click on Create New test run

### Actual results
Test cases with status Confirmed are marked as removed and are not added to test run.

![1](https://user-images.githubusercontent.com/25688732/42018004-17db732e-7ab1-11e8-9b61-b7f01fcb1c34.png)
![2](https://user-images.githubusercontent.com/25688732/42018005-17f64d48-7ab1-11e8-8fa1-134364623b3c.png)
![3](https://user-images.githubusercontent.com/25688732/42018006-18113c52-7ab1-11e8-844f-8f9d0acc7c82.png)

### Expected results
Test cases with status Confirmed can be added to test run.

### Additional info
This started with upgrade to 4.2. I presume that it could be due to new localization where status names are translated into Slovenian where application checks for status in English.
There is nothing in error log.

**Comment by atodorov** [comment]
@Prome88 I love to see Kiwi TCMS translated in another language. Thanks for this.

This issue is purely visual from what I can tell. The offending code is in `templates/run/new.html`:


```
<td{% if not test_case.case_status.name == 'CONFIRMED' %} style='text-decoration: line-through'{% endif %}>
                                                        {% if not test_case.case_status.name == 'CONFIRMED' %} <img src="{% static 'images/warning.png' %}"/>{% endif %}
                                                        <a id="link_{{ forloop.counter }}" class="blind_title_link js-case-summary" data-param="{{ forloop.counter }}" >
                                                                {{ test_case.summary }}
                                                        </a>
                                                </td>
```

There's a quick fix where we can compare against the translated value but honestly I'd like to investigate deeper and come up with a solution that doesn't require fixing every single template.

If you continue to see problems related to translated statuses please keep reporting them, however if they prevent you from using Kiwi TCMS you may want to use the English translation as a workaround.

**Comment by Prome88** [comment]
What would be the safest way to change the language on live application with minimal downtime?

**Comment by atodorov** [comment]
After the "Create new Test Run" has been redesigned with patternfly this is no longer an issue:
![new_run_in_slovenian](https://user-images.githubusercontent.com/1002300/46529941-e5c4c280-c8a0-11e8-8aa3-d4dc1b6e2d82.png)


statuses are shown as translated, see screenshot. Closing this issue.
