### ISSUE TITLE
How to intergrate with redmine?

### ISSUE THREAD

**Issue by archonwang** [kiwitcms/Kiwi#41]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
How to intergrate with redmine?

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
> How to intergrate with redmine?

Hi @archonwang,
the existing integration boils down to:

1.  You can click Report from an existing test case run and this will open the bug tracker with pre-filled information. Thinks like steps to reproduce, product, etc will be taken from the test case.
2. When adding bug number to a Test Case Run you have the option to add a comment to the bug tracker linking back to the test case URL. 
3. If the bug tracker supports displaying multiple issues on one page (via URL parameters) this is also supported for the reporting section.

All of this happens inside the `tcms/issuetrackers/` directory. Checkout the GitHub integration it is probably the easiest one. Would you like to submit a PR ?

**Comment by archonwang** [comment]
@atodorov ,
so sorry that I am not similar with the python or ruby.
or anyone have same requirements about it?

**Comment by atodorov** [comment]
ok then, I will consider this as request for enhancement for a future release. Thanks for your submission.

**Comment by csonuryilmaz** [comment]
Should it be a good idea to label this issue as **help wanted** to support below? @atodorov 
> ..  Would you like to submit a PR ?

I 've just installed latest version and disappointed about missing `redmine_integration.py` in `tcms/issuetracker` folder. :disappointed: 

Although I'm not familiar with `python` language, maybe I can duplicate an integration `.py` file to make some modifications and see whether it works.

Currenty, I 'll fill the first section of form at `/admin/testcases/bugsystem/add/` in order to try `LinkOnly` integration with Redmine.

**Comment by col-panic** [comment]
My Version is 7.1

I can't get this integration to work - everything seems to be configured correct, and I get the issue tracker on the list, but after clicking report - simply nothing happens! 

Docker log entry only says
```
kiwi_web | 172.20.0.1 - - [27/Nov/2019:09:10:11 +0000] "POST /json-rpc/ HTTP/1.0" 200 137 "https://tcms.medelexis.ch/runs/4/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0"
```
but there is no incoming request on the redmine host. The host address is definitely correct (although prepended with https not http - but an official valid certificate)

**Comment by atodorov** [comment]
Please don't comment on closed issues. Follow #97 which will help with debugging such issues.
