### ISSUE TITLE
Document branches in the repo

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#439]
In my team we're having a fork of Kiwi with our changes on top and we want to update regularly. I noticed that you have `master` and `next_release` branch, but I haven't found any explanation of your structure. Is it correct that `master` == `latest stable` and `next_release` == `develop` (which is not guaranteed to be stable)?

**Comment by atodorov** [comment]
You are correct about master but there are no assumptions nor guarantees for the rest.  You should rebase on top of master. 

Even better if you can send some pull requests our way for review and discussion.
