### ISSUE TITLE
Cannot delete bug which clone from another test run

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#475]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
Cannot delete bug which clone from another test run

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
5.2

### How often reproducible
always

### Steps to Reproduce

1. clone a finished test run, this test run has failed case and link bug id
2. keep default clone setting,  Reserve status Not marked, Reserver Assignee Marked
3. check the case failed in previous test run

### Actual results
the bug is clone, and no delete button, so cannot remove this bug.
if add a new bug, delete button appears

### Expected results
delete button should appear, then tester can remove the previous bug.

### Additional info
I alos try mark the Reserve status clone setting, all cases status keep same as previous test run. But still no delete button behind the bug id

![11](https://user-images.githubusercontent.com/11469746/44136123-2729aa2c-a09e-11e8-91bd-7bb5e462cec6.png)
![22](https://user-images.githubusercontent.com/11469746/44136127-27ae44da-a09e-11e8-976b-3e4438e79665.png)

**Comment by atodorov** [comment]
This is a feature, working as intended. The thinking behind was if this bug has been seen in other test runs then probably you will see it too. 

I will leave this issue open. The UI can do better in terms of indicating past issues.
