### ISSUE TITLE
Tags filed not save successfully

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#476]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
Tags filed not save successfully

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
5.2

### How often reproducible
always

### Steps to Reproduce

1. create a new test case or edit aa existed case
2. input some texts in Tags filed then click save button
3. open the case

### Actual results
Tags filed is empty, Tags filed not save successfully

### Expected results
Tags filed should display input texts

### Additional info
![11](https://user-images.githubusercontent.com/11469746/44142890-4cf7ae8c-a0b4-11e8-8116-3c3ba23024f3.jpeg)

**Comment by chenchangjiang** [comment]
Yes, thx. I also did as this. But this issue need fix.

**Comment by atodorov** [comment]
This UI field has been removed in 214191cc1f2a99bba6b1d67a0eeb2dc7a14ede06 together with the corresponding backend code. There's a separate tab which allows adding/removing of tags and which also makes sure to honor permissions.
