### ISSUE TITLE
dashboard test plan link url wrong

### ISSUE THREAD

**Issue by hakehuang** [kiwitcms/Kiwi#478]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
after create a test plan the url direct to https://127.0.0.1:8000/plan/3/test-plan-trial

### Component (web, API, etc)
web

### How often reproducible
always

### Steps to Reproduce

1. create a new test plan
2. click the link in dash board
3.

### Actual results
https://127.0.0.1:8000/plan/3/test-plan-trial

### Expected results
it shall be direct to the real url of my server

### Additional info
test is based on docker image

**Comment by atodorov** [comment]
Duplicate of #455. Read the documentation more carefully.

**Comment by hakehuang** [comment]
Configure Kiwi’s base URL
The first step you need to do is configure the base URL of your Kiwi TCMS installation. This is used to construct links to test plans, test cases, etc. The default value is 127.0.0.1:8000 which is suitable if you are running in devel mode. To update the setting go to https://<your_domain_or_ip>/admin/sites/site/1/! Update Domain name to the fully qualified domain name or IR address, including port if necessary and click the Save button!

this fix my problem. thanks a lot
