### ISSUE TITLE
Cannot change user

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#489]
I\m getting this error when trying to save user from admin panel. Tried to set up this setting to False, but then I'm gettting 404 on <kiwi>/admin/auth/user/16/change/b
Searching thru code didn't reall help in it...

Kiwi baseline is from this commit 531bc99

![image](https://user-images.githubusercontent.com/918446/44576848-e6d9de80-a78f-11e8-8a92-89aca5fb53e9.png)

**Comment by atodorov** [comment]
Post a traceback and steps to reproduce.

**Comment by okainov** [comment]
What kind of traceback? Where can I get it from? Isn't it the one on attached screenshot?

I described the steps - go to admin panel - select any user - edit - click "save".

**Comment by okainov** [comment]
Any update? This seem to be very High priority since it's blocking user editing!

**Comment by okainov** [comment]
I even did git bisect and found commit introducing this issue: f7198ca

**Comment by okainov** [comment]
And I even found an issue. You pass extra_context into form_url parameter. Please set up your linter to show this warnings as Pycharm does - it clearly states that you override `change_view` in a wrong way. And please  add a test for this functionality.

**Comment by atodorov** [comment]
I can't reproduce with master so unless you can reproduce there or give me more info and a traceback there isn't anything I can do. 

> And I even found an issue. You pass extra_context into form_url parameter. Please set up your linter to show this warnings as Pycharm does - it clearly states that you override change_view in a wrong way. And please add a test for this functionality.

I'm not exactly certain what you are talking about here. `KiwiUserAdmin` doesn't have a `change_view()` method.

s
