### ISSUE TITLE
RFE: provide command line tools to import/export test cases and test runs

### ISSUE THREAD

**Issue by tcler** [kiwitcms/Kiwi#491]
### Description of problem
seems there's not a way to:
   1. create/delete/update test-cases and test-runs from command line
   2. import/upload test run's result from command line

### Component (web, API, etc)
API

### Actual results
can't  create/import/upload  test run, so we can't auto report test result from script.
  users must edit test result on webUI one by one.

### Expected results
*Batch Import*
provide a way to create test-run and report test-result from command line.

for example user generate test results(in xml/json/yaml/...) from script, then
  tcms run --create $runname --result  result.yml  [--distro $distro --component $componnet --subcomponent  $subcomponent]

### More info
see <Pragmatic Programmer, The: From Journeyman to Master> -> "The Power of Text"

**Comment by atodorov** [comment]
Feel free to send pull requests implementing this functionality by using the existing API. See https://kiwitcms.readthedocs.io/en/latest/api/index.html

**Comment by tcler** [comment]
the document is tooo simple~
