### ISSUE TITLE
How to add own logo and colour theme.

### ISSUE THREAD

**Issue by Muvidevlopers** [kiwitcms/Kiwi#494]
Hi 
How can we add our own logo instead of kiwi.And how to change the colour theme.

**Comment by atodorov** [comment]
For the UI widgets we are migrating to Patternfly so you have to override its CSS properties related to color. Maybe a good start is here:
https://www.patternfly.org/styles/color-palette/

For logo you have to override the static file `images/kiwi_h20.png`.

For further support questions use the [kiwi-tcms](https://stackoverflow.com/questions/tagged/kiwi-tcms) tag at StackOverflow.
