### ISSUE TITLE
Feature Request: Authentication of users via OpenID

### ISSUE THREAD

**Issue by micha91** [kiwitcms/Kiwi#503]
There are connectors like mozilla-django-oidc, that add support for this authentication to Django. I already played around with it a little, but wasn't able to make it work with the current user-management of Kiwi-TCMS. Is there an API to add  external authentication methods to Kiwi and if not are there plans to implement support OpenID or an API for authentication?

**Comment by atodorov** [comment]
OpenID is already supported by Python Social Auth. You can easily install this on-top of the existing application and enable the backends that you wish. Docs at:
https://python-social-auth.readthedocs.io/en/latest/index.html

For the record the demo installation uses PSA and builds its own docker image based on `kiwitcms/Kiwi:latest`.
