### ISSUE TITLE
Test case - Edit - HTML tags shown

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#510]
With latest update and new editor (guessing from the new GUI) all previously entered tests have HTML tags shown in Edit test case view.

![image](https://user-images.githubusercontent.com/25688732/45020461-5d4bcb80-b02f-11e8-9f64-7a2bc72c2551.png)

**Comment by atodorov** [comment]
This is a known issue, read Changelog. You will have to convert these on your own.

**Comment by Prome88** [comment]
We consider this a critical bug as we are unable to properly edit previously inputed test cases and this should be converted automatically with the KiwiTCMS version update. We won't do this for all of 1000 test cases manually. Version 5.2 changelog does not state anything about this.

**Comment by Prome88** [comment]
Copy picture from clipboard to test case is also gone with the editor change.
Also why did you choose Markdown editor which has not been updated in over two years?

**Comment by Prome88** [comment]
Also simplemde is full of unresolved bugs which make dealing with lists very unpleasant.
