### ISSUE TITLE
Don't use get_full_url on the webpages

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#518]
Please don't use get_full_url on the pages. Use only normal urls.

When I copy the production website to my local machine, half of the links become broken (pointing to production instead of current)

The only point where you really need full one is emails.

**Comment by atodorov** [comment]
Version and pages on which you see this ?

**Comment by okainov** [comment]
Our Kiwi baseline is from 531bc99

Main dashboard page (test plan links), links on testplan view "tree view" page.

**Comment by atodorov** [comment]
All of these have been updated recently, that was issue #380. Try the latest version and then reopen 380 if you see this happening elsewhere. 

NOTE: there seems to be a bug with creating slugs (short URLs) for non ascii characters and that may cause the dashboard rendering to crash. I just saw such an issue with Chinese titles in Test Plan. Working on a fix.
