### ISSUE TITLE
Feature Request: SAML Integration

### ISSUE THREAD

**Issue by ryan-s** [kiwitcms/Kiwi#521]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem
SAML integration would be very useful since most identity providers support it and it would allow users to implement SSO on a wide variety of platforms

### Component (web, API, etc)
Web, API, Authentication

**Comment by atodorov** [comment]
SAML is already supported in python-social-auth which integrates seamlessly with Django and Kiwi TCMS (this is what we use on the demo site with only GitHub auth enabled):
https://python-social-auth.readthedocs.io/en/latest/backends/saml.html

You can install that as a dependency and rebuild your docker image.
