### ISSUE TITLE
Attachments upload causes 500 error

### ISSUE THREAD

**Issue by flamewow** [kiwitcms/Kiwi#523]
### Description of problem
When trying to add attachment to test plan server return 500 error.

### Steps to Reproduce

1. run latest docker version of kiwi
2. try to add attachment to the test plan
3. notice 500 error

**Comment by atodorov** [comment]
Submit a Python traceback and let me know if this reproduces on https://demo.kiwitcms.org ?

**Comment by flamewow** [comment]
> Submit a Python traceback and let me know if this reproduces on https://demo.kiwitcms.org ?


```
Request Method: | POST
-- | --
https://kiwi-qa.voxsync.com/attachments/add-for/testplans/testplan/12/
2.1.1
PermissionError
[Errno 13] Permission denied: '/Kiwi/uploads/attachments'
/venv/lib64/python3.6/os.py in makedirs, line 220
/venv/bin/python3
3.6.3
['/Kiwi',  '/venv/lib64/python3.6/site-packages',  '/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages',  '/venv/lib64/python36.zip',  '/venv/lib64/python3.6',  '/venv/lib64/python3.6/lib-dynload',  '/opt/rh/rh-python36/root/usr/lib64/python3.6',  '/opt/rh/rh-python36/root/usr/lib/python3.6',  '/venv/lib/python3.6/site-packages',  '/venv/lib64/python3.6/site-packages/tcms/core/lib']
Tue, 18 Sep 2018 08:11:49 +0000

```
On https://demo.kiwitcms.org is works fine.

**Comment by atodorov** [comment]
Is this an upgrade from a versoin older than 5.2  to the latest ? In 5.2 we are no longer running as root inside the container so permissions for pre-existing volumes must be updated manually, see Changelog.

**Comment by jasonyihk** [comment]
default folder for attachments `attachments/` is not created by default. manually create it and chmod 777 should fix the issue.
