### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#532]
No other comments. Just add some default favicon with kiwi :)

Just random picks from google
![image](https://user-images.githubusercontent.com/918446/45945164-df0a9580-bfec-11e8-861f-4f5defd4fae2.png)
![image](https://user-images.githubusercontent.com/918446/45945168-e3cf4980-bfec-11e8-8f2b-f2536769f49f.png)

**Comment by atodorov** [comment]
Note: none of these images is suitable because they don't match our logo. And we definitely don't want to add "random images from Google" because we have no idea what their license is.

**Comment by okainov** [comment]
Sure you want to check license first :)

First one looks kind of similar, doesn't it? Anyway, sure, if you have a dedicated designer, you may get your own.
