### ISSUE TITLE
JIRA integration failing due to issues with jira/requests dependencies

### ISSUE THREAD

**Issue by yekibud** [kiwitcms/Kiwi#538]
Cannot reproduce this issue on demo.kiwitcms.org since guest registrations have insufficient permissions to configure bug trackers.

Does anyone have JIRA integration working in their environments?

### Description of problem

Running Kiwi TCMS via docker-compose,
Adding bugs to the JIRA issue tracker fails due to apparent issues with jira/requests dependencies.  CURL requests to JIRA have no issue.

### Version or commit hash (if applicable)

Latest master fc876a784e03763f6

### Steps to Reproduce

1. Configure JIRA integration
2. Add bug to test case.

### Actual results

Dialog responds with:

```
WARNING:root:HTTPSConnectionPool(host='myproject.attlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",),)) while doing GET https://myproject.attlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.19.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
```

### Expected results

Bug should be added to tracker.

### Additional info (Python traceback, logs, etc.)

The issue seems to be a TLS cert issue with the underlying jira/requests dependencies, but this still is a bug for _this_ project, even if the issue needs resolving in the other projects.  

The bug can be isolated to the `rpc` assignment from `jira.JIRA()`.  Attempting to specify the certs that work with the CURL request or disabling the cert verification completely don't seem to have any effect, e.g. ```rpc = jira.JIRA(basic_auth=('foo@bar.com', 'somepassword'), options={'server': 'https://myproject.attlassian.net/', 'verify': False})```

**Comment by atodorov** [comment]
It looks like some kind of networking issue between your Kiwi TCMS host and JIRA, SSL error by the looks of it. Not sure if there's anything that we can do on our side. Can you try to provide some more information b/c without a reproducer I have no idea what is going on.

**Comment by yekibud** [comment]
Hi, @atodorov .  Thanks for your reply.

It would be helpful if I had admin perms on the demo site or someone could try configuring a JIRA bug tracker there to confirm success on the Kiwi source version fc876a784e0376 and docker image a420465852be.

I've tried this locally and on a Google Compute Engine VM, so I have at least duplicated it in two different standard environments with no changes to the TCMS docker image, following the standard deploy procedures, and simply adding the JIRA Bug tracker.  So I'm wondering how this is working for _anybody_ trying Kiwi with JIRA integration on the latest master/ docker image.

In any case, I realize the underlying problem is with the `jira` and `requests` dependencies, so I'll try troubleshooting those further or filing a bug report with the related projects.

**Comment by atodorov** [comment]
@yekibud can you try updating the jira package inside the container (pip install --upgrade jira should do it) and retry ? I'm wondering if the available 2.0 version will fix that ?

**Comment by yekibud** [comment]
Yeah, tried that.  No luck.

**Comment by okainov** [comment]
Most probably you need {'verify': False} option to be set in settings. have you tried to set JIRA_OPTIONS to this?

**Comment by yekibud** [comment]
Yeah, tried that too (per my bug report), no luck.  Same problem in multiple environments - Google Compute Engine deploy or local dev (no firewall).

@okainov Could you tell my what versions of `jira` and `requests` you are using?

**Comment by atodorov** [comment]
I must be jira 1.0.10 and I don't know about the requests library. Do a `pip freeze` inside the running container to get a list of all dependencies.

Side note: in the last few commits we've updated to the latest Jira client version but you already said this didn't make any difference.

This is a TLS/SSL issue, maybe even issue with the certificate on the JIRA server. Can you verify that the certificate on the JIRA server is current and is issued by a known CA? 

Looking back at your original report and traceback the problem should be reproducible with a simple Python script that tries to connect to your JIRA instance. Can you try and reproduce that way b/c otherwise there isn't much we can do to debug this problem.

**Comment by okainov** [comment]
>Could you tell my what versions of jira and requests you are using?

> jira==1.0.10
> requests==2.19.1
> requests-kerberos==0.12.0
> requests-oauthlib==1.0.0
> requests-toolbelt==0.8.0

**Comment by yekibud** [comment]
Omg, I found the issue:

Api URL = https://myproject.at**t**lassian.net

Sorry for the noise.  Closing.
