### ISSUE TITLE
Last login and Test record history time incorrect (wrt server timezone setting)

### ISSUE THREAD

**Issue by advhkjw** [kiwitcms/Kiwi#545]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
When the first time to create user and log into the system, the time is incorrect. Even, I tried to add some record such as new "Builds", "Product", when I accessed "History" tab, the "Date/time" shown a.m time not p.m. time

### Version or commit hash (if applicable)
The OS version is Debian 9.5 installed on Google Cloud. 

### Steps to Reproduce

1.Create new user by command
docker exec -it kiwi_web /Kiwi/manage.py createsuperuser
2.Login the web
3.Access "My Profile"-->"Last login"

### Actual results
2018-10-10 09:37:51
### Expected results
2018-10-10 17:XX:XX

### Additional info (Python traceback, logs, etc.)
By executing
>>timedatectl status
I got the below result:
Local time: Wed 2018-10-10 18:02:49 HKT
Universal time: Wed 2018-10-10 10:02:49 UTC
RTC time: Wed 2018-10-10 10:02:49
Time zone: Asia/Hong_Kong (HKT, +0800)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: yes

Even I modified the docker-compose.yml and Dockerfile to specific the timezone, this issue still cannot been fixed.

**Comment by atodorov** [comment]
`TIME_ZONE = 'Etc/UTC'` is in settings so you can change it if you want. Or alternatively update your system time to UTC.

Currently we don't save timezone info in the database so either treat all timestamps as local or UTC or experiment and figure out what breaks.

I think (but I'm not sure) when the browser displays timestamps they turn out localized and may even be in the timezone of the browser. Hadn't checked.

**Comment by advhkjw** [comment]
I had already modified /tcms/settings/common.py 
TIME_ZONE = 'Etc/UTC' to TIME_ZONE = 'Asia/Hong_Kong' but have no change.
Also the system installed on google cloud which cannot change the UTC
I am sure the browser detect the location is also Hong Kong.
I have googled about this seem the problem is this program didn't handle the timezoen by django.utils.timezone

**Comment by aspirin420** [comment]
![image](https://user-images.githubusercontent.com/32863315/55549812-57bf7c80-5709-11e9-8d1d-51ff0bd9555d.png)
It is same for me!
I changed the time_zone, but it still the UTC time when i create the test plan! what can i do now?
