### ISSUE TITLE
500 Internal Server Error - following standard doc instructions

### ISSUE THREAD

**Issue by wivaku** [kiwitcms/Kiwi#548]
### Version or commit hash (if applicable)
Did `git clone` Oct 14 13:00 CEST

### Steps to Reproduce

1. followed the instructions https://kiwitcms.readthedocs.io/en/latest/installing_docker.html
2. `git clone https://github.com/kiwitcms/Kiwi.git`
3. changed docker-compose.yml port mapping: comment out port 80 (because already in use), or change to e.g. 8080
4. checked ./tcms/settings/common.py : DEBUG = True
5. `docker-compose up`

### Actual results
docker-compose output: 
web_1  | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message

browser shows:
https://localhost/accounts/login/?next=/
Kiwi TCMS navbar
and error message: 500 Internal Server Error
![screenshot 2018-10-14 13 27 49](https://user-images.githubusercontent.com/2084872/46916027-01bd1800-cfb5-11e8-9bd1-96afaac637f0.png)

Same as: https://github.com/kiwitcms/Kiwi/issues/314

### Expected results
successful startup

**Comment by atodorov** [comment]
Reopen when you can provide debug logs, if you are seeing the above screenshot it means your instance is not properly configured in debug mode. If it is you should be seeing a python traceback.

There's nothing we can do until you can provide the above information.

**Comment by wivaku** [comment]
Was hoping the description was enough to reproduce. Where to get debug logs? And/or: which DEBUG setting needs to be set to True?
See step 4 above for what DEBUG flag I set (which was set to True by default). There was no additional logging shown in the docker console.

**Comment by Richard-Green-UK** [comment]
Looking at the instructions you followed, it appears you missed the 
`docker exec -it kiwi_web /Kiwi/manage.py migrate `
command required to generate the base tables in the database.

**Comment by wivaku** [comment]
how embarrassing! Thanks for pointing that one out. Works fine now.
