### ISSUE TITLE
Can't get started with Kiwi TCMS

### ISSUE THREAD

**Issue by rubaardah** [kiwitcms/Kiwi#560]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
I installed docker container and did all steps to run Kiwi TCMS successfully on my machine, but unfortunately, can't open it on the localhost:8000 , so may you please guide me in this problem 

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment]
Read carefully:
> Your Kiwi TCMS instance will be accessible at https://localhost.

and in the future please follow the instructions in the issue template and post support questions on StackOverflow with the kiwi-tcms tag.
