### ISSUE TITLE
Upgrade to 6.1 - django.db.migrations.exceptions.InconsistentMigrationHistory

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#561]
While upgrading from 6.x to 6.1 on our test system we got the following exception:

```
[Kiwi@kiwi-tmp Kiwi]# docker exec -it kiwi_web /Kiwi/manage.py migrate
Traceback (most recent call last):
  File "/Kiwi/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    executor.loader.check_consistent_history(connection)
  File "/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 297, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration testruns.0001_initial is applied before its dependency management.0001_squashed on database 'default'.
```

Application itself seems to be functional and running on 6.1 version. Is this expected behaviour?

**Comment by andrazh** [comment]
Actually, it said "Version 6.0". Didn't notice any "6.0.1". But since you don't have versions and one can only do "git pull" (and, of course, get the latest and greatest) - if we still had 5.3.1 ... how could we upgrade to 6.0(.1) first?
If the question really is whether we upgraded directly from 5.3.1 than the answer is no, upgrade to 6.1 happened on an instance upgraded to 6.0 first.

**Comment by atodorov** [comment]
Well this is what the blog post says:

```
NOTE: there is the 6.0.1 release which resolves an upgrade problem caused by non-applied migrations which have been later squashed and released in the same release! It is best to jump through the intermediate releases to ensure a smooth upgrade!

Supported upgrade paths:

5.3   (or older) -> 5.3.1
5.3.1 (or newer) -> 6.0.1
6.0.1            -> 6.1

Docker images:

kiwitcms/kiwi       latest  b559123d25b0    970.2 MB
kiwitcms/kiwi       6.1     b559123d25b0    970.2 MB
kiwitcms/kiwi       6.0.1   87b24d94197d    970.1 MB
kiwitcms/kiwi       5.3.1   a420465852be    976.8 MB
```

So the upgrade path is clearly described and the versions which you can't skip are also tagged and available from Docker hub.

In your case you should upgrade from 6.0 to 6.0.1 to 6.1 becase of the reason listed above.


> Actually, it said "Version 6.0". Didn't notice any "6.0.1". But since you don't have versions and one can only do "git pull"

You are wrong here.  Each version is tagged in git so you can pull & checkout to a particular release if you like. Also important versions are distributed as tagged docker images, while `latest` always points to the latest version.


For the particular traceback you reported there isn't anything I can do. You have to upgrade to 6.0.1 first and then to the latest version like the docs says.
