### ISSUE TITLE
RFE: enable account association by email for demo.kiwitcms.org

### ISSUE THREAD

**Issue by leon-anavi** [kiwitcms/Kiwi#573]
### Description of problem

I am unable to login with GitHub using "continue with" option at demo.kiwitcms.org. I have logged before and now I am getting an error that user with my email address already exists. It is expected to exist but I expected just to login automatically using my GitHub credentials and without typing anything.

### Version or commit hash (if applicable)

Version 6.1.1-ee

### Steps to Reproduce

1. Login in GitHub
2. Login once in demo.kiwitcms.org using GitHub from "or Continue With"
3. Try to login again in demo.kiwitcms.org using GitHub from "or Continue With"

### Actual results

Login error:
```
A user with address ****@*****.org already exists!
```

### Expected results

Successful login.

**Comment by leon-anavi** [comment]
Hi @atodorov, 

Thanks for the feedback. Is there a known work around for logging using GitHub in this particular case?

**Comment by atodorov** [comment]
> Is there a known work around for logging using GitHub in this particular case?

Yes, change the password for your existing account and when logging in via GutHub the application will create another user account.

**Comment by atodorov** [comment]
This has been resolved with the upgrade to 6.2
http://kiwitcms.org/blog/kiwi-tcms-team/2018/11/02/kiwi-tcms-62/

**Comment by leon-anavi** [comment]
@atodorov thanks! As we discussed privately - I have done several tests after the update of https://demo.kiwitcms.org/ and everything looks good now.

Best regards,
Leon
