### ISSUE TITLE
navigation bar gets spanned and two show toolbar options will be shown after traversing for few pages

### ISSUE THREAD

**Issue by vimukthi101** [kiwitcms/Kiwi#578]
### Description of problem

navigation bar gets spanned and two show toolbar options will be shown after traversing for few pages

### Steps to Reproduce

1. login to UI
2. traverse to few different pages
3. check the navigation bar and the show toolbar option 

### Actual results

1. navigation bar gets spanned
2. two show toolbar options were available

### Expected results

1. navigation bar size should be fixed
2. only one show toolbar option should be available

**Comment by atodorov** [comment]
Provide a screenshot and tell me exactly how and where do you click in the application and if you open windows in a new tab or no.

**Comment by vimukthi101** [comment]
By changing the DEBUG = False on tcms/settings/devel.py file the Show toolbar option will be removed, but still the spanned navigation bar will be there

**Comment by atodorov** [comment]
This is not an error. DjDT menu is django-debug-toolbar which is shown only in debug mode. Because some of the pages still use the old UI interface they are loaded inside an iframe (more precisely the navigation is inside an iframe) and Django will show debug toolbar for every page it loads.
