### ISSUE TITLE
redirection shows a information message on UI instead of redirecting

### ISSUE THREAD

**Issue by vimukthi101** [kiwitcms/Kiwi#579]
### Description of problem

redirection shows a information message on UI instead of redirecting

### Steps to Reproduce

1. go to dashboard
2. click on available test plan
3. check the outcome

### Actual results

1. redirected to info page with following information

> 301 Moved Permanently
> 
> Location: /plan/1/test-kiwi
> 
> The Django Debug Toolbar has intercepted a redirect to the above URL for debug viewing purposes. You can click the above link to continue with the redirect as normal.

### Expected results

1. should be redirected to the test plan

**Comment by atodorov** [comment]
Which version is this? 

How are you running Kiwi TCMS, from a Docker container or otherwise  because I can't reproduce. If possible try to reproduce on the demo site.

**Comment by vimukthi101** [comment]
This was solved by changing the DEBUG = False on tcms/settings/devel.py file
Marking the bug as invalid
