### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by kryskool** [kiwitcms/Kiwi#601]
Hi

French translation is done at crowdin

Do i send the PO file as Pull Request ?

Regards,

**Comment by atodorov** [comment]
@kryskool thank you for fast turnaround. Crowdin will open pull requests automatically, see:
https://github.com/kiwitcms/Kiwi/pull/600

We're in the process of making a -bot account for Crowdin but unfortunately we can't attribute individual contributions to translations.

**Comment by kryskool** [comment]
Hi @atodorov 

Thanks for the tips for PR

Regards,
