### ISSUE TITLE
Administration - Users - Change password for user - Password is changed for currently logged in user

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#610]
### Description of problem
I've tried to change password for another user
![image](https://user-images.githubusercontent.com/25688732/48412322-9b0e5400-e744-11e8-8310-32dbe85d9468.png)

But the application changed the password of currently logged (since both had the same initial password) in user instead of the selected user.

In hindsight I should have noticed the red flags with the text on the change password mask (your password, change my password) but I did not read them carefully.

On /admin/auth/user/xx/change/ --> Link for password change points to /admin/auth/user/32/password/ but you get redirected to//admin/password_change/

### Version or commit hash (if applicable)
6.1

### Steps to Reproduce
User with admin permissions / role

1. Admin
2. Users and groups
3. Users
4. Select one user (not currently logged in one)
5. In Password field click on this form link
6. Input old / new password
7. Click on Change my password

### Actual results
Password changed for currently logged in user.

### Expected results
Password changed for selected user

**Comment by atodorov** [comment]
This is intended functionality, not a bug. Users can change their own password or use the "Forget/Reset password" functionality from the login page.  

If you really insist on being able to change other peoples' passwords then use `manage.py shell` and `user.set_password()` function.

**Comment by atodorov** [comment]
This is stock django form which we can't adjust. I can try removing this field entirely if you are viewing the form for a different user, not yourself. I don't know how doable that is atm, need to check.
