### ISSUE TITLE
Test steps only can display 5 rows in test run view

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#622]
### Description of problem
Test steps only can display 5 rows in test run view

### Version or commit hash (if applicable)
6.2.1

### Steps to Reproduce
1. Some case has steps more than 5 rows
2. Add case to a test run
3. Run this case, check actions display

### Actual results
Test steps only can display 5 rows in test run view.
Setup, breakdown and Expected Results has same issue  
![case steps](https://user-images.githubusercontent.com/11469746/48756985-3750d180-ecd6-11e8-9e23-888ce0d54a44.jpg)

### Expected results
The maximum size of the display box should be larger.

### Additional info (Python traceback, logs, etc.)

**Comment by atodorov** [comment]
Similar to https://github.com/kiwitcms/Kiwi/issues/339

**Comment by chenchangjiang** [comment]
Maybe some difference. In that case, the issue is just the serial number from 10 should display a little to right, a minor issue. In this case, the display box only can display 5 rows text, max size is 5 rows in test run view. But in test plan case spread view or case edit view, the display box size large enough to display all row text. In my opinion, 5 rows seems too little.

Kindly have a check again? Thx.

![111](https://user-images.githubusercontent.com/11469746/48815460-93206680-ed79-11e8-9769-5f012d65d7f6.jpg)

**Comment by atodorov** [comment]
Test run page has been fixed meanwhile:
https://demo.kiwitcms.org/runs/703/

^^^ see CaseID 1715, first row.

Closing this one. Leaving #339 for the display inside Test Plan page.
