### ISSUE TITLE
The case text displays in a row without line feed but display normally when editing

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#623]
### Description of problem
The case text displays in a row without line feed but display normally when edting

### Version or commit hash (if applicable)
6.2.1

### Steps to Reproduce
1.  Create a new test case, without serial number then save it
2. Check case text display

### Actual results
The case text displays in a row without line feed. But if try to edit it, text display normally

### Expected results
The case text displays in several rows with line feed

### Additional info (Python traceback, logs, etc.)
Is there some display logic here? My PC is Mac OS.
1. If I create case with automated number such as 1. 2. 3... case text will display ok with line feed.
2. I import lots of cases via python script from xlsx file, and with line feed in steps or result. After importing, some case display ok and some display in a row. A little confused.

![111](https://user-images.githubusercontent.com/11469746/48761183-fe6b2980-ece2-11e8-8e7a-d630bc674d04.jpg)
![222](https://user-images.githubusercontent.com/11469746/48761199-03c87400-ece3-11e8-8d76-0f439d2e8160.jpg)

**Comment by atodorov** [comment]
I don't know if this is working as designed or an actual problem. I think it is by design.

The editor supports markdown do the shown text isn't a valid format for multi-line text. As a result it gets rendered as a single `<p>` tag in the HTML.

**Comment by chenchangjiang** [comment]
Yes. You are totally right. This editor use markdown format. Case with prefix number + dot + space is markdown lists, so display OK.

Seem you have fixed this? Change markdown to HTML? In future , we just use normal text and press Enter key, it will change to another line? Or still need use markdown format in editor?
