### ISSUE TITLE
No error when trying to add non-existing tag

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#625]
### Version or commit hash (if applicable)

Demo

### Steps to Reproduce

1. Create Test run
2. Go to Test Run page
3. Type anything in "Tag"
4. Click "Add Tag"
5. Nothing happens

If one checks developer console, the error can be found

    {"id": "jsonrpc", "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: Tag matching query does not exist."}}

However it should be displayed to the user directly (with clear explanation how to add new one)

**Comment by asankov** [comment]
when the API call executes successfully (no network error), but the API returns some kind of error the response looks like this:
```
{"id": "jsonrpc", "jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal error: Tag matching query does not exist."}}
```
however, in `tcms/statis/js/json.rpc`, the `success` handler looks like this:
```
success: function (result) {
            callback(result.result);
      },
```
so we swallow the error and the caller of `jsonRPC` cannot do anything with her.

A simple solution would be to change this code to:
```
success: function (result) {
            callback(result.result, result.error);
      },
```
in this case the caller of `jsonRPC` can use it like this:
```javascript
jsonRPC("TestRun.update", data, (res, err) => {
    if (err) {
        // failure
        alert(err)
    } else {
        // success case - do something with the actual response
        console.log(res)
    }
})
```

implementing the described changes, would allow us to fix all the places, where error handling is missing
