### ISSUE TITLE
internal error 500 when press on save new testrun

### ISSUE THREAD

**Issue by oritgaon** [kiwitcms/Kiwi#631]
WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

### Description of problem

can't save testrun

### Steps to Reproduce

1. install according to instructions at: https://kiwitcms.readthedocs.io/en/latest/set_dev_env.html
2. create test plan and add test cases
3. try to create test run for selected test case
4. press on Save

### Actual results
see internal error 500

### Expected results
test run should be created

### Additional info (Python traceback, logs, etc.)
1. tried to check the log according to ticket https://github.com/kiwitcms/Kiwi/issues/191
but I don't have permissions to open the log file inside the container.
2. checked the common.py file under Kiwi/tcms/settings and DEBUG is set to true (I didn't change it, this is how it was)

please let me know what information you need and how to make this to work.

**Comment by atodorov** [comment]
> install according to instructions at: https://kiwitcms.readthedocs.io/en/latest/set_dev_env.html

so first lets figure out which environment are you using. If you are using the devel environment you are not going to see a 500 page but instead the traceback on the console and in the browser.

So are you using Docker or the devel instance ?  In case of Docker see:
https://kiwitcms.readthedocs.io/en/latest/installing_docker.html#troubleshooting

> checked the common.py file under Kiwi/tcms/settings and DEBUG is set to true (I didn't change it, this is how it was)

Production uses `product.py` and devel mode uses `devel.py` both of which inherit from common.py and modify the DEBUG setting as well.

**Comment by oritgaon** [comment]
Hello, 

The problem was solved.

however, the DEBUG set to true (at product.py)  didn't show error message, I still get internal error 500
it only now prints outputs at the terminal. 

the error is the same as in ticket 191. 

I was able to get the error at the screen only by doing the following:

1. creating local_settings.py and set DEBUG to true under KIwi folder.

2. adcdding volume to docker-compose.yml file 
![image](https://user-images.githubusercontent.com/30828330/49071019-a7f77100-f235-11e8-9bc4-6a3d032eef17.png)

only then I was able to see the trackback


I have installed to production.

**Comment by atodorov** [comment]
OK, everything you describe (not being able to set DEBUG=True or being able to do so differently) is dependent on your local environment and how well versed you are in administering Django applications. There are many different way in which DEBUG=True can be accomplished as you have demonstrated.

Now please attach the traceback logs to this issue otherwise I have no idea what is going on or how to reproduce.

**Comment by oritgaon** [comment]
I don't have the log, but it mentioned 2 users instead of 1
looking at the users list I had the same user registered twice

after deleting the extra one,  the problem was solved
so you can close this ticket.

**Comment by atodorov** [comment]
OK, 2 users with the same address will crash things. This is not supposed to happen. If you can figure out how you ended up with the 2 accounts please share.

**Comment by trieutulong89** [comment]
Request Method: | POST
-- | --
2.2.8
OperationalError
(1366, "Incorrect string value: '\\xE1\\xBB\\x9F b\\xC3...' for column `kiwi`.`testplans_testplan`.`text` at row 1")
/venv/lib64/python3.6/site-packages/MySQLdb/connections.py in query, line 239
/venv/bin/python3
3.6.8
['/Kiwi',  '/venv/lib64/python3.6/site-packages',  '/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages',  '/venv/lib64/python36.zip',  '/venv/lib64/python3.6',  '/venv/lib64/python3.6/lib-dynload',  '/usr/lib64/python3.6',  '/usr/lib/python3.6',  '/venv/lib/python3.6/site-packages',  '/venv/lib64/python3.6/site-packages/tcms/core/lib']
Fri, 27 Dec 2019 11:08:05 +0000

This is my output errors, could you please help to fix this problem
