### ISSUE TITLE
RFE: Alphabetical sort for ModelAdmin FK fields for Component, Product and Version

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#633]
### Description of problem
Difficult to find expected items from drop-down menu when creating component, product or versions in management page

### Version or commit hash (if applicable)
6.2.1, I try it on https://demo.kiwitcms.org/

### Steps to Reproduce
Try to add Component, Product, Versions in admin -- everything else --management page
Component: 
Product filed
Initial owner filed
Initial qa contact filed

Product:
Classification filed

Versions:
Product filed

### Actual results
Difficult to find expected items from drop-down menu for step 1 filed, so many items

### Expected results
My suggestion is that items should be in alphabetical order, e.g. a b c d...then it easy to find

### Additional info (Python traceback, logs, etc.)
![111](https://user-images.githubusercontent.com/11469746/49054599-b04cad80-f22f-11e8-9443-e7069288c3ea.jpg)

**Comment by atodorov** [comment]
These are automatically generated forms by Django. The sorting of these fields can be overriden as shown here:
https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_for_foreignkey
