### ISSUE TITLE
Cannot filter all test runs for one product, ------ need be existed in drop-down menu as version

### ISSUE THREAD

**Issue by chenchangjiang** [kiwitcms/Kiwi#634]
### Description of problem
Cannot filter all test runs for one product, need select a specific build. ------ need be existed in drop-down menu as version

### Version or commit hash (if applicable)
6.2.1, I also try it on https://demo.kiwitcms.org/runs/search/

### Steps to Reproduce
1. Go to search -- search test runs
2. Select a product, check build filed display

### Actual results
One build is selected automatically, cannot filter all test runs for one product. I just want to see all build test runs status

### Expected results
------ need be existed in drop-down menu as version

### Additional info (Python traceback, logs, etc.)
![222](https://user-images.githubusercontent.com/11469746/49056504-e6d9f680-f236-11e8-80d8-57f69155874f.jpeg)

**Comment by atodorov** [comment]
In 6.6 the Build field contains "-----" which solves this issue. I'm not sure when that was solved, it's been resolved for some time now.
