### ISSUE TITLE
Can't add new user after initial setup

### ISSUE THREAD

**Issue by ichaldeak** [kiwitcms/Kiwi#642]
### Description of problem
Using a kiwitcms image built from latest source, when entering the add user page to add another user after initial configuration, I get an AttributeError at /admin/auth/user/add/ with value "'NoneType' object has no attribute 'pk'". Doesn't occur when pulling kiwitcms image from Docker Hub.

### Version or commit hash (if applicable)
Latest Source from master (30/11)

### Steps to Reproduce
1. Build kiwitcms image from latest source (make docker-image)
2. Initialize containers (db and first user - migrate and createsuperuser)
3. Go to admin/auth/user/ to add a new user

### Actual results
Internal Server Error (500) 

### Expected results
Display the add user page with empty fields for username, password etc.

### Additional info (Python traceback, logs, etc.)
http://dpaste.com/3JGF36Y  (traceback)

**Comment by atodorov** [comment]
Thanks for this report. That is a legitimate bug and I've opened a PR with a fix and couple of tests as well. I will merge it as soon as CI reports PASS. 

We are going to build a new docker image pretty soon as well but it appears you are already building the image yourself.
