### ISSUE TITLE
How to use Gitlab Integration

### ISSUE THREAD

**Issue by ertw0405** [kiwitcms/Kiwi#648]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
Cannot create issue on Gitlab with Private Token

### Version or commit hash (if applicable)
master from github

### Steps to Reproduce
I wonder what to fill in to the following fields on bug tracker:

1. Name
2. URL format string
3. RegExp for ID validation
4. Type (Gitlab I suppose :)
5. Base URL
6. API URL
7. API username (Should be blank I suppose, according to source code)
8. API password or token (Should be generated in Personal Access Token with api permission granted)

Assuming my group is MY_GROUP and my project name is MY_PROJECT. Current issues on Gitlab the URL is https://gitlab.com/MY_GROUP/MY_PROJECT/issues

I also tried to use curl curl https://gitlab.com/api/v4/projects/MY_GROUP%2FMY_PROJECT/issues?private_token=XXXXXX and I can see all issues from MY_PROJECT

Thanks and please kindly advise.

### Actual results
N/A

### Expected results
N/A

### Additional info (Python traceback, logs, etc.)
N/A

**Comment by atodorov** [comment]
See this answer:
https://stackoverflow.com/questions/53595966/kiwi-tcms-gitlab-bug-tracker-integration

The documentation should be clear about what you need and what you don't.

Next time please ask support questions on StackOverflow with the kiwi-tcms tag as prompted by the issue template.
