### ISSUE TITLE
RFC: Remove existing reports

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#657]
We are planning to remove the existing reports feature because they are not well designed and the code internally is a huge blob that can't be extended very easily. Kiwi TCMS team would like to reimplement existing functionality that folks find useful, add new types of reports (incl. nicer graphics and UI) and make it possible for the reporting sub-system to be more easily extendable.

Phase out is planned to begin after 1st March 2019!

Until then we are looking for feedback from the community:

1) Which of the existing reports do you use? What kind of decisions do you make based on them? 

2) What kind of reports/decision you have to make that currently do not exist or you feel like the information is not easy to obtain ?

**Comment by Prome88** [comment]
1. 
Currently we only rely on:
- Test plan progress bar
- Overall report -> Bug list / View all in Issue Tracker

2.
Managing team workload -> some kind of real-time metrics to show progress of individual tester.
Managing team predictability -> re-implementation of time tracking and adding a metric that would predict the estimated end of test run etc.

**Comment by essoftdev** [comment]
Great, because I've to say the reports... are pretty weak in General

** Test Run Report **
It's very useful to send the feedback to the developer but I think it's not very clear, for example Red color to mark the non-passed tests... will be very useful to just skip the passed ones

We started using the APP few weeks back, so I can not give you much more feedback, but soon I'll post more.

Thanks!

**Comment by okainov** [comment]
Current (okay, maybe not so current, but from Kiwi from April 2018) reports are really weak, not informative and almost useless.

However, it's still better than nothing. I'd suggest that you do not remove it unless you have proper replacement (probably designed from scratch with nicer templates and content)

**Comment by atodorov** [comment]
> However, it's still better than nothing. I'd suggest that you do not remove it unless you have proper replacement (probably designed from scratch with nicer templates and content)

Oh we are removing those. They are a mess internally and we can't keep them around for much longer. There's no question about it. The removal will be gradual, not everything at once!

If there are specific reports that you use please tell us about them, but I'm certain that is not *all* of them! Whatever people don't care about will go away.

We're interested in knowing which reports and for what kind of purpose/information you are using them so we can redesign those and make the better.

**Comment by okainov** [comment]
@atodorov  I use only my own reports that we created in our fork =)

**Comment by atodorov** [comment]
@okainov can you share more details what these reports are ? Screenshots, some description of what kind of info you are looking for, etc. If you can't share internal information that is understandable but if you can let's hear it.

**Comment by okainov** [comment]
@atodorov 

Main template for our reports is table view, where each cell of the table is a test run (link).

For the "release", it's something like this - each "build" (mind that it's not the same as none of "Product version" nor "Build" but more like some substring of "Build") is tested against different OSes (which we get from Environment variable which you have removed in master already)

![image](https://user-images.githubusercontent.com/918446/50888047-01d28580-13f5-11e9-850d-545ae822ccb6.png)

Then for each "build" you have more detailed page where the upper part is just the row from the table above, but below you have some pivot table with test results for components included to this "build" (as before, each cell is a link to test run if exist). As I already told you several times in previous issues, we heavily use Environment variables to set up these links between test runs and components included.
![image](https://user-images.githubusercontent.com/918446/50888429-eddb5380-13f5-11e9-876c-06a2a256ef7c.png)

**Comment by saifulrip** [comment]
Email confirmation or email notification is not working when installed KIWI on Docker.

**Comment by atodorov** [comment]
> Email confirmation or email notification is not working when installed KIWI on Docker.

@saifulrip this isn't related to reports so use StackOverflow for this type of questions.

**Comment by saurabhdv** [comment]
It would be great if we can back track the test cases that are failed, as link to test case or test case id

**Comment by DanielaPopova** [comment]
Hi guys,
I'd like to make a suggestion (if you're not already considering such feature, of course) to make it possible for a test report to be exported in some kind of file format, html, xml etc.

**Comment by atodorov** [comment]
> make it possible for a test report to be exported in some kind of file format, html, xml etc.

@DanielaPopova  can you elaborate more on this? The existing format is HTML so this is already covered. Why do you need XML and how are you going to use it ?

**Comment by DanielaPopova** [comment]
Say I need to send a KIWI test report to a client or upload/attach that report in some other system, so what I meant is an easy way to do that - downloading/exporting it in some kind of file format, like html/xml, archive it and use it. Currently I can show that report by sending a link to it, the person I'm sending it to has to have an account, which is not always needed and so on.

**Comment by atodorov** [comment]
@DanielaPopova, for the record we are talking about this https://demo.kiwitcms.org/runs/776/report/, right ?

> Currently I can show that report by sending a link to it, the person I'm sending it to has to have an account, which is not always needed and so on.

we can improve the layout and you can use 'Print to PDF' which will be good for sending the report to a customer, manager or other stakeholders. In fact this page prints relatively well as it is and the new UI with Patternfly prints even better so this use-case should be solved.

> Say I need to upload/attach that report in some other system, so what I meant is an easy way to do that 

Again, if it is for human consumption Print to PDF will do just fine. If it is for machine consumption we need more details.

**Comment by DanielaPopova** [comment]
Yes, it is for human consumption and a "fancier" pdf would be great! Thank you for your response.

**Comment by HelgaOR** [comment]
Hi,
We are just moving to Kiwi and do not have any usage statistics yet, but we do need reports to:
1. show current progress on test plan (I believe current "Test Execution Report" does that),
2. show progress over latest test runs (or builds), including filed bugs, so we can tell if builds are getting better or worse from test perspective,
3. some statistical data like "test cases that fail most often", "average failed test cases per suite", maybe some graphical information like this,
4. also there is a separate scenario when we need to find out who ran the test case last and when it was done. 

We mostly want to get some meaningful statistical info and test case/test suite dynamics so we can see current problems and address them.

**Comment by atodorov** [comment]
@Prome88  a few questions about your very first comment:

> Currently we only rely on:
>    Test plan progress bar

I think you mean Test Run progress bar. See picture and tell me if I am correct or show me what do you mean.

![testrun_progres_report](https://user-images.githubusercontent.com/1002300/53420433-76cd3f00-39e4-11e9-95fc-cde875e5ce09.png)

>    Overall report -> Bug list / View all in Issue Tracker

Which page is this? I'm not sure I follow.

**Comment by atodorov** [comment]
@HelgaOR :
> show current progress on test plan (I believe current "Test Execution Report" does that),

Do you mean the progress bar for Test Run as shown in the screenshot above or something else? Point me to what you mean if different.

**Comment by atodorov** [comment]
@essoftdev 

>  I think it's not very clear, for example Red color to mark the non-passed tests... will be very useful to just skip the passed

To be clear: you mean that we are using only 2 colors (red for bad results) when there are several negative statuses (FAILED, BLOCKED, ERROR) ? Your objection is to how the visual information is presented, is this correct ?

**Comment by HelgaOR** [comment]
@atodorov :

> Do you mean the progress bar for Test Run as shown in the screenshot above or something else? > Point me to what you mean if different.

Yes, I meant progress bar for Test Run and report that is accessed by clicking "Report" button below it. Report is more readable then Test Run main page, in my opinion.
I'm new to your product and may use some terms incorrectly, so please forgive me if this is the case.

**Comment by Prome88** [comment]
a) Yes, you are correct. I've ment Test run progress bar.

b) /runs/$ID/report/ -> Sections Bug list and View all in Issue Tracker

**Comment by atodorov** [comment]
New feature specs have been defined at http://kiwitcms.org/blog/kiwi-tcms-team/2019/03/03/legacy-reports-become-telemetry/.

Please use the comments in the blog to follow up.  I will open individual issues for features where we need more information and CC those of you who have provided opinions.

The only report capability which isn't yet defined in the post above is the `Environment matrix report` as described by @okainov. I have the feeling this should be an extension of the TestRun status matrix telemetry but we have to implement it first to see how it can be extended with environment data.

This issue will be closed once the legacy reporting code has been removed.
