### ISSUE TITLE
Add test case to test plan - cannot perform normal search after quick search

### ISSUE THREAD

**Issue by alevas** [kiwitcms/Kiwi#663]
### Description of problem
When adding a test case to a test plan, if an attempt at Quick Search is made, the Normal Search option cannot be accessed. Also, the Reset button does not clean the search fields.

### Steps to Reproduce

1. Open a test plan
2. Go to Case menu
3. Select "Add cases from other plans
4. Perform a Quick Search with random ID
5. Try to select Normal Search
6. Try to Reset your search fields.

### Actual results
You cannot access the Normal Search option, neither is the Reset button doing anything.

### Expected results
Access the Normal Search option. By pressing the Reset button while on Quick search, clean the search fields.

**Comment by atodorov** [comment]
Notes:

* It doesn't matter if the Case ID exists in the DB or not. After the quick search is reloaded the links on the page seem to break.
* The Reset button not working is related to the fact that the page reloads and the HTML after reload contains the search values, thus the pristine, non-modified state of the form (according to the browser) contains the previous search values. If you try and modify the search parameters and then click Reset button the form is returned to the initial state after the page was reloaded.

* This search page and its forms will be rewritten using the Patternfly UI library and we intend to re-use the existing widgets from Search -> Test Case page templates. It will likely solve some of the issues but we need to test for the rest when doing the change.
