### ISSUE TITLE
The drop-down list "Category" in Test plan display no values

### ISSUE THREAD

**Issue by OddanN** [kiwitcms/Kiwi#674]
### Description of problem
Quick filter does not work by category when viewing test cases in the test plan

### Steps to Reproduce

1. Open any test plan (https://demo.kiwitcms.org/plan/1399/12321#testcases)
2. Switch to tab "Cases"
3. Click "Show filter options"
4. Try to make a filter by the value of the "Category"

### Actual results
There are no filter values in the Category dropdown list

### Expected results
The drop-down list "Category" displays the values of the corresponding field in the cases.

### Additional info (Python traceback, logs, etc.)
In the browser console the following information:

[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by OddanN** [comment]
With drop-list "Compont" same issue

https://gifyu.com/image/wwBY

**Comment by JTR87** [comment]
Yes, confirmed the bug.
When is the bug expected to be fixed?

**Comment by atodorov** [comment]
> When is the bug expected to be fixed?

Whenever we get around to it. If you need to have it fixed faster you can try sending us a pull request.

**Comment by marion2016** [comment]
> > When is the bug expected to be fixed?
> 
> Whenever we get around to it. If you need to have it fixed faster you can try sending us a pull request.

i have sent a PR
