### ISSUE TITLE
import kerberos error

### ISSUE THREAD

**Issue by shadeimi** [kiwitcms/Kiwi#690]
HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
the import kerberos line in xmlrpc.py is not fulfilled by OS dependencies

### Steps to Reproduce

1. Install the devel dependencies as described into the wiki page
2. the import kerberos command will fail

### Actual results
import error

### Expected results
the library is available

### Additional info (Python traceback, logs, etc.)
Under ubuntu linux, execute the following to solve:

- apt install krb5-config libkrb5-dev libssl-dev libsasl2-dev libsasl2-modules-gssapi-mit
- (kiwiEnv) pip install kerberos

**Comment by atodorov** [comment]
This import is in the client-side library which shouldn't have to do anything with the server side application. Can you explain in more details what are you trying to do ?

**Comment by atodorov** [comment]
fixed as part of https://github.com/kiwitcms/Kiwi/pull/756
