### ISSUE TITLE
Django test runner reporting plugin 

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#693]
Kiwi TCMS needs a customized test runner for Django based projects. This runner will execute the Django test suite as normal and then report the results into Kiwi TCMS database via our API.

**Getting started docs**
- https://kiwitcms.readthedocs.io/en/latest/plugins/automation-frameworks.html
- https://kiwitcms.readthedocs.io/en/latest/contribution.html
- http://kiwitcms.org/blog/atodorov/2018/11/05/test-runner-plugin-specification/

**How Django test discovery & execution works**
The test runner can be controlled with the `TEST_RUNNER` setting, which by default points to
`django.test.runner.DiscoverRunner` class.

`./manage.py test` will initialize the test runner class and execute `.run_tests()` method which does the heavy lifting of setting up the test environment and executing the test suite. At the end it calls `.suite_result()` with the results.

`.suite_result()` and possibly `.run_tests()` look like possible methods to override and perform the reporting of results to Kiwi TCMS. For inspiration see https://github.com/kiwitcms/tap-plugin and https://github.com/kiwitcms/junit.xml-plugin

**Definition of done**
- a class called `tcms_django_plugin.TestRunner` which inherits from `DiscoverRunner` and overrides methods to compile information of what has been tested and what the results were
- then feed that information to an instance of `tcms_api.plugin_helpers.Backend` which encapsulates the communication and behavior logic around the TCMS DB, see referenced plugins above
- ^^^ work is created in a separate repository
- README.rst contains information about installatin & configuration (see plugin references above)
- repository contains setup.py file similar to references above
- repository contains tests - a nice candidate is to have a sample django project in the same repository which could be used as a driver, see https://github.com/kiwitcms/tenants/tree/master/test_project
- repository uses GPLv3 license
- code review & issues reported from Kiwi TCMS maintainers have been resolved
- repository has been transferred under https://github.com/kiwitcms organization

**Note:** comment on this issue with a link to your repository as soon as you have something working!

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Comment by brymut** [comment]
May I please get assigned this?

**Comment by atodorov** [comment]
> May I please get assigned this?

Go ahead please.

**Comment by atodorov** [comment]
@brymut I see in your profile that you are from Kenya. You may also help us with the Swahili translation if you want, see issues.

**Comment by brymut** [comment]
I’ll look into those too, no problem

**Comment by brymut** [comment]
Hi again @atodorov, took longer than expected but I think I've got something can be looked at for some initial feedback on [tcms-django-plugin](https://github.com/brymut/tcms-django-plugin).

Still working on adding to testing, the README and compatibility with subtests, however, any feedback would be appreciated on the current progress if you've got some time to spare.

**Comment by atodorov** [comment]
I will review & comment/open issues directly at https://github.com/brymut/tcms-django-plugin

**Comment by atodorov** [comment]
@brymut I have released the plugin on PyPI https://pypi.org/project/kiwitcms-django-plugin/ and I consider it ready for consumption. 

In order to close this PR and claim the bounty please update the relevant documentation section and close this issue via commit log message.
