### ISSUE TITLE
RFC: py.test reporting plugin

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#694]
This plugin will be able to parse the results from an automated test execution with Django's test-runner and send them to Kiwi TCMS.  If you would like to use such functionality vote with a :+1: reaction (top-right corner of this comment) or leave your feeback below.

If you would like to help the test-runner plugin specification can be found at
http://kiwitcms.org/blog/atodorov/2018/11/05/test-runner-plugin-specification/

**Comment by atodorov** [comment]
@Stranger6667 is this something you may be interested in ?

**Comment by Stranger6667** [comment]
Hej Alex! Sounds cool :) I'm definitely interested, will take a look into the spec tomorrow

**Comment by Stranger6667** [comment]
Hej again! :)
I want to write the plugin :) Could you, please, create a repo for the plugin and give me write permission?
I have an implementation idea and can start next week - spec seems good for me :)

**Comment by atodorov** [comment]
Hi Dmitry,
thanks for the good news. Repo is at https://github.com/kiwitcms/pytest-plugin. I've sent you an invite.

**Comment by atodorov** [comment]
I am closing this issue b/c we're tracking this effort in a separate repository. Watch the repository from the previous comment if you want to keep up with the news.
