### ISSUE TITLE
RFC: Bug-tracker functionality inside Kiwi TCMS

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#699]
There's an idea for Kiwi TCMS to be able to keep track of reported bugs directly inside the system. The functionality will be minimal, similar to what GitHub Issues provides.  This will be useful to small teams who do no need tons of functionality (sort of like JIRA) or do not want to deploy a separate system for bug-tracking.

Please vote with a :+1: reaction (top-right corner) if you find a feature like that useful!

Use the comments below to describe the features and behavior you imagine this bug-tracker to have.

**Comment by okainov** [comment]
There are dozens of small free and even open-source bug trackers (see [MantisBT](https://www.mantisbt.org/) for example). Implementation of your own wheel seems like a big overhead with extra maintenance afterwards.

However, if you want Kiwi to go beyond TCMS in general, you may consider making some kind if plugins\extensions (in separated repos, with separated codebase), and here some basic bug tracker functionality could be an okay-idea for extension. So if one wants to install it, one can go to, lets say,  admin panel - plugins - bug tracker - activate - and get it automagically.

**Comment by kryskool** [comment]
Hi @atodorov 

Why don't use [entry_point](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) to allow plugin creation ?

We must convert [existing plugins](https://github.com/kiwitcms/Kiwi/tree/master/tcms/issuetracker) to a separate plugin with name like 

- ktcms-plugin-issuetracker-github
- ktcms-plugin-issuetracker-jira

You can see an example at this [address](https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/entry_points_and_plugins.html)

Regards
