### ISSUE TITLE
Improvements for TestCase search page

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#715]
- Make it possible to search by date (TC created before and/or after)
- Show Component as column in search results (Refs #123)
- Show Tags as column in search results (Refs #123)

- The widget for Automated doesn't work - it relies on the field having a query set but this field instead has choices.  It also must become a bootstrap switch widget, not a select. (May need related backend work for the is_automated field) and a test!

If there is no space on the screen we have to figure out something.

**Comment by asankov** [comment]
> The widget for Automated doesn't work - it relies on the field having a query set but this field instead has choices. 

This has been fixed recently. Currently we have 3 radio buttons (automated, manual, both) and are working as expected. 

> It also must become a bootstrap switch widget, not a select. (May need related backend work for the is_automated field) and a test!

I will implement this. I was thinking of having two separate switches - one for AUTOMATED and one for MANUAL. If one of them is selected, only such cases will be shown, if both are selected all cases will be shown (IMO this should be the default state). @atodorov , what's your take on this?

**Comment by atodorov** [comment]
> I will implement this. I was thinking of having two separate switches - one for AUTOMATED and one for MANUAL. If one of them is selected, only such cases will be shown, if both are selected all cases will be shown (IMO this should be the default state). @atodorov , what's your take on this?

Leave it as radio button. 2 switches with 2 options yields 4 possible combinations. What happens when both are not selected? What is your filter then? 

Let's leave these as radio buttons for now.


NOTE: I've observed that the search pages are showing columns which don't match all of the search terms. I'm not sure if we need all of the columns, or just the most important ones. For example Test Case search is not showing Product while the Category and Tags column may not be needed if they are not used.

I'm leaving this as a comment here. My preference leans towards fetching all fields from the DB, showing only the ones we think are important and configuring some option to DataTables to let the user change which columns are displayed. Hopefully DataTables will be smart enough and keep this in cookies.

**Comment by asankov** [comment]
Yes, I get your point. So this can be closed once #748 and #749 are merged
