### ISSUE TITLE
Test plan - User tries to add test case with status different from confirmed - error msg design

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#718]
### Description of problem
Design of error message is a bit broken.

### Version or commit hash (if applicable)
6.4 @ demo

### Steps to Reproduce

1. Open test plan https://demo.kiwitcms.org/plan/1468/break-me-gently#testcases
2. Click Show filter options
3. Tick all statuses
4. Click Filter
5. Select both cases (one confirmed and one proposed)
6. Run
7. Click Create new test run
8. Click Save

### Actual results
![image](https://user-images.githubusercontent.com/25688732/51320861-78106100-1a61-11e9-82d2-3780cf69092b.png)

### Expected results
Best option: Prevent creation of adding test cases to test plan from test plan view if their status != Confirmed.

Second best option: Fix the design (two table borders are unnecessary) of the error message and actually describe what is wrong with selected test case.

**Comment by atodorov** [comment]
Yes, this looks like a bug. The table below the Save button is supposed to show a red border with a helpful error message. This is a check for this in the backend view and also a check for it in the template (search for `disabled_cases`)
