### ISSUE TITLE
[DEMO] Environment cannot be set for test plan

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#73]
### Description of problem

Cannot use environment groups

### Component (web, API, etc)

Web

### Version or commit hash (if applicable)

Demo https://demo.kiwitcms.org

### How often reproducible

Always

### Steps to Reproduce

1. Create some env properties
2. Create some env group
3. Go to "New test plan"
4. Make sure environment groups combobox exists, select env group
5. Press "Create"
6. Press "Edit"
7. Make sure combobox value is "-----", no env group was actually set.

### Actual results

Combobox value is "-----", no env group was actually set.

### Expected results

Env group should be set

Looks like regression since in Nitrate it was fine. Or maybe DEMO issue, I haven't checked it with real instance

**Comment by atodorov** [comment]
Thanks for the bug report. I was able to reproduce. This also looks like a permissions issue. Will look further into it.

**Comment by atodorov** [comment]
@GodfatherThe this and #74 have been fixed, thanks for spotting the problems. I will update the demo in a few days. Note: when you see a changelog update on GitHub that means the demo has been updated.
