### ISSUE TITLE
new linter: Do not use label in form fields

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#738]
Our team has decided that template labels must be placed in the HTML and not defined in form fields. Most of the existing ones are not translated and many of them may not be used b/c the HTML template has its own opinion. Since the HTML is what the user sees we prefer all labels to be in the HTML, not in the python code.

Kiwi TCMS needs a custom kiwi_lint/ checker which will discover all `label` arguments to form field classes and warn about them.

**Definition of Done**:
- new checker class under `kiwi_lint/` which implements the necessary pylint machinery
- Can be relatively simple checker. It should be sufficient to raise a warning when a function call contains a parameter with the name `label`. If this is too generic we can refine it later
- All code review passed & PR merged

Here's me explaining how to write pylint plugins:
- https://www.youtube.com/watch?v=3CkSKUNMLJc
- https://www.youtube.com/watch?v=D1wLFyazTRM

*This issue is part of Kiwi TCMS open source bounty program. For more information see the link(s) in [bounty-program milestone](https://github.com/kiwitcms/Kiwi/milestone/4)*

**Comment by brymut** [comment]
Made an attempt at adding a lint check at https://github.com/kiwitcms/Kiwi/pull/1742
