### ISSUE TITLE
One-click test execution status setting and commenting is missing

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#74]
### Description of problem
In Nitrate it was really nice that one could really easy set test execution status and and comment. For some reason, I didn't find it in Kiwi Demo. See screenshot
![image](https://user-images.githubusercontent.com/918446/32044316-83b70f0c-ba3d-11e7-83eb-5d6fc380a643.png)

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)

Demo

### How often reproducible
Always

### Steps to Reproduce

1. Create test plan, test case and test run
2. Execute test run
3. Check test execution UI element

### Actual results

No possibility to set status and\or add comment in one click

### Expected results

One-click setting of Status and adding comment should be possible

### Additional info
Looks like regression

**Comment by atodorov** [comment]
OK, I think I found your username and this is probably a permissions issue. I will take a deeper look into it later today
