### ISSUE TITLE
Users with duplicated emails lead to error 500 Internal server error during test run creation

### ISSUE THREAD

**Issue by nikolaykolev** [kiwitcms/Kiwi#746]
### Description of problem
An internal server error is thrown when the default tester is with an email that is already used by another user in the system.

### Version or commit hash (if applicable)
b910fc98e6e357b9a2eb390dfcaa4d400137cee5

### Steps to Reproduce

1. Install Kiwi using docker
2. Make a new account trough the Kiwi interface (the first account)
3. I did not receive a confirmation on my email
4. Created the admin account trough the command line because of that (used the same email as above)
5. Logged in with the admin account
6. Created a test case, added it to a test plan
7. Tried to create a test run for this test plan and assign it to the admin as default tester
8. Upon trying to save the test run, error 500 appears

### Actual results
500 Internal server error

### Expected results
Created test run

### Additional info (Python traceback, logs, etc.)
Possible duplicate of #463 which is resolved, but it seems it's the same
Duplicate of #631 which is resolved, but the exact steps were never posted

The resolution in my case is the same as in #631. I did have the 2 users with the same email address. After changing 1 of the emails everything is fine.

**Comment by atodorov** [comment]
> I did not receive a confirmation on my email

If you haven't configured email transports in the docker image there's no way you will receive this email. There is a big fat warning section in the documentation about this.

Once you get the same email address assigned to 2 user accounts everything gets screwed and there's nothing we can do about it. Start over and configure your first user appropriately.

**Comment by nikolaykolev** [comment]
Indeed it is in the configuration, but I should not be able to create 2 users with the same email. I'm not complaining about the internal server error. The system should not let me do that ...

**Comment by nikolaykolev** [comment]
@atodorov I think this can help if you decide to prevent this from happening again: https://stackoverflow.com/a/42491469
It happened a few times already so it will happen to other people in the future too ...
