### ISSUE TITLE
Test case - executions show non-existing user

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#765]
### Description of problem
Test case page shows wrong test execution history.

### Version or commit hash (if applicable)
6.5

### Steps to Reproduce

1. Open one test case which was used in test runs on our local KiwiTCMS instance
2. Expand Executions tab

### Actual results
![image](https://user-images.githubusercontent.com/25688732/52210526-9bbc0f80-2887-11e9-8dde-61b8a3da5243.png)

### Expected results
Proper data shown as in 6.4.

**Comment by Prome88** [comment]
Proper user is shown, but the timestamp is still in cyrillic datetime format.

**Comment by atodorov** [comment]
@Prome88 thanks for catching these. I've also fixed a problem when displaying the new TestCase page and language is different than English. Unfortunately we need a PR merged in Django to be able to test properly and find other places where that may break.
