### ISSUE TITLE
Search - Test cases - Minor GUI / UX issues

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#767]
### Description of problem
Minor GUI / UX issues

### Version or commit hash (if applicable)
6.4 and 6.5, possibly even older versions

### Steps to Reproduce

1. Search
2. Test case
3. Filter test cases by all options in Automated

### Actual results
Issue 1:
GUI always shows 76 pages of returned results (instead of actual number of filtered out pages), if user clicks on Last page button it only goes to appropriate number.

Yes:
Goes to page 12 / 76
![image](https://user-images.githubusercontent.com/25688732/52211251-a24b8680-2889-11e9-8fe2-eb5fc2e982fa.png)

Buttons Next, Last page are clickable but unusuable.

No:
Goes to page 5 / 76
![image](https://user-images.githubusercontent.com/25688732/52211284-bd1dfb00-2889-11e9-823e-a65647f53a52.png)

Buttons Next, Last page are clickable but unusuable.

Both:
Goes to page 76 / 76

Issue 2:
Input field for summary has placeholder text "Test run summary" which is incorrect as it searches via test case summary.

![image](https://user-images.githubusercontent.com/25688732/52211465-3d446080-288a-11e9-8e36-4ec678c69cdd.png)

`<input id="id_summary" type="text" class="form-control" placeholder="Test run summary">`

### Expected results
Issue 1: GUI shows the appropriate number of returned search results pages.
Issue 2: Show text based on search page - e.g. "Test case summary"

**Comment by atodorov** [comment]
> GUI always shows 76 pages of returned results (instead of actual number of filtered out pages), if user clicks on Last page button it only goes to appropriate number.

can you reproduce on https://demo.kiwitcms.org b/c I can't ? Not sure how this is happening. I see 95/95 pages currently.


> Buttons Next, Last page are clickable but unusuable.

Ack, when on the last page buttons next/last page are clickable and they should be disabled. Same should be for buttons on the left when on the first page.

**Comment by Prome88** [comment]
On demo:

Show all automated cases:
![image](https://user-images.githubusercontent.com/25688732/52212212-446c6e00-288c-11e9-9d41-a738face2ba8.png)

Show all manual cases:
![image](https://user-images.githubusercontent.com/25688732/52212280-636b0000-288c-11e9-8459-62cbd6ed6ffe.png)
