### ISSUE TITLE
Comment should be optional for test case run

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#77]
### Description of problem
Cannot set test case run status without a comment

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
04ee63372bac82dd614dc44ba20a10e14ae4016e

### How often reproducible
Always

### Steps to Reproduce

1. Create test-pan-case-run
2. Go to test run
3. Go to test case run
4. For test case run, click icon with result status (i.e. green OK checkbox)

### Actual results
Error "Please fill out this field" appear near "Comments"
Numbers in upper statistics table were changed
![image](https://user-images.githubusercontent.com/918446/32107728-c70e79d2-bb2f-11e7-9633-8da74f68e0f0.png)

### Expected results
Status should be recorded either w\o comment if it's empty or with comment, if it's not empty.
Numbers in upper table should be changed only in case when actual status change was performed.

### Additional info
Possible solution - make it optional only for "Success" status

**Comment by atodorov** [comment]
I will look at the status table issue, looks like a bug. 

I'm still not sure if we want to make comments optional. If they are optional there will be people who simply set the status and forget/don't bother to comment even on failure. I've seen people do this on a regular basis. Then it becomes impossible to figure out what went wrong unless you talk to them or read the bug reports.

**Comment by GodfatherThe** [comment]
Right, that's what I mentioned in "Additional info". Maybe it makes sense to improve the behavior:
- For "Passed" status - no comment should be required. Sounds logical - it's fine, what else do you need?
- For other statuses - comment is required to explain, why this status was set. 

"Failed" is discussible, since there is "Bugs" field, so it tester submits a bug, what else should he\she write in comment? "Test failed, see issue QQQ-1"?
