### ISSUE TITLE
create test case within test plan - test case is not associated with any plan

### ISSUE THREAD

**Issue by supranov** [kiwitcms/Kiwi#777]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
create test case within test plan - test case is not associated with any plan

### Version or commit hash (if applicable)
v 6.5

### Steps to Reproduce

1. On dashboard, open one of your test plan (for example: API testing on Springboot)
2. Under Case button, select Write new case
3. Under Summary field, there is link of test plan (API testing on Springboot). Type new test case
4. Click Save button

### Actual results
No records found (in Test plans summary)
![screenshot from 2019-02-08 16-48-21](https://user-images.githubusercontent.com/6009336/52470806-be209680-2bc1-11e9-9e2c-1a2afdce7cb8.png)

### Expected results
a test plan (API testing on Springboot) listed on Test plans

**Comment by atodorov** [comment]
This is a known issue in version 6.5, already fixed in master branch.
