### ISSUE TITLE
Special symbols in test run name cause search failure

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#78]
### Description of problem
Looks like special symbols in test run name is not being escaped properly

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
04ee63372bac82dd614dc44ba20a10e14ae4016e

### How often reproducible
Always

### Steps to Reproduce

1. Create Test run with "\\" symbols in the name i.e. "Test Product with Windows\Chrome"
2. Try to search this test run by product
3. Make sure error will appear
![image](https://user-images.githubusercontent.com/918446/32109495-2d3ebfa0-bb35-11e7-9719-daf872898724.png)

### Actual results
Error appears

### Expected results
Test run should be found

### Additional info
Maybe the same error exists for other fields as well

**Comment by atodorov** [comment]
Confirmed the problem, however the quotes are not the issue, the backslash character is! As a workaround you can use forward slash (/) or something else as a delimiter.

**Comment by GodfatherThe** [comment]
Yes, it was a GitHub bug. In my initial text there was quote-slash-quote symbols, but slash disappeared for some reason. Now I've updated the text

**Comment by atodorov** [comment]
Fixed in #96 but commit log wrongly refers to #79 instead.
