### ISSUE TITLE
Design issue :: Print Test Plan

### ISSUE THREAD

**Issue by essoftdev** [kiwitcms/Kiwi#798]
### Description of problem
When printing a a test plan, the test cases is not fitting with the 100% of the page. So it's printing more pages than required

### Version or commit hash (if applicable)
5.6.3

### Steps to Reproduce

1. Go to a test plan
2. Click on "Print Plan" button

### Actual results
See that the test cases are rendered in one small column
![seleccion_042](https://user-images.githubusercontent.com/24506244/52703100-e1f72a00-2f7d-11e9-9e5c-52adb4f88ec3.png)

### Expected results
The test cases text should be rendered fitting the 100% of the page

**Comment by atodorov** [comment]
> The test cases text should be rendered fitting the 100% of the page

Reformatting is a bad idea. Latest versions support Markdown formatting which may include source code, message examples or what not. We are going to render the HTML that comes from the Markdown renderer and not touch it at all.


I see your version is very old. Can you transfer your test case/test plan to https://demo.kiwitcms.org and see how the print page looks like there?

**Comment by atodorov** [comment]
> 5.6.3

That's 6.5.3 I believe looking more closely at your screenshot. The problem was in a CSS width: 25%. Fix will land shortly.

**Comment by essoftdev** [comment]
> > 5.6.3
> 
> That's 6.5.3 I believe looking more closely at your screenshot. The problem was in a CSS width: 25%. Fix will land shortly.

Sorry, My hands sometimes goes too fast. Yes I'm using latests, 
and thanks for taking care!

Regards
