### ISSUE TITLE
Add simple possibility to use test case run notes

### ISSUE THREAD

**Issue by GodfatherThe** [kiwitcms/Kiwi#81]
### Description of problem
There is already field TestCaseRun.notes, and it's even being displayed at some pages, but I was not able to find any way to edit it. Is it possible to have some textbox in test case run window (see screenshot)? And surely possibility to search\filter by this field

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
04ee63372bac82dd614dc44ba20a10e14ae4016e

### How often reproducible
Always

### Additional info
![image](https://user-images.githubusercontent.com/918446/32112843-ba48a86c-bb3e-11e7-9aca-6a0d5dbda30b.png)

**Comment by atodorov** [comment]
I need to check what the TestCaseRun.notes field was originally intended for and how it is currently used. Maybe it isn't used at all. There are two different note fields as well:

- one is attached to the TestRun model and you can add notes related to the entire execution for a particular version aka the current test run you are testing
- then there is a TestCase.notes field as well. This is for adding notes to the test case itself. This is mostly intended for things which don't fit into Setup/Expected results sections. 

Test cases also have tags and components which are visible in the expanded widget on the test run execution page. Aren't tags a better fit for what you are trying to do ?

**Comment by GodfatherThe** [comment]
No, I'm talking about TestCaseRun.notes. So neither of Test Run nor Test Case note. For me it would bу great to see exactly note related to TestCaseRun.

**Comment by atodorov** [comment]
Can you describe how a TestCaseRun note will be different than a TestCaseRun comment ? If possible can you give an example of a test case in your team and what goes into the notes field and how the team uses that information.

**Comment by GodfatherThe** [comment]
Notes vs comments - it's more or less the same, but I can hardly imagine possibility of searching by comments. In the same time, search by notes is pretty easy since it's just one text field.

Example - as I wrote personally before, our use case includes execution of each test on different environment (i.e. OS+Browser+Version of 3rd-party library). We consider creation of dozens test runs more like workaround'ish way. But since I understand, that it's more architectural change and even if decided, it can take time to implement properly, so I'm looking for other workarounds. And I think we can just simple text field (notes) to specify our test environment in given format.
Concrete artificial example:
>ID=1; Test that web page can be open. 
More or less good test and test doesn't imply any restrictions.
Test run (only one!)
> Testing for release 1.0.1
Test Cases Run belonging to this run:
> 1 with Windows, Chrome with lib 1.3.4 - passed
> 1 with Windows, IE with lib 1.3.4 - passed
> 1 with Linux, Chrome with lib 2.0a - failed
> 1 with Linux, Firefox with lib 2.0a - passed

After that, we would like to have ability to search [for test case runs], example of queries:
> Show me all test cases you've performed on 1.0.1 version on Linux
> Show me all test cases you've performed with lib 2.0a
> Is it the first time Lin+Chrome+2.0a failing?

At least for me such structure sounds pretty reasonable, but if you have ideas what we'r edoing wrong and how can we improve - we're open :)

**Comment by atodorov** [comment]
#105 describes how data is organized within Kiwi TCMS and I believe searching by the TestCaseRun.notes field will not meet your needs because TestCaseRun has a 1-to-1 relation with the TestCase model. Information about the test environment is held in the TestRun object and when doing reports needs to be retrieved from there. 

I am closing this as wontfix b/c I don't believe searching by notes will ever be practical. I even think that field should be entirely removed since it duplicates what the comments do.

I will be working on some fixes and improvements to the Advanced Search functionality in order to make filtering by env properties work and having the search results show more useful info.
