### ISSUE TITLE
Error 500 on attempt to clone certain test cases

### ISSUE THREAD

**Issue by HelgaOR** [kiwitcms/Kiwi#815]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

When trying to clone some test cases, I get 500 internal error. I reproduced this on https://demo.kiwitcms.org with test case ID 3864, though now it does not reproduce. Steps I provide do not produce error 100% of time. 

### Steps to Reproduce

1. Create test plan, test case
2. Clone test case to the same plan
3. Change new test case to "confirmed", then clone it.

### Actual results
Error 500.

**Comment by HelgaOR** [comment]
Reproduced it again for link:
https://demo.kiwitcms.org/case/3864/?from_plan=None

Got this link after editing the case.

**Comment by atodorov** [comment]
This is fixed in b31df448f6d9e55d23a57bb1275e0d2be2d6c9d6 and not yet deployed to the demo.
