### ISSUE TITLE
Kiwi development static file `bootstrap-switch.min.js` does not exist

### ISSUE THREAD

**Issue by gitaarik** [kiwitcms/Kiwi#827]
I try run Kiwi for development on my system, I cloned the repo, installed pip dependencies, ran `npm install`, `./manage.py migrate` and `./managa.py runserver`, that goes fine, but when I go to the `/plans/new/` url I get:

    Static file "bootstrap-switch/dist/js/bootstrap-switch.min.js" does not exist and will cause 404 errors!

Any ideas?

**Comment by atodorov** [comment]
You are missing something, maybe bootstrap-switch wasn't installed (see your npm logs). Here's all the packages I have and I can't reproduce.

This error is coming from the storage backend which in devel mode is configured to raise exception when a static file isn't found locally.

Have you changed `STATICFILES_DIRS` setting ?


```
$ pip freeze
alabaster==0.7.12
asn1crypto==0.24.0
astroid==2.2.0
Babel==2.6.0
bandit==1.5.1
bleach==3.1.0
bleach-whitelist==0.0.9
certifi==2018.11.29
cffi==1.12.2
chardet==3.0.4
coverage==4.5.2
cryptography==2.6
defusedxml==0.5.0
Deprecated==1.2.4
Django==2.1.7
django-attachments==1.4
django-contrib-comments==1.9.1
django-debug-toolbar==1.11
django-extensions==2.1.6
django-glrm==1.1.3
django-grappelli==2.12.2
django-modern-rpc==0.11.1
django-simple-history==2.7.0
django-uuslug==1.1.8
django-vinaigrette==1.2.0
docutils==0.14
entrypoints==0.3
epydoc==3.0.1
factory-boy==2.11.1
Faker==1.0.2
flake8==3.7.7
gitdb2==2.0.5
GitPython==2.1.11
idna==2.8
imagesize==1.1.0
isort==4.3.9
Jinja2==2.10
jira==2.0.0
lazy-object-proxy==1.3.1
Markdown==3.0.1
MarkupSafe==1.1.1
mccabe==0.6.1
mock==2.0.0
oauthlib==3.0.1
packaging==19.0
pbr==5.1.2
pkginfo==1.5.0.1
pycodestyle==2.5.0
pycparser==2.19
pydot==1.4.1
pyflakes==2.1.0
PyGithub==1.43.5
Pygments==2.3.1
PyJWT==1.7.1
pylint==2.3.0
pylint-django==2.0.5
pylint-plugin-utils==0.4
pyOpenSSL==19.0.0
pyparsing==2.3.1
python-bugzilla==2.2.0
python-dateutil==2.8.0
python-gitlab==1.8.0
python-slugify==2.0.1
pytz==2018.9
PyYAML==3.13
readme-renderer==24.0
requests==2.21.0
requests-oauthlib==1.2.0
requests-toolbelt==0.9.1
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.2.1
Sphinx==1.8.4
sphinxcontrib-websupport==1.1.0
sqlparse==0.2.4
stevedore==1.30.0
text-unidecode==1.2
tqdm==4.31.1
twine==1.13.0
typed-ast==1.2.0
Unidecode==1.0.23
urllib3==1.24.1
webencodings==0.5.1
wrapt==1.11.1
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(kiwitemp) [atodorov@aero Kiwi]$ npm list
/tmp/Kiwi
├── marked@0.6.1
├─┬ patternfly@3.59.1
│ ├─┬ @types/c3@0.6.3
│ │ └─┬ @types/d3@4.13.1
│ │   ├── @types/d3-array@1.2.6
│ │   ├── @types/d3-axis@1.0.12
│ │   ├── @types/d3-brush@1.0.10
│ │   ├── @types/d3-chord@1.0.9
│ │   ├── @types/d3-collection@1.0.8
│ │   ├── @types/d3-color@1.2.2
│ │   ├── @types/d3-dispatch@1.0.7
│ │   ├── @types/d3-drag@1.2.3
│ │   ├── @types/d3-dsv@1.0.36
│ │   ├── @types/d3-ease@1.0.8
│ │   ├── @types/d3-force@1.2.1
│ │   ├── @types/d3-format@1.3.1
│ │   ├─┬ @types/d3-geo@1.11.1
│ │   │ └── @types/geojson@7946.0.6
│ │   ├── @types/d3-hierarchy@1.1.6
│ │   ├── @types/d3-interpolate@1.3.1
│ │   ├── @types/d3-path@1.0.8
│ │   ├── @types/d3-polygon@1.0.7
│ │   ├── @types/d3-quadtree@1.0.7
│ │   ├── @types/d3-queue@3.0.8
│ │   ├── @types/d3-random@1.1.2
│ │   ├── @types/d3-request@1.0.5
│ │   ├── @types/d3-scale@1.0.14
│ │   ├── @types/d3-selection@1.4.1
│ │   ├── @types/d3-shape@1.3.1
│ │   ├── @types/d3-time@1.0.10
│ │   ├── @types/d3-time-format@2.1.1
│ │   ├── @types/d3-timer@1.0.9
│ │   ├── @types/d3-transition@1.1.4
│ │   ├── @types/d3-voronoi@1.1.9
│ │   └── @types/d3-zoom@1.7.4
│ ├── bootstrap@3.4.1
│ ├── bootstrap-datepicker@1.8.0
│ ├── bootstrap-sass@3.4.1
│ ├── bootstrap-select@1.12.2
│ ├── bootstrap-slider@9.10.0
│ ├── bootstrap-switch@3.3.4
│ ├── bootstrap-touchspin@3.1.1
│ ├── c3@0.4.23
│ ├── d3@3.5.17
│ ├── datatables.net@1.10.19
│ ├── datatables.net-colreorder@1.5.1
│ ├─┬ datatables.net-colreorder-bs@1.3.3
│ │ └── datatables.net-bs@1.10.19
│ ├── datatables.net-select@1.2.7
│ ├── drmonty-datatables-colvis@1.1.2
│ ├── eonasdan-bootstrap-datetimepicker@4.17.47
│ ├── font-awesome@4.7.0
│ ├── font-awesome-sass@4.7.0
│ ├── google-code-prettify@1.0.5
│ ├── jquery@3.2.1
│ ├── jquery-match-height@0.7.2
│ ├── moment@2.24.0
│ ├── moment-timezone@0.4.1
│ ├── patternfly-bootstrap-combobox@1.1.7
│ └── patternfly-bootstrap-treeview@2.1.8
├─┬ simplemde@1.11.2
│ ├── codemirror@5.44.0
│ └─┬ codemirror-spell-checker@1.1.2
│   └── typo-js@1.0.3
└── typeahead.js@0.11.1
```

**Comment by gitaarik** [comment]
Bootstrap is installed with NPM, but that doesn't make Django find it. 
In your documentation it says to `npm install` in the root directory, 
that's where the package.json file is. But Django won't be able to find 
that file because it's somewhere in the node_modules/ directory in the 
root of the repository.

Should I do collectstatic? Would be weird for development.

No I haven't changed the STATICFILES_DIRS setting.

**Comment by atodorov** [comment]
> Should I do collectstatic? Would be weird for development.

nope, in devel mode STATICFILES_DIRS will instruct Django to look in `node_modules/` checkout how this setting is defined. Obviously for you this isn't working but I can't figure out why. 

What is your OS?

Is `node_modules/` under the  root directory of the project? 

Does `node_modules/` actually contain the path which Django is complaining about? 

What version of npm/node do you have ?

**Comment by gitaarik** [comment]
Ok, I had some bootstrap-switch files from patternfly:

```
$ find . -name "bootstrap-switch*"
./node_modules/patternfly/dist/sass/patternfly/dependencies/bootstrap-switch
./node_modules/patternfly/dist/sass/patternfly/dependencies/bootstrap-switch/bootstrap-switch.scss
./node_modules/patternfly/dist/less/bootstrap-switch.less
```

But not the `bootstrap-switch/dist/js/bootstrap-switch.min.js` file, so I tried `npm install bootstrap-switch` and after restarting the `runserver` that worked. Looking at the `package.json` file, `bootstrap-switch` is not a dependency. So maybe that should be added?

**Comment by atodorov** [comment]
Which version of patternfly do you have (npm list)? 

bootstrap-switch was a dependency to Patternfly and it does work for me. However I agree that we can add it into package.json to be extra safe. Maybe you were unlucky and picked some broken version of Patternfly, I don't know how that happened.

**Comment by gitaarik** [comment]
I was actually using `yarn` instead of `npm`. Now I'm using `npm` and that does work. `yarn` and `npm` differentiate on how they structure the sub-dependencies in the `node_modules/` directory. Which is not a problem if you don't use the files in `node_modules/` directly but only through javascript `import` statements. Anyway, it works now that I use `npm install` instead of `yarn install`.
