### ISSUE TITLE
PREVENT ABUSE on demo.kiwitcms.org !!!

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#829]
As of just recently we were seeing an increased amount of email notificiations by one particular user. Their account has been blocked and they have been notified. ATM we don't know if this is a legitimate experiment or an abuse!

Because on https://demo.kiwitcms.org everybody can see almost everything there is no way to prevent a malicious user from modifying objects created by another user and causing hundreds of email notifications to be sent to them!

**Comment by okainov** [comment]
From the beginning I was wondering why do you require somehow "real" account, for demo purposes it would be much better to have "test/test" admin account with some pre-created data (test plans, cases and runs), which you can redeploy every night, for example (in case someone deleted or screwed up everything)

**Comment by supranov** [comment]
Maybe create user (or Group) access control at Product can prevent a malicious user from modifying objects.
