### ISSUE TITLE
add chinese languages

### ISSUE THREAD

**Issue by yunpengb** [kiwitcms/Kiwi#840]
Hi, 
guys, I can help to do some translations work on Chinese Simplified languages.
The language is being used by 1.3 billion of people.
this is my Crowdin username: yunpeng01 (email yp.b@outlook.com)

**Comment by atodorov** [comment]
@yunpengb - thanks for offering to help.

You should be able to edit Chinese translations in Crowdin even without special permissions. Can you confirm this?

Crowdin should automatically open pull requests when there are new translations. The user opening pull requests is called @kiwitcms-bot.

**Comment by atodorov** [comment]
I see a PR for new Chinese translations so I think we can close this issue, right ?

**Comment by yunpengb** [comment]
Yes, I have make chinese translations to 100% now.
