### ISSUE TITLE
Test plan, test case - Add attachment - User is redirected to dashboard

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#846]
### Description of problem
User gets redirected to dashboard after uploading attachment.

### Version or commit hash (if applicable)
Version 6.5.3 (reproducible on demo)

### Steps to Reproduce

1. Open Test Run / Test Case
2. Add attachment

### Actual results
User is redirected to dashboard with Your attachment was uploaded.! confirmation message.

![image](https://user-images.githubusercontent.com/25688732/54112981-96eafe00-43e7-11e9-9e92-9504416cdaa9.png)

### Expected results
User stays on current page with Your attachment was uploaded.! confirmation message.

**Comment by atodorov** [comment]
Note: this will be fixed with the migration to Patternfly!

**Comment by atodorov** [comment]
Fixed meanwhile in https://github.com/kiwitcms/Kiwi/pull/1006
