### ISSUE TITLE
Test Plan - Attachments - Delete action is missing

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#847]
### Description of problem
User cannot delete attachments added to Test Plan.

### Version or commit hash (if applicable)
6.5.3 (reproducible on demo)

### Steps to Reproduce

1. Open Test Plan
2. Add attachment to test plan

### Actual results
Column Action is missing delete attachment action.

![image](https://user-images.githubusercontent.com/25688732/54113166-0365fd00-43e8-11e9-857e-bd95fcc2e4e6.png)

### Expected results
Column Action has delete attachment action.
User can delete attachment from Test Plan.

**Comment by atodorov** [comment]
The link is there but it isn't visible. There's a `<span class="pficon-error-circle-o"></span>` but it isn't visible b/c the Patternfly CSS isn't loaded.
