### ISSUE TITLE
Plan Type not loaded on test plan modifications

### ISSUE THREAD

**Issue by shadeimi** [kiwitcms/Kiwi#864]
### Description of problem
Starting from a non-Acceptance test plan, when an user try to modify the test plan, the plan type is not loaded and must be confirmed again.

### Version or commit hash (if applicable)
Latest Version

### Steps to Reproduce

1. Create a test plan of type != acceptance
2. Save it
3. Edit the test plan
4. Verify the test plan type field is acceptance

### Actual results
During the editing phase, the test plan must be selected again

### Expected results
During the editing phase, the test plan must be the previously selected type

**Comment by atodorov** [comment]
Which version is this ?

I believe it has been fixed in d23f9911ca49ef1afc2c982d417c7a85c2cae046 but that hasn't made its way into a newer release. Can you confirm by rebuilding the master branch ?

**Comment by atodorov** [comment]
Fixed in version 6.6
