### ISSUE TITLE
cant open testcase after I added issue when using linkonly

### ISSUE THREAD

**Issue by mikii111** [kiwitcms/Kiwi#885]
When using linkonly when setting up bug tracking I expect to be able to add any adress as I want 
When I add: 
URL format string: https://mantis.company.com/view.php?
RegExp for ID validation: id=
Type= Linkonly

and then add an issue to a test case I get this error when I try to open the test case from my test run:
Uncaught ReferenceError: grappelli is not defined
    at grappelli.min.js:1
    at grappelli.min.js:1
/case/14/caserun-detail-pane/?case_run_id=11&case_text_version=67:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

And there is a large spinner when I press on my test case

**Comment by mikii111** [comment]
reproduced on https://demo.kiwitcms.org/
Dont know how often the demosite is reset but can at this moment be found here:
https://demo.kiwitcms.org/runs/847/#caserun_3316
and look at the bug tracker named Mantis on the demo server

**Comment by atodorov** [comment]
The BT in question is misconfigured. Your regex is wrong. URL format string is also wrong. See the help text at:
https://public.tenant.kiwitcms.org/admin/testcases/bugsystem/5/change/
