### ISSUE TITLE
Edit and delete function does not work in new version 

### ISSUE THREAD

**Issue by esteroski** [kiwitcms/Kiwi#887]
When I select Edit or Delete option it shows a new screen with 500 internal server error; I'm using Kiwi TCMS with docker

**Comment by atodorov** [comment]
> When I select Edit or Delete option it s

Edit or Delete which object and from which page ?

500 ISE means an application traceback so try getting the logs (docker-compose up without -d should print them on the terminal).

**Comment by esteroski** [comment]
this is what is prints 
web_1  | 172.21.0.1 - - [03/Apr/2019:15:20:54 +0000] "GET /case/1/edit/?from_plan=1 HTTP/1.1" 500 10049 "https://localhost/case/1/?from_plan=1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

**Comment by esteroski** [comment]
![Screenshot_20190628_144245](https://user-images.githubusercontent.com/25193114/60370338-9f297200-99b3-11e9-9427-915ae2b345c9.png)

**Comment by esteroski** [comment]
i REALLY NEEE HELP
This is a big bug 'cause i can't even select a test case because it shows that screen

**Comment by atodorov** [comment]
It's been several months since we've requested error logs and they are not present so there's nothing we can do about this. Without a traceback there's no way to reproduce.

If you can reproduce on public.tenant.kiwitcms.org feel free to reopen.
