### ISSUE TITLE
production version installed but not appearing on localhost

### ISSUE THREAD

**Issue by johnsharp123** [kiwitcms/Kiwi#899]
I've successfully completed installation and the the containers seem up to date, but when I go to localhost after running the docker-compose command as shown below, nothing appears at the localhost address.

Here's what was run:
=============================

[user@localhost ~]$ cd Kiwi
[user@localhost Kiwi]$ sudo service docker start
[sudo] password for user: 
Redirecting to /bin/systemctl start docker.service
[user@localhost Kiwi]$ docker-compose up -d
kiwi_db is up-to-date
kiwi_web is up-to-date
[user@localhost Kiwi]$ list containers
bash: list: command not found...
[user@localhost Kiwi]$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                                               NAMES
d33eab4718e7        kiwitcms/kiwi:latest   "/bin/sh -c /httpd-f…"   28 hours ago        Up 12 minutes       8080/tcp, 8443/tcp, 0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   kiwi_web
309ae0cb6331        centos/mariadb         "/docker-entrypoint.…"   29 hours ago        Up 12 minutes       3306/tcp                                                            kiwi_db
[user@localhost Kiwi]$ dir
CHANGELOG.rst  docker-compose_orig.yml	Dockerfile  etc		      httpd-foreground	LICENSE   manage.py    README.rst	requirements  setup.py	tests
crowdin.yml    docker-compose.yml	docs	    greenkeeper.json  kiwi_lint		Makefile  MANIFEST.in  readthedocs.yml	setup.cfg     tcms
[user@localhost Kiwi]$ firewall-cmd --state
running
=====================================

disabling the firewall didn't seem to help.

Also, I'm not an expert on Kiwi TCMS or linux/centos, I'm just trying to install/run it to do a trial run with it to see if it will help me day-to-day. So if the answer is obvious but I don't know it...please be kind! and tell me what to do. Thanks!

**Comment by Prome88** [comment]
a) Did you try both localhost and 127.0.0.1 to access the application?
b) Can you elaborate on "nothing shows" - blank page, some kind of error msg?
c) What does `docker logs d33eab4718e7` show?

**Comment by atodorov** [comment]
@Prome88 thanks for reaching out. 

@johnsharp123 please use StackOverflow for support questions like these as documented in issue template.

**Comment by johnsharp123** [comment]
@Prome88 

a) yes, 

b) both localhost and 127.0.0.1 show "Testing 1 2 3 ..." and "This page is used to test the proper operation of the Apache HTTP server after it has been installed. If you can read this page it means that this site is working properly. This server is powered by CentOS.". 

c) the mentioned log's contents is pasted below; thanks for your help here.

[user@localhost Kiwi]$ docker logs d33eab4718e7
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 07 20:53:50.270107 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Sun Apr 07 20:53:50.330582 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 07 20:53:50.389143 2019] [auth_digest:notice] [pid 8] AH01757: generating secret for digest authentication ...
[Sun Apr 07 20:53:50.390700 2019] [lbmethod_heartbeat:notice] [pid 8] AH02282: No slotmem from mod_heartmonitor
[Sun Apr 07 20:53:50.391698 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Sun Apr 07 20:53:50.391934 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
[Sun Apr 07 20:53:50.395131 2019] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Sun Apr 07 20:53:50.395159 2019] [core:notice] [pid 8] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 07 21:23:26.304161 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Sun Apr 07 21:23:26.304430 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Apr 07 21:23:26.325046 2019] [auth_digest:notice] [pid 8] AH01757: generating secret for digest authentication ...
[Sun Apr 07 21:23:26.326151 2019] [lbmethod_heartbeat:notice] [pid 8] AH02282: No slotmem from mod_heartmonitor
[Sun Apr 07 21:23:26.326845 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Sun Apr 07 21:23:26.327000 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
[Sun Apr 07 21:23:26.329583 2019] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Sun Apr 07 21:23:26.329707 2019] [core:notice] [pid 8] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 08 22:40:46.735126 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Mon Apr 08 22:40:46.920747 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Apr 08 22:40:46.990842 2019] [auth_digest:notice] [pid 8] AH01757: generating secret for digest authentication ...
[Mon Apr 08 22:40:46.991866 2019] [lbmethod_heartbeat:notice] [pid 8] AH02282: No slotmem from mod_heartmonitor
[Mon Apr 08 22:40:46.992539 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Mon Apr 08 22:40:46.992714 2019] [ssl:warn] [pid 8] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
[Mon Apr 08 22:40:46.994762 2019] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Mon Apr 08 22:40:46.994792 2019] [core:notice] [pid 8] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 09 00:14:18.769902 2019] [ssl:warn] [pid 9] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Tue Apr 09 00:14:18.955368 2019] [ssl:warn] [pid 9] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 09 00:14:19.099396 2019] [auth_digest:notice] [pid 9] AH01757: generating secret for digest authentication ...
[Tue Apr 09 00:14:19.100980 2019] [lbmethod_heartbeat:notice] [pid 9] AH02282: No slotmem from mod_heartmonitor
[Tue Apr 09 00:14:19.102083 2019] [ssl:warn] [pid 9] AH01909: RSA certificate configured for 172.18.0.3:443 does NOT include an ID which matches the server name
[Tue Apr 09 00:14:19.102335 2019] [ssl:warn] [pid 9] AH01909: RSA certificate configured for 172.18.0.3:8443 does NOT include an ID which matches the server name
[Tue Apr 09 00:14:19.105689 2019] [mpm_prefork:notice] [pid 9] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_wsgi/4.6.5 Python/3.6 configured -- resuming normal operations
[Tue Apr 09 00:14:19.105727 2019] [core:notice] [pid 9] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by johnsharp123** [comment]
@promme88  

Thank you both for your help here. I've created the same issue in stackoverflow. Here is the link:
https://stackoverflow.com/questions/55636607/production-version-of-kiwi-tcms-gui-not-at-localhost
