### ISSUE TITLE
[UI] Help icon missing on New test case / Edit test case pages

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#905]
### Description of problem
When opening new test case form / edit test case form the help menu icon is not rendered.

### Version or commit hash (if applicable)
6.6, 6.7, reproducible on demo

### Steps to Reproduce

1. Open existing test case for edit e.g - https://demo.kiwitcms.org/case/3336/edit/
or
2. Open new test case form https://demo.kiwitcms.org/cases/new/

### Actual results
![image](https://user-images.githubusercontent.com/25688732/55936966-144c9d00-5c38-11e9-9a70-d18133fdc475.png)

### Expected results
Icon shown as on other parts of the app:
![image](https://user-images.githubusercontent.com/25688732/55937033-41994b00-5c38-11e9-8a74-3aec54499972.png)

**Comment by atodorov** [comment]
Yeah, not sure if this icon isn't being loaded or what else is happening. I don't see anything obvious in console log and this should really be loaded automatically when we pull Patternfly.

**Comment by Prome88** [comment]
Related issue fix in 6.8 is not connected to this issue as it still around in version 6.8.

**Comment by atodorov** [comment]
Try removing cache and refreshing the page or Ctrl+F5

**Comment by atodorov** [comment]
Scratch that, there's no fix released for this issue yet so maybe you were confused by the linked-in issue.

**Comment by atodorov** [comment]
FTR I now believe the root cause of this issue is the JavaScript/CSS loaded for our markdown editor. It looks like this problem happens on every page where we have the markdown editor present.  Something must be overriding/conflicting with FontAwesome after the editor is loaded.
