### ISSUE TITLE
New TP - notification settings appear turned off

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/Kiwi#916]
https://public.tenant.kiwitcms.org/plans/new/ - notification settings (bootstrap-switch buttons) seem to be off, but all of these fields default to True.

This seems like a UI only issue b/c before the page loads completely I can see checkboxes which are checked on.

Seen in version 6.7

I am wondering if it has anything to do with #905 .

@Prome88 how do these buttons look to you? 

Anyone else out there using an older version that can provide more info ?

**Comment by asankov** [comment]
Apparently, this is a bug within `bootstrap-switch`. this is used within `patternfly`. the faster workaround would be to make patternfly use older version, the longer solution would be to contribute the fix to `bootstrap-switch` and also to `patternfly`. both are in motion now
