### ISSUE TITLE
[UI/UX] Telemetry - Testing - Breakdown - Datepicker - Limit date-picker values

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#947]
Now user can (v6.9.0.2 on demo tenant):
- set value After to date in the future
- set value for Before to lower value then date in After

Which as intended yields no results, but user should be at least warned that there is something not with the inputed values.

Have you considered adding some additional checks to date-picker on telemetry:

Value for After 
- Limited to today or older dates
Value for Before 
-  Limited to today or older dates
- Value should be equal or smaller than value from After

**Comment by atodorov** [comment]
Indeed this is the case for every form where you can select before/after timestamps. Thanks for reporting.

**Comment by atodorov** [comment]
Closing, wontfix.
