### ISSUE TITLE
Kiwi container constantly restarts

### ISSUE THREAD

**Issue by VK3FNG** [kiwitcms/Kiwi#954]
Support requests and general questions must be posted to
[StackOverflow](https://stackoverflow.com/questions/tagged/kiwi-tcms)
and tagged with the **kiwi-tcms** tag! Issues are for bug reports and
feature request discussions only!

WARNING: do not publically report security issues in the bug tracker!
Ping us via email to coordinate the fix and disclosure of the problem!

HINT: try to reproduce bugs and errors at https://demo.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
After cloning the repo, running `docker-compose up -d` results in a container that constantly restarts.

### Version or commit hash (if applicable)
Docker CE 18.09.6 64 bit
Git repo cloned yesterday 2019-05-22

### Steps to Reproduce

1. Clone repo
2. run docker-compose up -d
3.

### Actual results
`docker container ls` results in a status 'Restarting (1) n seconds'
output from dockerd results in many messages mentioning "shim reaped", and ignoring events

see [This pastebin](https://pastebin.com/WKfbnDYg)

### Expected results
A running docker container that I can then run `docker exec -it kiwi_web /Kiwi/manage.py migrate` on

**Comment by atodorov** [comment]
there's nothing helpful in this pastebin. Direct your support questions to StackOverflow.
