### ISSUE TITLE
Add some kind of "Health Check" for bug tracker integration (Jira)

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#97]
I've added our Jira into Admin, so links to bugs work good. Trying to understand what can Kiwi do, I've also added Base URL (https://ourjiraaddress.com/) and API URL (https://ourjiraaddress.com/rest/api/2/project/ourprojname), filled login and password, but even when I mark a checkbox "Check to add Test Case(s) to Issue Tracker" from test run, looks like nothing happens. No any error appears.

It would be nice to have some kind of "health check" in issue tracker Admin page to make sure that everything was entered correctly. 
As an idea, it could be something like "Check that Kiwi can read issue details" by given URLs, credentials and (for check only) issue number.

Purpose: to be sure that integration works in general without guessing where the error is.

**Comment by atodorov** [comment]
note to self: indeed the configuration of external bug trackers is a bit tricky and very vaguely documented. I will add the necessary docs, also describing why you can't reset the Tracker Type back to null and how to configure authentication.

@GodfatherThe a health-check button would be the best I think but I'm not sure how easy is this to implement. I will have to take a look at it.

**Comment by GodfatherThe** [comment]
Potential stages which can be checked:
1. Just connection \ trying to create Bug Tracker object (i.e. jira.JIRA). Problems which may be found here - wrong address, missed "https" in address, wrong configured proxy (especially not obvious - it was required to unset http_proxy to be able to access JIRA in internal network), wrong credentials. I personally met all of those problems when I was trying to configure it.
2. Trying to get issue details. Input from a user is required "Please input some issue ID from your project and click <Check>". Problems which may be found here - no access to given project for given credentials.

**Comment by col-panic** [comment]
Version 7.1

I definitely fail to integrate redmine as bugtracker - and don't know where to look. From what I see, there is not even a request incoming to redmine, although the address is valid and can be reached from within the wiki docker container. (I tried by manually installing curl in the container, and fetching something as standard user)

Is there any way I can activate log output in the redmine connector as the only thing I see in the log output of the container is
```
kiwi_web | 172.20.0.1 - - [27/Nov/2019:12:00:55 +0000] "POST /json-rpc/ HTTP/1.0" 200 137 "https://hostname/runs/4/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0"
```
