### ISSUE TITLE
Where are the Chinese translation documents? I can assist in Chinese translation

### ISSUE THREAD

**Issue by xian-crazy** [kiwitcms/Kiwi#978]
Where are the Chinese translation documents? I can assist in Chinese translation

**Comment by atodorov** [comment]
https://kiwitcms.readthedocs.io/en/latest/contribution.html#translation

**Comment by xian-crazy** [comment]
thanks!
I found that the text such as "Search Test Plans" is already translation,but why it  is still  english in my local  address ,which is installed by docker . 
how can I use the new translation text!
