### ISSUE TITLE
Page display problem: navigation bar has a large blank

### ISSUE THREAD

**Issue by xian-crazy** [kiwitcms/Kiwi#979]
![页面显示bug](https://user-images.githubusercontent.com/6520452/59992918-b0efda00-9680-11e9-9a8f-e93a1f093152.gif)

**Comment by atodorov** [comment]
this is side effect of having old and new style templates.

**Comment by xian-crazy** [comment]
but How to eliminate this side effect？thx！

**Comment by atodorov** [comment]
by rewriting the entire page template to use Patternfly
