### ISSUE TITLE
Robotframework Integration

### ISSUE THREAD

**Issue by shadeimi** [kiwitcms/Kiwi#984]
I'm writing an integration between RF and Kiwi in order to track test execution status and load informations on the TCMS. Anyone interested?

**Comment by atodorov** [comment]
FTR can this framework export results in TAP or XML (junit.xml) ? It may be easier to just write a parser for the resulting format instead of a native add-on to the framework.

**Comment by atodorov** [comment]
FTR if you want to contribute go to https://github.com/shadeimi/zealand

**Comment by LazyEnot** [comment]
@atodorov, RF can produce xUnit XML, if this can help.

**Comment by atodorov** [comment]
@shadeimi I think this (vvv) is you:
https://www.meetup.com/Robot-Framework-Milano/events/269468758/

Great to see progress in this direction, I'm hoping to be able to help you out very soon.

**Comment by flyNinghao** [comment]
> I'm writing an integration between RF and Kiwi in order to track test execution status and load informations on the TCMS. Anyone interested?

Have you finished this?

**Comment by flyNinghao** [comment]
> I'm writing an integration between RF and Kiwi in order to track test execution status and load informations on the TCMS. Anyone interested?

I have some quetions about integrating RF and kiwi. Can kiwi control rf to run test case and get the test results? And how? Does kiwi offer the api for rf to send messages back, or kiwi just run rf's test cases(think it's not possible.) And I tried to run the follow command: robot --listener zealand.listener.KiwiTCMS and nothing happened. I am really confused.
