### ISSUE TITLE
Header - Test case more actions button / menu shown

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#991]
Unauthorized user is shown more actions button twice on login page and they persist also inside the app when I login (both link to https://public.tenant.kiwitcms.org/case/5129/edit/) on my user.

https://public.tenant.kiwitcms.org/accounts/login/?next=/ , 6.10-enterprise

![image](https://user-images.githubusercontent.com/25688732/60577705-27c35c00-9d80-11e9-8edf-8d95296163ae.png)

![image](https://user-images.githubusercontent.com/25688732/60577718-2bef7980-9d80-11e9-8f4d-a6d754fa88ba.png)

**Comment by atodorov** [comment]
ack, not sure why this is happening. Could be a side effect of the newer Django version. Need to investigate more.

**Comment by atodorov** [comment]
FTR a restart of the container fixed this. The test cases linked from the menu are with IDs 5126 and 5129. Both of them have names in Spanish which should be fine b/c everything underneath is UTF8. 

5129 has attachments by different users and there's also an error report in Sentry for one of the attachments failing to upload b/c filename contained unicode characters (we've seen it before and upstream wasn't able to reproduce).

My best guess for now is that when something crashes while attaching files or editing the page this header menu is cached somewhere and then cache is not cleaned (properly).

**Comment by Tomasito-cca** [comment]
Hello, something new with this error? In our company we have a little trouble with this problem.

**Comment by atodorov** [comment]
> Hello, something new with this error? In our company we have a little trouble with this problem.

Restart your docker containers or contribute a pull request. As you see the issue has not been fixed yet.

**Comment by atodorov** [comment]
Still happens and it's hard to figure out why exactly.
