### ISSUE TITLE
Remove HTTPS and SSL

### ISSUE THREAD

**Issue by okainov** [kiwitcms/Kiwi#997]
### Description of problem

Web app should not include certificates and SSL stuff, this should be handled by the user (Kiwi instance maintainer) and reverse proxy. App should just expose simple HTTP port :)

Please remove all SSL-related settings and certs so app starts just with http

**Comment by atodorov** [comment]
> App should just expose simple HTTP port :)

IMO this is a very bad idea b/c we've already seen users running Kiwi TCMS in a very non-secure way.  There is no additional benefit of running plain/text HTTP (and I'm sure there will be lots of requests to re-enable https immediately). I also recognize serving the default SSL certs is marginally more secure but it's better than not having anything at all ? 

Many instances are not running behind an SSL terminator or reverse proxy. This is not the default setup so if you are using it then overriding the certificates is not a problem for you. 

Instead let's talk about what your use-case is? Why having the default SSL certs in the app is a problem for you ?

**Comment by okainov** [comment]
Because I have my reverse proxy with all my certificates on my host already :) And I believe this IS the default setup usually :)

If one is not having SSL terminator, then it would be perfectly fine to use plain HTTP there, it is somehow expected, isn't it?

If you're running kiwi inside your internal network for your team, then noone really cares about HTTP/HTTPS, so even if it's "not secure" it doesn't matter. But if one has certificate, then one has entrypoing nginx or so :)

**Comment by atodorov** [comment]
> Because I have my reverse proxy with all my certificates on my host already :)

Then having the application ship the default certs which you have overriden is not a problem for you, is it ? 

> And I believe this IS the default setup usually :)

We've seen quite a few setups where this is not the case and teams which don't have a dedicated sysadmin/devops person for their testing infrastructure. So definitely not the case usually.

> If one is not having SSL terminator, then it would be perfectly fine to use plain HTTP there, it is somehow expected, isn't it?

No. You should always run SSL enabled, even on internal network. It does matter if your passwords are sent over plain/text or encrypted channel, even if you don't really care. 

By default Kiwi TCMS tries to run in a secure manner as much as possible, which in this case means HTTPS.

With the current setup there are several possibilities to configure your own ssl certificates:
- bind-mount them via docker-compose.yml
- bake them inside your own customized docker image
- use reverse proxy SSL (nginx and haproxy examples in doc but you can use anything you want)
- if you are deploying as a WSGI application (e.g. no docker) then just overwrite the dafault SSL cert your httpd uses

If we disable SSL this means that users wanting to use their own certs will have to
1) Reconfigure Apache to serve Kiwi TCMS over HTTPS and bind-mount or build their own docker image
2) Provide their SSL certs via one of the methods above.

I don't see a point in adding 1 extra step (which involves several smaller steps) which doesn't bring any benefit. I will close this issue after 1 week if I don't hear from other users.


Notes:

1) If someone can propose an even easier way to override the default SSL certs please say so, preferably in another issue or a pull request/docs update

2) We recognize that shipping a default SSL cert (which may have expired or will expire at some point) that isn't signed by a well-known CA is a slight problem. Suggestions/pull requests how to improve this are welcome.

**Comment by atodorov** [comment]
No updates on this ticket to 10/7 days so closing.

**Comment by mmospanenko** [comment]
It doesn't work with reverse proxy, could you provide (and test it to see) some docs for Traefik?
